### PR TITLE
Feat/camel refactor

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1645
- https://github.com/openmpf/openmpf/issues/799

**Related PRs:**
- https://github.com/openmpf/openmpf.github.io/pull/168

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 29 of 35 files at r1, 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)* status: all files reviewed, 17 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIVGjS33GhPYH8UDBU:-NWIVGjUAfjKxz7ezfqR:b-oste5a) (no related file):*
Remove `TrackMergingContext.java`.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIl8XO7pjMskmIZ70W:-NWIl8XP1TBOPNz8lACk:bvhtlpg) (no related file):*
Review and update this doc: https://openmpf.github.io/docs/site/Workflow-Manager-Architecture/index.html#job-management

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIlO3FCGPJvKFa58ae:-NWIlO3FCGPJvKFa58af:bstw5ji) (no related file):*
Provide a general summary of the changes here: https://github.com/openmpf/openmpf/issues/1645. That issue is missing a description.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWKyX3Q3yI-2s5gnbsp:-NWKyX3R9zN29hqZPW-y:b-dfjwbf) (no related file):*
The format of these log lines is different:

```
2023-05-25 22:41:11,521 WARN [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.o.m.MarkupSplitter - [Job 626] Skipping '4: /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/Corrupted.png' - it is in an error state.
```

```
2023-05-25 22:41:07,849 WARN [Camel (camelContext) thread #8 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.o.d.DetectionTaskSplitter - [Job 626] Skipping Media #4 - it is in an error state.
```

If you look for "it is in an error state" in the code we log this message 4 slightly different ways. We should be consistent.

I propose we standardize on:

```
 [Job 626] Skipping media 4. It is in an error state.
```

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIOX_318BNvzyg03eC:-NWIOX_318BNvzyg03eD:b-80zug1) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java#L8)):*
> ```Java
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2022 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update year.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIOYo_CM2xwyL5K_MI:-NWIOYo_CM2xwyL5K_MJ:b-80zug1) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java#L12)):*
> ```Java
> 
> /******************************************************************************
>  * Copyright 2022 The MITRE Corporation                                       *
> ```

Update year.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java` line 47 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIpQbl3A8bm-oTrpuZ:-NWIpQbl3A8bm-oTrpu_:b-7evf22) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java#L47)):*
> ```Java
>     private static final Logger LOG = LoggerFactory.getLogger(WfmLocalSplitter.class);
> 
>     private final InProgressBatchJobsService _inProgressJobs;
> ```

Could this be protected so that the `MediaInspectionSplitter` and `RemoteMediaSplitter` can both access it instead of having their own data members?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWISaZ719rZGHcLNvCB:-NWISaZ719rZGHcLNvCC:b-80zug1) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java#L8)):*
> ```Java
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2022 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update year.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIScbw4_d0HJm2zTek:-NWIScbx6r-a3qHUSawS:b-80zug1) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java#L12)):*
> ```Java
> 
> /******************************************************************************
>  * Copyright 2022 The MITRE Corporation                                       *
> ```

Update year.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 67 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWJzDNcEKftN2fXC9pS:-NWJzDNd0_LcEYZKQ_NA:bfr5hxb) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L67)):*
> ```Java
>     private final InProgressBatchJobsService _inProgressJobs;
>     private final MediaInspectionHelper _mediaInspectionHelper;
>     private final JsonUtils _jsonUtils;
> ```

Not used.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java` line 128 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWJzSOR9TY56rcPPOqA:-NWJzSOR9TY56rcPPOqB:bcpgxv4) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L128)):*
Unrelated to your updates, but please address this:

> The static method actionAppliesToMedia(Media, Map<String,String>) from the type AggregateJobPropertiesUtil should be accessed in a static way
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionSplitter.java` line 42 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIqAGR6vcQG4YuZILX:-NWIqAGS2aNQVXI5Pddv:bhntumi) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionSplitter.java#L42)):*
> ```Java
> import org.mitre.mpf.wfm.data.entities.persistent.Media;
> import org.mitre.mpf.wfm.enums.MpfHeaders;
> import org.mitre.mpf.wfm.util.IoUtils;
> ```

IoUtils not used.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java` line 79 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIYura-w0pp97TFVI6:-NWIYurd7hK7wuOq-6OV:bdkxffk) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java#L79)):*
> ```Java
>                 // Splitter will set the "CamelJmsDestinationName" header to
>                 // specify the destination.
>                 .to("jms:queue:dummy")
> ```

Is this necessary because you have to have a `to()` here?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/TrackCache.java` line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIR_SY34hLRr1Xqyq7:-NWIR_SY34hLRr1Xqyq8:bqbzgpk) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/TrackCache.java#L1)):*
> ```Java
> package org.mitre.mpf.wfm.data;
> ```

Add header comment blocks.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java` line 148 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIxVmK7r5RJEZkKMrn:-NWIxVmK7r5RJEZkKMro:b-v9esk2) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java#L148)):*
> ```Java
> 
>     private void generateAndRunMerge(String samplingInterval, String mergeTracks, String minGap, String minTrackSize,
>                                      int expectedTracks) {
> ```

Change to `numExpectedTracks`.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java` line 166 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIxbSn5k-dnkLf4pSx:-NWIxbSoArxhk1hzfbNP:b-v9esk2) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java#L166)):*
> ```Java
>      */
>     private void generateAndRunMerge(String filePath, MediaType mediaType, String mimeType, String samplingInterval,
>                                      String mergeTracks, String minGap, String minTrackSize, int expectedTracks) {
> ```

Change to `numExpectedTracks`.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BeginTaskProcessor.java` line 62 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIOQyl1p3ounwKoxQr:-NWIOQyl1p3ounwKoxQs:b-x066f6) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BeginTaskProcessor.java#L62)):*
> ```Java
> 
>         if (job.getCurrentTaskIndex() > 0) {
>             log.info("Task Complete! Progress is now {}/{}.",
> ```

I found this a little confusing since the first thing this "Begin" task processor does is log task complete. Please leave a comment here.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)* status: all files reviewed, 19 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIQs_kBr-df8vyfhIb:-NWIQs_kBr-df8vyfhIc:b-80zug1) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java#L8)):*
> ```Java
>  * 52.227-14, Alt. IV (DEC 2007).                                             *
>  *                                                                            *
>  * Copyright 2022 The MITRE Corporation. All Rights Reserved.                 *
> ```

Update year.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIQut4CWBHn88-AvbK:-NWIQut4CWBHn88-AvbL:b-80zug1) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java#L12)):*
> ```Java
> 
> /******************************************************************************
>  * Copyright 2022 The MITRE Corporation                                       *
> ```

Update year.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)* status: 9 of 49 files reviewed, 19 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIVGjS33GhPYH8UDBU:-NWNj5OC0SI5LFrvq8n2:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove `TrackMergingContext.java`.
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWKyX3Q3yI-2s5gnbsp:-NWNjoym1IKC_50d2Jw0:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The format of these log lines is different:

```
2023-05-25 22:41:11,521 WARN [Camel (camelContext) thread #7 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.o.m.MarkupSplitter - [Job 626] Skipping '4: /home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/Corrupted.png' - it is in an error state.
```

```
2023-05-25 22:41:07,849 WARN [Camel (camelContext) thread #8 - JmsConsumer[MPF.JOB_ROUTER]] o.m.m.w.c.o.d.DetectionTaskSplitter - [Job 626] Skipping Media #4 - it is in an error state.
```

If you look for "it is in an error state" in the code we log this message 4 slightly different ways. We should be consistent.

I propose we standardize on:

```
 [Job 626] Skipping media 4. It is in an error state.
```


</blockquote></details>

Done.

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIOX_318BNvzyg03eC:-NWNme4O0iEpak-gpnf4:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update year.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIOYo_CM2xwyL5K_MI:-NWNmea-4mqDVPEvVlRV:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BroadcastEnabledAggregator.java#L12)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update year.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIQs_kBr-df8vyfhIb:-NWNmjTq-10Gos2s31Sa:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update year.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIQut4CWBHn88-AvbK:-NWNmjlGBPLrSJpXsQqS:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java#L12)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update year.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java` line 47 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIpQbl3A8bm-oTrpuZ:-NWNnm_L-ZWwXIVSr8Al:b7vn097) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/WfmLocalSplitter.java#L47)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Could this be protected so that the `MediaInspectionSplitter` and `RemoteMediaSplitter` can both access it instead of having their own data members?
</blockquote></details>

Typically in Java, all member variables are private, even when it causes additional verbosity. Getters and setters are an example of this added verbosity. Personally, I think referring to a variable defined in another class is sloppy.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java` line 8 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWISaZ719rZGHcLNvCB:-NWNpcem3WkjA2JpNZZY:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java#L8)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update year.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java` line 12 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIScbw4_d0HJm2zTek:-NWNpd3zE23YWRyg4WUj:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/CommitUpdatedTracksProcessor.java#L12)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Update year.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 67 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWJzDNcEKftN2fXC9pS:-NWNppT16xawMOxJaL92:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L67)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Not used.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java` line 128 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWJzSOR9TY56rcPPOqA:-NWNpxgf4jckRC8TJpvB:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L128)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Unrelated to your updates, but please address this:

> The static method actionAppliesToMedia(Media, Map<String,String>) from the type AggregateJobPropertiesUtil should be accessed in a static way
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionSplitter.java` line 42 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIqAGR6vcQG4YuZILX:-NWNq-3-0PSluTBvUA5V:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaInspectionSplitter.java#L42)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

IoUtils not used.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java` line 79 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIYura-w0pp97TFVI6:-NWNqJzRDu96-OX86Q6R:bseb2m8) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java#L79)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this necessary because you have to have a `to()` here?
</blockquote></details>

That way of doing it is from: https://camel.apache.org/components/3.20.x/jms-component.html#_reuse_endpoint_and_send_to_different_destinations_computed_at_runtime

Without that, Camel wouldn't know that the message is supposed to go to a JMS queue.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/TrackCache.java` line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIR_SY34hLRr1Xqyq7:-NWNqtR42BkOxti0SOKm:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/TrackCache.java#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add header comment blocks.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java` line 148 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIxVmK7r5RJEZkKMrn:-NWNr9i9D_5DOCJJW0dV:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java#L148)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change to `numExpectedTracks`.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java` line 166 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIxbSn5k-dnkLf4pSx:-NWNrGjG1eyLuV02kPXo:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestTrackMergingProcessor.java#L166)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Change to `numExpectedTracks`.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BeginTaskProcessor.java` line 62 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIOQyl1p3ounwKoxQr:-NWNm8VG5Z4xmApyF_k6:b-ei89ve) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BeginTaskProcessor.java#L62)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I found this a little confusing since the first thing this "Begin" task processor does is log task complete. Please leave a comment here.
</blockquote></details>

I don't understand the confusion, so I don't know what you want the comment to say.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)* status: 9 of 49 files reviewed, 19 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIl8XO7pjMskmIZ70W:-NWODHaREv7xPXVKlk4_:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Review and update this doc: https://openmpf.github.io/docs/site/Workflow-Manager-Architecture/index.html#job-management
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIlO3FCGPJvKFa58ae:-NWODHyeCUTQK54N9Eoj:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Provide a general summary of the changes here: https://github.com/openmpf/openmpf/issues/1645. That issue is missing a description.
</blockquote></details>

Done.

___

**Review by jrobble — COMMENTED** [review]
> Reviewed 3 of 40 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)* status: all files reviewed, 3 unresolved discussions (waiting on @brosenberg42)

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)* status: all files reviewed, 3 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWKyX3Q3yI-2s5gnbsp:-NXM5GZOBc9o0dT-qS_u:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I should have been more clear and asked you to update all four places. I only mentioned two of the four.
</blockquote></details>

Done.

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java` line 79 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIYura-w0pp97TFVI6:-NXM3y-N1xGgWxoih6AF:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/JobRouterRouteBuilder.java#L79)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Got it. Please provide that link in a comment.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BeginTaskProcessor.java` line 62 at r2](https://reviewable.io/reviews/openmpf/openmpf/1646#-NWIOQyl1p3ounwKoxQr:-NXM3j69DLNp2V38bDHU:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/311cf48488c0974ec662dce792edcf3709ed8208/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/BeginTaskProcessor.java#L62)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How about: "If this is not the first task, log that the previous task completed."
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1646)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
