### PR TITLE
Fix times in output object for VFR videos.

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1313

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1334)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1334)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1334#-Ma_NolfEbr8nC0ofEFP:-Ma_NolfEbr8nC0ofEFQ:bf4be9l) (no related file):*
As a reminder, you mentioned updating this to optionally disable the improved timestamp behavior for performance reasons.

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1334#-Maa_dAF2WHu6VBSM7H3:-Maa_dAF2WHu6VBSM7H4:b3d0lan) (no related file):*
I ran a nightly test build thinking that some of the timestamps would be different. Everything passed.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 218 at r1](https://reviewable.io/reviews/openmpf/openmpf/1334#-MaZKCmpAeJY_TnvE6oe:-MaZKCmpAeJY_TnvE6of:b-hqq7hw) ([raw file](https://github.com/openmpf/openmpf/blob/727e0e0dcad3557d1fee34feb5ca1537fe314462/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L218)):*
> ```Java
>                 continue;
>             }
>             frameTimes[i] = (int) (i * msPerFrame);
> ```

Is this last case for frame 0 only? Wouldn't it always return 0? Do we need to consider start time?

Have you ever seen a video where `ffprobe` did not return the time for frame 0? I don't see any unit tests for this case.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java, line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf/1334#-MaaV_j6EZn_Lpbtc0vI:-MaaV_j6EZn_Lpbtc0vJ:b-nffv5r) ([raw file](https://github.com/openmpf/openmpf/blob/727e0e0dcad3557d1fee34feb5ca1537fe314462/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java#L46)):*
> ```Java
>     public void testMkv() throws IOException {
>         var videoPath = TestUtil.findFilePath("/samples/five-second-marathon-clip.mkv");
>         compareTimes(videoPath, 29.97, true, false);
> ```

Why not check the last frame here? This is the only test in this file which skips it, so it seems a little strange. Consider leaving a comment explaining as much.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java, line 131 at r1](https://reviewable.io/reviews/openmpf/openmpf/1334#-MaaZNo4BgYCKUYdZO3h:-MaaZNo4BgYCKUYdZO3i:b-4ocya8) ([raw file](https://github.com/openmpf/openmpf/blob/727e0e0dcad3557d1fee34feb5ca1537fe314462/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java#L131)):*
> ```Java
>         // we are also checking for a variable frame rate. best_effort_timestamp is always an
>         // integer, unlike best_effort_timestamp_time which is a floating point value.
>         // Using best_effort_timestamp to check for variable frame rate prevents the loss of
> ```

Please mention what `best_effort_timestamp` returns (PTS values).

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1334)* status: 9 of 17 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 218 at r1](https://reviewable.io/reviews/openmpf/openmpf/1334#-MaZKCmpAeJY_TnvE6oe:-MaiGF8879UVi0SQsdqV:b28mlp2) ([raw file](https://github.com/openmpf/openmpf/blob/727e0e0dcad3557d1fee34feb5ca1537fe314462/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L218)):*
> Is this last case for frame 0 only? 

Yes

> Wouldn't it always return 0?

Yes

> Do we need to consider start time?

We don't have any options here. If ffprobe outputs "N/A"  for the first frame, we have no way to determine the start time. We only call getStartTimeMs() when mediainfo reports a constant frame rate, because when we actually get PTS values, we can just use the first PTS value to get the start time.

> Have you ever seen a video where ffprobe did not return the time for frame 0?

No, but I think we should handle that case anyway.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java, line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf/1334#-MaaV_j6EZn_Lpbtc0vI:-Maia2fu92QwDdHF-uL0:b-bttoee) ([raw file](https://github.com/openmpf/openmpf/blob/727e0e0dcad3557d1fee34feb5ca1537fe314462/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java#L46)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why not check the last frame here? This is the only test in this file which skips it, so it seems a little strange. Consider leaving a comment explaining as much.
</blockquote></details>

Added comment
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java, line 131 at r1](https://reviewable.io/reviews/openmpf/openmpf/1334#-MaaZNo4BgYCKUYdZO3h:-Maia7hGDbCOzUE5r6u0:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/727e0e0dcad3557d1fee34feb5ca1537fe314462/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java#L131)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please mention what `best_effort_timestamp` returns (PTS values).
</blockquote></details>

Done.

**Comment by brosenberg42** [comment]
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1334#-Ma_NolfEbr8nC0ofEFP:-Maj0QPf5Puz-4yFdNiW:b-mxadl4) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As a reminder, you mentioned updating this to optionally disable the improved timestamp behavior for performance reasons.
</blockquote></details>

I found out ffprobe has a `-threads` argument, so now it performs the same as ffmpeg's vfrdet filter.

---

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r2, 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1334)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1334#-Ma_NolfEbr8nC0ofEFP:-MajK37M95Db1_1XXn5g:b4c9lyr) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I found out ffprobe has a `-threads` argument, so now it performs the same as ffmpeg's vfrdet filter.
</blockquote></details>

:thumbsup: 

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 270 at r3](https://reviewable.io/reviews/openmpf/openmpf/1334#-Maj_zGG09QQ9DAVnBvX:-Maj_zGG09QQ9DAVnBvY:b-3675j4) ([raw file](https://github.com/openmpf/openmpf/blob/a3728e95b309eea9b5e53fd22846924dba029836/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L270)):*
> ```Java
>         // Last frame needs special handling because it doesn't have a following value to use to
>         // calculate the average PTS value.
>         if (frameTimes.length > 2 && frameTimes[frameTimes.length - 1] <= 0) {
> ```

If `frameTimes[frameTimes.length - 1] <= 0` and `frameTimes.length <= 2` should we calculate the time for the last frame using fps like the special case for the second frame?
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 327 at r3](https://reviewable.io/reviews/openmpf/openmpf/1334#-MajOyhv9DBftDm8Pmf6:-MajOyhv9DBftDm8Pmf7:buiwlia) ([raw file](https://github.com/openmpf/openmpf/blob/a3728e95b309eea9b5e53fd22846924dba029836/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L327)):*
> ```Java
>     private static OptionalInt getStartTimeMs(Path mediaPath) {
>         String[] command = {
>                 "ffprobe", "-read_intervals", "%30" ,"-hide_banner", "-select_streams", "v",
> ```

Why print out time entries for the first 30 seconds if all we want is the first entry?

While trying to answer this question, I noticed that `TesseractOCRTextDetection/test/data/test-video-detection.avi`only produced the correct value using this new approach:

```
[mpf@openmpf-master openmpf]$ ffprobe -hide_banner -select_streams v -show_entries stream=start_time -print_format default=noprint_wrappers=1:nokey=1 /home/mpf/git/openmpf-projects/openmpf-components/cpp/TesseractOCRTextDetection/test/data/test-video-detection.avi 2>/dev/null
0.000000

[mpf@openmpf-master openmpf]$ ffprobe -read_intervals %30 -hide_banner -select_streams v -show_entries frame=best_effort_timestamp_time -print_format default=noprint_wrappers=1:nokey=1 ~/git/openmpf-projects/openmpf-components/cpp/TesseractOCRTextDetection/test/data/test-video-detection.avi 2>/dev/null
2.206278
N/A
N/A

[mpf@openmpf-master openmpf]$ ffprobe -read_intervals %+#1 -hide_banner -select_streams v -show_entries frame=best_effort_timestamp_time -print_format default=noprint_wrappers=1:nokey=1 ~/git/openmpf-projects/openmpf-components/cpp/TesseractOCRTextDetection/test/data/test-video-detection.avi 2>/dev/null
N/A
```

However, that video is VFR (and has "N/A" entries), so we would never bother getting the starting time. Note that `-read_intervals %1` produced the same output as `-read_intervals %30` for that video.

Are you trying to handle the same situation for CFR videos? Out of curiosity, have you seen a CFR video like that yet?

Side note: I noticed that for `BigBuckBunny_DivX_HD720p_ASP.divx` that your new command will print out all of the time entries (ending with "N/A"), not just the first 30 seconds. However, that video is not identified as CFR by `mediainfo`, so it will be treated like VFR and we'd never try to get the start time.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 351 at r3](https://reviewable.io/reviews/openmpf/openmpf/1334#-MajKb0t1_Dz4bu6VrFx:-MajKb0t1_Dz4bu6VrFy:b-uhfoch) ([raw file](https://github.com/openmpf/openmpf/blob/a3728e95b309eea9b5e53fd22846924dba029836/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L351)):*
> ```Java
>         }
>         catch (IOException | NumberFormatException e) {
>             LOG.error("Assuming start time of %s is 0 because the following error occurred " +
> ```

I think you intended to log the mediaPath in this message.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java, line 130 at r3](https://reviewable.io/reviews/openmpf/openmpf/1334#-MajJRh19-ZINIKIZMog:-MajJRh19-ZINIKIZMoh:byo4qd3) ([raw file](https://github.com/openmpf/openmpf/blob/a3728e95b309eea9b5e53fd22846924dba029836/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameTimeInfoBuilder.java#L130)):*
Extra space here:

> ```
>  is always an  integer
> ```

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 270 at r3](https://reviewable.io/reviews/openmpf/openmpf/1334#-Maj_zGG09QQ9DAVnBvX:-Majby5s8_WI4lDVRNrD:b-sztv7p) ([raw file](https://github.com/openmpf/openmpf/blob/a3728e95b309eea9b5e53fd22846924dba029836/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L270)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

If `frameTimes[frameTimes.length - 1] <= 0` and `frameTimes.length <= 2` should we calculate the time for the last frame using fps like the special case for the second frame?
</blockquote></details>

Actually, never mind. If `frameTimes.length <= 2` then the last frame is either the first or second frame and should already be handled in the above code.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1334)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 327 at r3](https://reviewable.io/reviews/openmpf/openmpf/1334#-MajOyhv9DBftDm8Pmf6:-Mamt4Qx8W6OefvLvF26:b-3cd1w0) ([raw file](https://github.com/openmpf/openmpf/blob/a3728e95b309eea9b5e53fd22846924dba029836/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L327)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why print out time entries for the first 30 seconds if all we want is the first entry?

While trying to answer this question, I noticed that `TesseractOCRTextDetection/test/data/test-video-detection.avi`only produced the correct value using this new approach:

```
[mpf@openmpf-master openmpf]$ ffprobe -hide_banner -select_streams v -show_entries stream=start_time -print_format default=noprint_wrappers=1:nokey=1 /home/mpf/git/openmpf-projects/openmpf-components/cpp/TesseractOCRTextDetection/test/data/test-video-detection.avi 2>/dev/null
0.000000

[mpf@openmpf-master openmpf]$ ffprobe -read_intervals %30 -hide_banner -select_streams v -show_entries frame=best_effort_timestamp_time -print_format default=noprint_wrappers=1:nokey=1 ~/git/openmpf-projects/openmpf-components/cpp/TesseractOCRTextDetection/test/data/test-video-detection.avi 2>/dev/null
2.206278
N/A
N/A

[mpf@openmpf-master openmpf]$ ffprobe -read_intervals %+#1 -hide_banner -select_streams v -show_entries frame=best_effort_timestamp_time -print_format default=noprint_wrappers=1:nokey=1 ~/git/openmpf-projects/openmpf-components/cpp/TesseractOCRTextDetection/test/data/test-video-detection.avi 2>/dev/null
N/A
```

However, that video is VFR (and has "N/A" entries), so we would never bother getting the starting time. Note that `-read_intervals %1` produced the same output as `-read_intervals %30` for that video.

Are you trying to handle the same situation for CFR videos? Out of curiosity, have you seen a CFR video like that yet?

Side note: I noticed that for `BigBuckBunny_DivX_HD720p_ASP.divx` that your new command will print out all of the time entries (ending with "N/A"), not just the first 30 seconds. However, that video is not identified as CFR by `mediainfo`, so it will be treated like VFR and we'd never try to get the start time.

</blockquote></details>

I have encountered videos that require `%5`. I used 30 to over estimate.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java, line 351 at r3](https://reviewable.io/reviews/openmpf/openmpf/1334#-MajKb0t1_Dz4bu6VrFx:-MamvatMC7DiCako4mg6:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/a3728e95b309eea9b5e53fd22846924dba029836/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfoBuilder.java#L351)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think you intended to log the mediaPath in this message.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1334)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
