### PR TITLE
Update opencv 3.2 gif

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/138)

### CODE REVIEW

**Comment by brosenberg42** [comment]
When running a pipeline with markup on a gif, the marked-up video files have green diagonal lines.


---

Reviewed 17 of 31 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[trunk/video-overlay/src/main/cpp/FrameCounter.cpp, line 69 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/138#-Kn_L-RA_jxVTMC9hBFr:-Kn_L-RA_jxVTMC9hBFs:b-mdww8u) ([raw file](https://github.com/openmpf/openmpf/blob/f4f0db8a63631fd2a90742d602c9141a3ace0de9/trunk/video-overlay/src/main/cpp/FrameCounter.cpp#L69)):*
> ```cpp
>                 }
> 
>                 if (bruteForce) {
> ```

Using VideoCapture.grab() (http://docs.opencv.org/3.2.0/d8/dfe/classcv_1_1VideoCapture.html#ae38c2a053d39d6b20c9c649e08ff0146) might be a little bit faster.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/138#-:-Kn_LlQCWGmVh5LQPXLh:blust24)*

**Comment by brosenberg42** [comment]
The green lines appear to be an issue with my version of VLC. I am unable to replicate in any other playback software.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/138#-:-Kn__t0e41AeOeU9G0Cz:b-29tpyi)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/138#-:-Kn_aqc0cZ5pTJbL1JIU:bnfp4nl)*

**Comment by jrobble** [comment]
*[trunk/video-overlay/src/main/cpp/FrameCounter.cpp, line 69 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/138#-Kn_L-RA_jxVTMC9hBFr:-KnaHMt7gxthZJoItpwa:b-weshvj) ([raw file](https://github.com/openmpf/openmpf/blob/f4f0db8a63631fd2a90742d602c9141a3ace0de9/trunk/video-overlay/src/main/cpp/FrameCounter.cpp#L69)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Using VideoCapture.grab() (http://docs.opencv.org/3.2.0/d8/dfe/classcv_1_1VideoCapture.html#ae38c2a053d39d6b20c9c649e08ff0146) might be a little bit faster.
</blockquote></details>

Good idea. I just implemented that approach.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/138)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4, 15 of 15 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/138#-:-KndP29pJ8TzOQHCOR75:bnfp4nl)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/138#-:-Knez_7pbYgkbjz4Jd6x:bnfp4nl)*

**Pull request merged**
