### PR TITLE
Handle missing video stream and improve MIME type detection

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1188)

### CODE REVIEW

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 50 of 52 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1188)* status: 50 of 52 files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 1254 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLNmFKtAxAwH5IfwKXn:-MLNmFKuClPmjFfOlefg:b-qq78gc) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L1254)):*
> ```Java
> 
>     @Test(timeout = 5 * MINUTES)
>     @Ignore // TODO: Will be fixed in HEIC/pngdefry PR.
> ```

Please remove the `@Ignore`
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java, line 244 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLNqAn568Swljs-x31G:-MLNqAn568Swljs-x31H:bwiiey9) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/MarkupController.java#L244)):*
> ```Java
>         }
> 
>         BatchJob job = Optional.ofNullable(jobRequestDao.findById(markupResult.getJobId()))
> ```

We should be checking `markupResult.getMarkupUri()` first to avoid the database lookup when the markup is stored locally. 
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java, line 56 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLORygE-0GNKoWKBVZS:-MLORygE-0GNKoWKBVZT:bytx76v) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java#L56)):*
> ```Java
>  * There is no fallback for the IMAGE data type. "image/*" MIME types are not containers like "video/*" MIME types.
>  *
>  * If one invalid media metadata property is identified then we do trust any of the properties. In that case fallback
> ```

I think you are missing a not here. Should this be "then we do **not** trust any"?
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java, line 66 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLORWsD8krzA9tzHS7o:-MLORWsD8krzA9tzHS7p:b-52au8d) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java#L66)):*
> ```Java
> 
>     // MIME_TYPE and MEDIA_HASH are common and checked first
>     private Set requiredAudioMetadata = Set.of("DURATION");
> ```

These 3 should be declared as `private static final Set<String>`
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java, line 173 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOWX4p5hAAZpTlso7o:-MLOWX4p5hAAZpTlso7p:bji7rzt) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java#L173)):*
> ```Java
>                                                 String type) {
>         String missingError = requiredMetadata.stream()
>                 .filter(key -> !mediaMetadata.containsKey(key) || mediaMetadata.get(key).isBlank())
> ```

This doesn't properly handle when the value in the map is `null`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 91 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOgikPEW_YcpUbKgxQ:-MLOgikQ8qiQtIaXVc8S:b-vjcbi8) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L91)):*
> ```Java
> 
>         String command = "file -m " + LINUX_MAGIC_PATH + ":" + customMagicPath + " --mime-type -b " + filePath;
>         Process process = Runtime.getRuntime().exec(command);
> ```

Please use ProcessBuilder here. This from the Process documentation: "As of 1.5, ProcessBuilder.start() is the preferred way to create a Process."
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 92 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOgztR-tiHvRDepWwR:-MLOgztR-tiHvRDepWwS:b-ll0377) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L92)):*
> ```Java
>         String command = "file -m " + LINUX_MAGIC_PATH + ":" + customMagicPath + " --mime-type -b " + filePath;
>         Process process = Runtime.getRuntime().exec(command);
>         int exitCode = process.waitFor();
> ```

You should read from the streams before calling `process.waitFor()`. You should also use a different thread to read from stderr so that you can read from stdout and stderr at the same time. Other usages of ProcessBuilder in the code don't use multiple threads because they call `.redirectErrorStream(true)` to combine stdout and stderr. This is from the Process documentation: "Because some native platforms only provide limited buffer size for standard input and output streams, failure to promptly write the input stream or read the output stream of the process may cause the process to block, or even deadlock."
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 94 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOjzR63cZgWTwz4xcK:-MLOjzR63cZgWTwz4xcL:blqe8hb) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L94)):*
> ```Java
>         int exitCode = process.waitFor();
>         String error = IOUtils.toString(process.getErrorStream(), "UTF-8").trim();
>         String output = IOUtils.toString(process.getInputStream(), "UTF-8").trim();
> ```

Please use `StandardCharsets.UTF_8` instead of `"UTF-8"`
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 110 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOr3oX9i6-dpZhsi81:-MLOr3oX9i6-dpZhsi82:b-udbuk7) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L110)):*
> ```Java
>     }
> 
>     public static String getPathContentType(String mimeType) {
> ```

It is extremely confusing to have one version that takes a file path and one that takes the mime type. There are many places in the code that use Strings for file paths, including this file. It also doesn't appear necessary since I fixed that exception.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 329 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOl7fw95w3wM5kRwgD:-MLOl7fw95w3wM5kRwgE:b-fm0rwv) ([raw file](https://github.com/openmpf/openmpf/blob/06bbbe2c47be1a90d17c80fb842728355445fef1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L329)):*
> ```Java
>     }
> ```

...why? It is extremely common to put two blank lines between function declarations. A single blank line is used to delimit sections in a single function. Now the the two are visually the same, making it much more difficult to find a function without ctrl+f. When you have short functions surrounded by longer ones it very hard to see the middle function at a glance. Specifically getMimeType, getMimeTypeUsingTika, getMimeTypeUsingFile have this issue. 
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java, line 109 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLPBgmR2ODbBDlK81YR:-MLPBgmS9zaN1DFIcCwB:b-kpwvlb) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java#L109)):*
> ```Java
>                 media.isFailed());
> 
> 	String mediaHash = "c067e7eed23a0fe022140c30dbfa993ae720309d6567a803d111ecec739a6713";// `sha256sum meds1.jpg`
> ```

It looks like tabs somehow got added here.

**Review by brosenberg42 — COMMENTED** [review]
I decided to just make most of the changes myself. I pushed a branch named `no-video-stream-changes` and started build #509. If that build passes, please merge it into this. 

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1188#-:-MLPF0X0A_Ayg3MstZJy:b-28stfc)* status: 50 of 52 files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @jrobble)

**Comment by brosenberg42** [comment]
That one failed because of a minor issue. I just started #510

**Review by jrobble — COMMENTED** [review]
Merged @brosenberg42 's branch into mine.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1188#-:-MLUjaiu-nqbE_6xHNAB:b-lru0v3)* status: 44 of 54 files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 1254 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLNmFKtAxAwH5IfwKXn:-MLUji6w-M546VAodQ-o:b-whxd16) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L1254)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Please remove the `@Ignore`
</blockquote></details>

Thanks for fixing this.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java, line 56 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLORygE-0GNKoWKBVZS:-MLUFn4b-mGpLoEto_VA:b-vgeesk) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java#L56)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think you are missing a not here. Should this be "then we do **not** trust any"?
</blockquote></details>

Good catch. Thanks for fixing this.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java, line 66 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLORWsD8krzA9tzHS7o:-MLUo2jGDHKsv2G8z37s:b-whxd16) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java#L66)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

These 3 should be declared as `private static final Set<String>`
</blockquote></details>

Thanks for fixing this.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java, line 173 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOWX4p5hAAZpTlso7o:-MLUoB2y3EUUizgs7GDa:b-whxd16) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/mediainspection/MediaMetadataValidator.java#L173)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This doesn't properly handle when the value in the map is `null`.
</blockquote></details>

Thanks for fixing this.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 91 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOgikPEW_YcpUbKgxQ:-MLUoXn13NRU3qszI_RA:b-whxd16) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L91)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Please use ProcessBuilder here. This from the Process documentation: "As of 1.5, ProcessBuilder.start() is the preferred way to create a Process."
</blockquote></details>

Thanks for fixing this.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 92 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOgztR-tiHvRDepWwR:-MLUGFzLDMj0-N7VgGwZ:b-whxd16) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L92)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You should read from the streams before calling `process.waitFor()`. You should also use a different thread to read from stderr so that you can read from stdout and stderr at the same time. Other usages of ProcessBuilder in the code don't use multiple threads because they call `.redirectErrorStream(true)` to combine stdout and stderr. This is from the Process documentation: "Because some native platforms only provide limited buffer size for standard input and output streams, failure to promptly write the input stream or read the output stream of the process may cause the process to block, or even deadlock."
</blockquote></details>

Thanks for fixing this.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 94 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOjzR63cZgWTwz4xcK:-MLUiGTD8C57VOBl85s_:b-whxd16) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L94)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Please use `StandardCharsets.UTF_8` instead of `"UTF-8"`
</blockquote></details>

Thanks for fixing this.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 110 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOr3oX9i6-dpZhsi81:-MLUHJhd8hKSLbm5T4WB:b-8kc5ws) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L110)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It is extremely confusing to have one version that takes a file path and one that takes the mime type. There are many places in the code that use Strings for file paths, including this file. It also doesn't appear necessary since I fixed that exception.
</blockquote></details>

Your updates address this and make sense to me.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java, line 329 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLOl7fw95w3wM5kRwgD:-MLUatVE6iROZqZjm1oc:b-wvdc3b) ([raw file](https://github.com/openmpf/openmpf/blob/06bbbe2c47be1a90d17c80fb842728355445fef1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/IoUtils.java#L329)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

...why? It is extremely common to put two blank lines between function declarations. A single blank line is used to delimit sections in a single function. Now the the two are visually the same, making it much more difficult to find a function without ctrl+f. When you have short functions surrounded by longer ones it very hard to see the middle function at a glance. Specifically getMimeType, getMimeTypeUsingTika, getMimeTypeUsingFile have this issue. 
</blockquote></details>

As discussed, I didn't realize you added two lines on purpose. In the future I'll assume it's intentional.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java, line 109 at r1](https://reviewable.io/reviews/openmpf/openmpf/1188#-MLPBgmR2ODbBDlK81YR:-MLUoc5wEBJQfsjePK6g:b-whxd16) ([raw file](https://github.com/openmpf/openmpf/blob/1a82b3443d35bf1d6a6d4ac31540e6de645f999b/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java#L109)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

It looks like tabs somehow got added here.
</blockquote></details>

Thanks for fixing this.

**Review by jrobble — COMMENTED** [review]
> Reviewed 44 of 52 files at r1, 10 of 10 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1188)* status: all files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @jrobble)

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 9 of 10 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1188)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
