### PR TITLE
Include job ids in log message when sending callbacks.

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/458)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 141 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5AfKqsTZscwnQG_Dwz:-L5AfKqsTZscwnQG_Dx-:blg1pwn) ([raw file](https://github.com/openmpf/openmpf/blob/15d2ba059725e1c9cd8b16d6fde31d1a0e1d84b5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L141)):*
> ```Java
>     // TODO: Implement doGetCallback
> 
>     private void sendPostCallback(List<Long> jobIds, Object json, String callbackUri) {
> ```

Looking at:

```
sendHealthReportCallback(String callbackUri, List<Long> jobIds)
```

The job ids come after the callback URI. Let's move the job ids as the last param in `sendPostCallback` for consistency.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/458)*

**Comment by brosenberg42** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 141 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5AfKqsTZscwnQG_Dwz:-L5AhciJ7RvIht9qK3S3:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/15d2ba059725e1c9cd8b16d6fde31d1a0e1d84b5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L141)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Looking at:

```
sendHealthReportCallback(String callbackUri, List<Long> jobIds)
```

The job ids come after the callback URI. Let's move the job ids as the last param in `sendPostCallback` for consistency.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/458)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 116 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C0M2PH2_BTY7L12iF:-L5C0M2Q2_tH3oa6Quro:bfccvso) ([raw file](https://github.com/openmpf/openmpf/blob/cef9f35994a1e19438d255a9b918e7f5c34fd48a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L116)):*
> ```Java
>         // instead of multiple times per job to get each of the following pieces of data.
> 
>         log.info("Starting POST of health report(s) with jobIds: " + jobIds);
> ```

Print out callback URI here as well. Say "job ids" (no colon) to be consistent with other messages.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 129 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5BydWdp_n7Xj9CSV9_:-L5BydWeowX7YCQXB0TC:b-3gny9t) ([raw file](https://github.com/openmpf/openmpf/blob/cef9f35994a1e19438d255a9b918e7f5c34fd48a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L129)):*
> ```Java
>             sendPostCallback(jsonBody, callbackUri, jobIds);
>         } catch (WfmProcessingException | MpfInteropUsageException e) {
>             log.error("Error sending health report(s) to " + callbackUri + ".", e);
> ```

Mention the job ids in this log message.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 135 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C0Pz9vHvOJgeQXjk0:-L5C0Pz9vHvOJgeQXjk1:b7f9lp7) ([raw file](https://github.com/openmpf/openmpf/blob/cef9f35994a1e19438d255a9b918e7f5c34fd48a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L135)):*
> ```Java
>     // Send the summary report to the URI identified by callbackUri, using the HTTP POST method.
>     public void sendSummaryReportCallback(JsonSegmentSummaryReport summaryReport, String callbackUri) {
>         log.info("Starting POST of summaryReport with jobId " + summaryReport.getJobId());
> ```

Print out callback URI here as well. Split "summaryReport" into "summary report".

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 141 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C0v-3YjWmZMwKwbvd:-L5C0v-3YjWmZMwKwbve:b-ibw88l) ([raw file](https://github.com/openmpf/openmpf/blob/cef9f35994a1e19438d255a9b918e7f5c34fd48a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L141)):*
> ```Java
>     // TODO: Implement doGetCallback
> 
>     private void sendPostCallback(Object json, String callbackUri, List<Long> jobIds) {
> ```

Consider passing in the callback type as well (e.g. "health report(s)" or "summary report". Instead of strings, maybe we should use a locally-defined enum that defines those human-readable strings.

Use that parameter in all of the log messages.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 174 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C-a0shsC5924NuQAr:-L5C-a0shsC5924NuQAs:b1tlsw9) ([raw file](https://github.com/openmpf/openmpf/blob/cef9f35994a1e19438d255a9b918e7f5c34fd48a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L174)):*
> ```Java
> 	                    log.warn("Callback for job ids {} sent to {}. Receiver did not respond.", jobIds, callbackUri);
>                     } else {
>                     	log.warn(String.format("Error sending callback for job ids %s to %s", jobIds, callbackUri), e);
> ```

Please change this back to printing out `e.getMessage()` so the log isn't polluted with these kinds of exceptions:

```
2018-02-12 21:33:50,150 WARN [pool-5-thread-1] org.mitre.mpf.wfm.util.CallbackUtils - Error sending callback for job ids [197] to http://localhost:2000
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_144]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_144]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) [httpcore-nio-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) [httpcore-nio-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) [httpcore-nio-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194) [httpasyncclient-4.1.3.jar:4.1.3]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.3.jar:4.1.3]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
```

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 182 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5BvfY-DyAkaBLPG59P:-L5BvfY-DyAkaBLPG59Q:b-j2vo2) ([raw file](https://github.com/openmpf/openmpf/blob/cef9f35994a1e19438d255a9b918e7f5c34fd48a/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L182)):*
> ```Java
>             });
>         } catch (WfmProcessingException | IllegalArgumentException e) {
>             log.error(String.format("Error sending for callback for job ids %s to %s.", jobIds, callbackUri), e);
> ```

Check grammar: "for callback for job"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/458)*

**Comment by brosenberg42** [comment]
Review status: 1 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 116 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C0M2PH2_BTY7L12iF:-L5ESK9esRvQj39NpcEf:b-n783dr) ([raw file](https://github.com/openmpf/openmpf/blob/568856823a879e974f22fac60a159b94866638b4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L116)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Print out callback URI here as well. Say "job ids" (no colon) to be consistent with other messages.
</blockquote></details>

This log message was moved in to the sendPostCallback method.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 129 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5BydWdp_n7Xj9CSV9_:-L5ERygoIwHIymtR_kUn:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/568856823a879e974f22fac60a159b94866638b4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L129)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Mention the job ids in this log message.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 135 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C0Pz9vHvOJgeQXjk0:-L5ES-hg4a_13bBOAPpq:bapht8p) ([raw file](https://github.com/openmpf/openmpf/blob/568856823a879e974f22fac60a159b94866638b4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L135)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Print out callback URI here as well. Split "summaryReport" into "summary report".
</blockquote></details>

This log message was moved in to the sendPostCallback method.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 141 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C0v-3YjWmZMwKwbvd:-L5ES8dowvM1mjoTZFjp:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/568856823a879e974f22fac60a159b94866638b4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L141)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Consider passing in the callback type as well (e.g. "health report(s)" or "summary report". Instead of strings, maybe we should use a locally-defined enum that defines those human-readable strings.

Use that parameter in all of the log messages.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 174 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5C-a0shsC5924NuQAr:-L5ESEWJctmQsRr7QXh_:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/568856823a879e974f22fac60a159b94866638b4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L174)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please change this back to printing out `e.getMessage()` so the log isn't polluted with these kinds of exceptions:

```
2018-02-12 21:33:50,150 WARN [pool-5-thread-1] org.mitre.mpf.wfm.util.CallbackUtils - Error sending callback for job ids [197] to http://localhost:2000
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_144]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_144]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) [httpcore-nio-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) [httpcore-nio-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) [httpcore-nio-4.4.6.jar:4.4.6]
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194) [httpasyncclient-4.1.3.jar:4.1.3]
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.3.jar:4.1.3]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
```
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 182 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5BvfY-DyAkaBLPG59P:-L5ESHSyB77pjHyoDCE9:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/568856823a879e974f22fac60a159b94866638b4/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L182)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check grammar: "for callback for job"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/458)*

**Comment by jrobble** [comment]
For consistency, please update the log statements so that callback URI always precedes job ids. In some places we switch back and forth.

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 167 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5Ezc9rKWBZ1own07uQ:-L5Ezc9sdjIJVUTucj-D:b-tva55n) ([raw file](https://github.com/openmpf/openmpf/blob/50c8ea819a660c72f4f53f7ea759797eaf1b66cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L167)):*
> ```Java
> 			try {
> 				JsonCallbackBody jsonBody =new JsonCallbackBody(jobId, redis.getExternalId(jobId));
> 				new Thread(new CallbackThread(jsonCallbackURL, jsonCallbackMethod, jsonBody)).start();
> ```

Please log a success line here with all the info.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/458#-:-L5Ezr96dWhgy4DxsjQC:bs5h341)*

**Comment by brosenberg42** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 167 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5Ezc9rKWBZ1own07uQ:-L5F1_5rfWqfrAF7U9m9:b62c9cd) ([raw file](https://github.com/openmpf/openmpf/blob/50c8ea819a660c72f4f53f7ea759797eaf1b66cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L167)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please log a success line here with all the info.
</blockquote></details>

The callback happens on a separate thread. If I add logging right after this line, the log message will be printed before the callback gets sent. There is some logging in the CallbackThread.run() method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/458)*

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 167 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/458#-L5Ezc9rKWBZ1own07uQ:-L5FEDsjHv2eO4PEd1jU:b5piwdi) ([raw file](https://github.com/openmpf/openmpf/blob/50c8ea819a660c72f4f53f7ea759797eaf1b66cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L167)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The callback happens on a separate thread. If I add logging right after this line, the log message will be printed before the callback gets sent. There is some logging in the CallbackThread.run() method.
</blockquote></details>

You're right. I didn't see it before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/458)*

**Pull request merged**
