### PR TITLE
Feat/OIDC support

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1704

**Related PRs:**
- https://github.com/openmpf/openmpf.github.io/pull/170
- https://github.com/openmpf/openmpf-docker/pull/196

This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1703)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1703)* status: 0 of 30 files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/OidcAuthenticationManager.java` line 134 at r1](https://reviewable.io/reviews/openmpf/openmpf/1703#-Nd6CJ2362XyUbITm6KV:-Nd6CJ244YhrV22GTy1a:b-69z93b) ([raw file](https://github.com/openmpf/openmpf/blob/772bda46d1aa65249774ef13ddde63a2be2ddd13/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/OidcAuthenticationManager.java#L134)):*
> ```Java
>             return "The token's \"%s\" claim did not contain \"%s\" and the \"%s\" claim did not contain \"%s\"."
>                     .formatted(_userClaimName.orElseThrow(), _userClaimValue,
>                             _adminClaimName.orElseThrow(), _adminClaimName);
> ```

This should be:

```
                    .formatted(_userClaimName.orElseThrow(), _userClaimValue,
                            _adminClaimName.orElseThrow(), _adminClaimValue);

```

Notice the last `_adminClaimValue`.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/OidcAuthenticationManager.java` line 149 at r1](https://reviewable.io/reviews/openmpf/openmpf/1703#-Nd6AFO58frf7z0J64Zh:-Nd6AFO58frf7z0J64Zi:b-d8mw77) ([raw file](https://github.com/openmpf/openmpf/blob/772bda46d1aa65249774ef13ddde63a2be2ddd13/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/OidcAuthenticationManager.java#L149)):*
There's one situation this doesn't handle correctly. Consider:

```
      OIDC_ADMIN_CLAIM_NAME: openmpf-wfm-rolex
      OIDC_ADMIN_CLAIM_VALUE: ADMINX
      OIDC_USER_CLAIM_NAME: openmpf-wfm-role
      OIDC_USER_CLAIM_VALUE: USER
```

And consider that the token contains `openmpf-wfm-role=ADMIN`.

I get this error message in the UI:

> The token's "openmpf-wfm-role" claim did not contain "USER" or "ADMINX".

What's going is that the current logic doesn't handle the case where only one of the claim keys is present (admin or user), but doesn't have the right value.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 29 of 30 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1703)* status: all files reviewed, 4 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/OidcSecurityConfig.java` line 159 at r2](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjQBgSqCjl-_cr-Znqa:-NjQBgSqCjl-_cr-Znqb:b-y5oett) ([raw file](https://github.com/openmpf/openmpf/blob/a916b8c8698466f8a636a6e1386434ed420253b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/OidcSecurityConfig.java#L159)):*
> ```Java
>         return http
>             .authorizeHttpRequests(x ->
>                 x.antMatchers("/login/**", "/logout/**", "/resources/**", "/oidc-access-denied")
> ```

Why is "/logout/**" in here are not in this line in `LocalSecurityConfig.java`?

```
                x.antMatchers("/login/**", "/resources/**").permitAll()
```
___
*[`trunk/workflow-manager/src/main/webapp/resources/js/pipelines2/pipeline-directives.js` line 105 at r2](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjQCJUL8KfHt1oQxl7V:-NjQCJUM-n_wxr0DRS3A:b-hgpove) ([raw file](https://github.com/openmpf/openmpf/blob/a916b8c8698466f8a636a6e1386434ed420253b0/trunk/workflow-manager/src/main/webapp/resources/js/pipelines2/pipeline-directives.js#L105)):*
> ```JavaScript
> 
> 
>     module.directive('mpf-action', [
> ```

Good catch. The other directives (`mpfTask`,`taskSequence`, and `actionProperty`) are not defined with a hyphen here, but they do appear with a hyphen in the .html files. Also, not all of those start with `mpf`. Should we update them for consistency?
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/security/TestOidcAuthenticationManager.java` line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjQDbZI8Kra_UgO2bW6:-NjQDbZI8Kra_UgO2bW7:b-mjpjtq) ([raw file](https://github.com/openmpf/openmpf/blob/a916b8c8698466f8a636a6e1386434ed420253b0/trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/security/TestOidcAuthenticationManager.java#L1)):*
> ```Java
> package org.mitre.mpf.mvc.security;
> ```

Please add header comment blocks.

Otherwise, great tests :thumbsup: 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/CustomAccessDeniedHandler.java` line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjEO8110vYpIUXJoX2h:-NjEO8123UpHJZOmkUy4:b3icfzk) ([raw file](https://github.com/openmpf/openmpf/blob/e8125f08f1172e97c9858270ba1a3c520c83464d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/CustomAccessDeniedHandler.java#L50)):*
> ```Java
>             AccessDeniedException accessDeniedException) throws IOException, ServletException {
> 
>         if (!(accessDeniedException instanceof InvalidCsrfTokenException)) {
> ```

Was this a bug?

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1703)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjjmnvZ0eMB-yJ8dySZ:-Njjmnv_Bs4Jp0E525mJ:byl4ix3) (no related file):*
I got the `HTTP Error 401: : b''` message again. Some nitpicking about the formatting:

- What's up with the double colon and `b` character? Is the latter a formatting thing? Can we pull the message out of that and format it normally using one colon?

- If there is no message (like `b''`), can we just end the log message with `HTTP Error 401`?

___

**Comment by brosenberg42** [comment]
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/CustomAccessDeniedHandler.java` line 50 at r2](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjEO8110vYpIUXJoX2h:-NkHGkSP2z00DSpCIe9m:b6w8d6r) ([raw file](https://github.com/openmpf/openmpf/blob/e8125f08f1172e97c9858270ba1a3c520c83464d/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/security/CustomAccessDeniedHandler.java#L50)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Was this a bug?
</blockquote></details>

No, I just ran in to another type of csrf issue.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1703)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjjmnvZ0eMB-yJ8dySZ:-NkRDdep4H6f2huqY6uu:b6rvmzl) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I got the `HTTP Error 401: : b''` message again. Some nitpicking about the formatting:

- What's up with the double colon and `b` character? Is the latter a formatting thing? Can we pull the message out of that and format it normally using one colon?

- If there is no message (like `b''`), can we just end the log message with `HTTP Error 401`?
</blockquote></details>

The b means it is a bytes object. I improved the error message.

___
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/security/TestOidcAuthenticationManager.java` line 1 at r2](https://reviewable.io/reviews/openmpf/openmpf/1703#-NjQDbZI8Kra_UgO2bW6:-NkHEoGX7meChUzU9W7S:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/a916b8c8698466f8a636a6e1386434ed420253b0/trunk/workflow-manager/src/test/java/org/mitre/mpf/mvc/security/TestOidcAuthenticationManager.java#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add header comment blocks.

Otherwise, great tests :thumbsup:
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1703)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
