### PR TITLE
Fix artifact extraction resubmit issues

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFJISzm8Ry1FsB_9XdL:bu7430u) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
> ```Java
>             // If the priority should be changed during resubmission, make that change now.
>             if (priorityPolicy == PriorityPolicy.PROVIDED) {
>                 jsonJobRequest.setPriority(priority);
> ```

@jrobble, It looks like you made this change in commit fce4e8d9b835e2ce80ca1f2280cf027f1786bbc7. Then, it was accidentally reverted in  f90e420915bd0678e8cdce96334ab94791c37501.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFJn9Rs6sG53w4p54Ni:bbdzeti) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

@jrobble, It looks like you made this change in commit fce4e8d9b835e2ce80ca1f2280cf027f1786bbc7. Then, it was accidentally reverted in  f90e420915bd0678e8cdce96334ab94791c37501.
</blockquote></details>

Yeah, it is does look like that; however, I think we decided to revert back to the old way in order to add this:

```
// Attempt to recreate the pipeline because registered components; as well as algorithms, actions, tasks, and pipelines;
// may have changed since the first time the job was run.
JsonPipeline jsonPipeline = pipelineService.createJsonPipeline(jsonJobRequest.getPipeline().getName());
```

`createJsonPipeline` checks to ensure that all of the algorithms, actions, and tasks in the original job still exist. Let's say you have a MOG --> FACECV pipeline, remove the MOG component, and then try to resubmit it. That would be a problem.

Maybe the best thing to do here is to modify the code as follows:

```
        JobRequest oldJobRequest = jobRequestDao.findById(jobId);
        if (oldJobRequest == null) {
            throw new WfmProcessingException(String.format("A job with id %d is not known to the system.", priority));
        } else if (!oldJobRequest.getStatus().isTerminal()) {
            throw new WfmProcessingException(String.format("The job with id %d is in the non-terminal state of '%s'. Only jobs in a terminal state may be resubmitted.",
                    jobId, oldJobRequest.getStatus().name()));
        } else {
            JsonJobRequest oldJsonJobRequest = jsonUtils.deserialize(oldJobRequest.getInputObject(), JsonJobRequest.class);

            // Create a copy of this job's media in order to add it to the new instance we're about to create.
            final List<JsonMediaInputObject> originalMedia = new LinkedList<>();
            for (JsonMediaInputObject media : oldJsonJobRequest.getMedia()) {
                JsonMediaInputObject originalMedium = new JsonMediaInputObject(media.getMediaUri());
                originalMedium.getProperties().putAll(media.getProperties());
                originalMedia.add(originalMedium);
            }

            // Attempt to recreate the pipeline because registered components; as well as algorithms, actions, tasks, and pipelines;
            // may have changed since the first time the job was run.
            JsonPipeline jsonPipeline = pipelineService.createJsonPipeline(oldJsonJobRequest.getPipeline().getName());

            JsonJobRequest newJsonJobRequest = new JsonJobRequest(oldJsonJobRequest.getExternalId(), oldJsonJobRequest.isOutputObjectEnabled(),
                    jsonPipeline, priority, oldJsonJobRequest.getCallbackURL(), oldJsonJobRequest.getCallbackMethod());
            newJsonJobRequest.getMedia().addAll(originalMedia);
            newJsonJobRequest.getJobProperties().putAll(oldJsonJobRequest.getJobProperties());
            newJsonJobRequest.getAlgorithmProperties().putAll(oldJsonJobRequest.getAlgorithmProperties());

            JobRequest newJobRequest = initializeInternal(oldJobRequest, newJsonJobRequest);
            markupResultDao.deleteByJobId(jobId);

            redis.setJobStatus(jobId, BatchJobStatusType.IN_PROGRESS);
            AtmosphereController.broadcast(new JobStatusMessage(jobId, 0, BatchJobStatusType.IN_PROGRESS, null));

            return runInternal(newJobRequest, newJsonJobRequest, priority);
        }
```

I haven't tested that. Basically, the code is recreating the the `oldJsonJobRequest`, including all of it's fields.

Note that the current code is odd. The `pipelineService.createJsonPipeline` check is only done if the priority policy is provided. That check should be done even if it's not.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFJvx4_EqgRpFNJkdum:b-c5d83z) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Yeah, it is does look like that; however, I think we decided to revert back to the old way in order to add this:

```
// Attempt to recreate the pipeline because registered components; as well as algorithms, actions, tasks, and pipelines;
// may have changed since the first time the job was run.
JsonPipeline jsonPipeline = pipelineService.createJsonPipeline(jsonJobRequest.getPipeline().getName());
```

`createJsonPipeline` checks to ensure that all of the algorithms, actions, and tasks in the original job still exist. Let's say you have a MOG --> FACECV pipeline, remove the MOG component, and then try to resubmit it. That would be a problem.

Maybe the best thing to do here is to modify the code as follows:

```
        JobRequest oldJobRequest = jobRequestDao.findById(jobId);
        if (oldJobRequest == null) {
            throw new WfmProcessingException(String.format("A job with id %d is not known to the system.", priority));
        } else if (!oldJobRequest.getStatus().isTerminal()) {
            throw new WfmProcessingException(String.format("The job with id %d is in the non-terminal state of '%s'. Only jobs in a terminal state may be resubmitted.",
                    jobId, oldJobRequest.getStatus().name()));
        } else {
            JsonJobRequest oldJsonJobRequest = jsonUtils.deserialize(oldJobRequest.getInputObject(), JsonJobRequest.class);

            // Create a copy of this job's media in order to add it to the new instance we're about to create.
            final List<JsonMediaInputObject> originalMedia = new LinkedList<>();
            for (JsonMediaInputObject media : oldJsonJobRequest.getMedia()) {
                JsonMediaInputObject originalMedium = new JsonMediaInputObject(media.getMediaUri());
                originalMedium.getProperties().putAll(media.getProperties());
                originalMedia.add(originalMedium);
            }

            // Attempt to recreate the pipeline because registered components; as well as algorithms, actions, tasks, and pipelines;
            // may have changed since the first time the job was run.
            JsonPipeline jsonPipeline = pipelineService.createJsonPipeline(oldJsonJobRequest.getPipeline().getName());

            JsonJobRequest newJsonJobRequest = new JsonJobRequest(oldJsonJobRequest.getExternalId(), oldJsonJobRequest.isOutputObjectEnabled(),
                    jsonPipeline, priority, oldJsonJobRequest.getCallbackURL(), oldJsonJobRequest.getCallbackMethod());
            newJsonJobRequest.getMedia().addAll(originalMedia);
            newJsonJobRequest.getJobProperties().putAll(oldJsonJobRequest.getJobProperties());
            newJsonJobRequest.getAlgorithmProperties().putAll(oldJsonJobRequest.getAlgorithmProperties());

            JobRequest newJobRequest = initializeInternal(oldJobRequest, newJsonJobRequest);
            markupResultDao.deleteByJobId(jobId);

            redis.setJobStatus(jobId, BatchJobStatusType.IN_PROGRESS);
            AtmosphereController.broadcast(new JobStatusMessage(jobId, 0, BatchJobStatusType.IN_PROGRESS, null));

            return runInternal(newJobRequest, newJsonJobRequest, priority);
        }
```

I haven't tested that. Basically, the code is recreating the the `oldJsonJobRequest`, including all of it's fields.

Note that the current code is odd. The `pipelineService.createJsonPipeline` check is only done if the priority policy is provided. That check should be done even if it's not.
</blockquote></details>

To better future-proof this, it may be best to create a copy constructor for JsonJobRequest.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFKWuKp4fYVqPJEfaSe:bk0rasd) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

To better future-proof this, it may be best to create a copy constructor for JsonJobRequest.
</blockquote></details>

Alternatively, we may not want to create a new JsonJobRequest at all. Instead, we can  use the code in your PR but also make sure to invoke `pipelineService.createJsonPipeline` as a sanity check, throwing away the return value. That will throw InvalidPipelineObjectWfmProcessingException if something is wrong.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by brosenberg42** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFNFcB3BYT2Gl1Xi0Yv:b4e85sb) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
> createJsonPipeline checks to ensure that all of the algorithms, actions, and tasks in the original job still exist. Let's say you have a MOG --> FACECV pipeline, remove the MOG component, and then try to resubmit it. That would be a problem.

Couldn't we just check if the pipeline exists? If you remove the MOG plugin, the pipeline that used MOG will also be removed.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFNLzWZ6He9l5fWZEnU:b2y4hah) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

> createJsonPipeline checks to ensure that all of the algorithms, actions, and tasks in the original job still exist. Let's say you have a MOG --> FACECV pipeline, remove the MOG component, and then try to resubmit it. That would be a problem.

Couldn't we just check if the pipeline exists? If you remove the MOG plugin, the pipeline that used MOG will also be removed.
</blockquote></details>

It's possible, although unlikely, that someone could recreate a pipeline with the same name that has different stages from the pipeline used in the original job.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by brosenberg42** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFNMNZNE8LIBOBxDwqX:buumpt7) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It's possible, although unlikely, that someone could recreate a pipeline with the same name that has different stages from the pipeline used in the original job.
</blockquote></details>

The code in `pipelineService.createJsonPipeline` doesn't prevent that. It calls `PipelineDefinition pipelineDef = pipelines.get(pipelineName)` which just gets the current pipeline definition.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFNOA4E7GguEAkmcHYV:b-uc1gcy) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

The code in `pipelineService.createJsonPipeline` doesn't prevent that. It calls `PipelineDefinition pipelineDef = pipelines.get(pipelineName)` which just gets the current pipeline definition.
</blockquote></details>

Good point. Thinking about this more, I'm thinking that if a user resubmits a job he will probably want to use the current pipeline definition. Also, we don't store the system property values in mySQL, so those job properties that are set to the system property value may change between resubmissions.

Do you think that's how a user would want it to behave, or do you think a user would want to run the exact same pipeline with the exact same system property values?

I'm thinking that in most cases a user will resubmit a job right away, so the pipeline definitions and system properties are unlikely to change, but a user may decide to change those things and then resubmit, so we should use those new settings.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by brosenberg42** [comment]
Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFNRxvP4pltWDxCSKBT:b-xdcnit) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Good point. Thinking about this more, I'm thinking that if a user resubmits a job he will probably want to use the current pipeline definition. Also, we don't store the system property values in mySQL, so those job properties that are set to the system property value may change between resubmissions.

Do you think that's how a user would want it to behave, or do you think a user would want to run the exact same pipeline with the exact same system property values?

I'm thinking that in most cases a user will resubmit a job right away, so the pipeline definitions and system properties are unlikely to change, but a user may decide to change those things and then resubmit, so we should use those new settings.
</blockquote></details>

I was also thinking about whether or not a user would want the new pipeline. I think if a user deletes a pipeline and then creates another with the same name, they probably are correcting some issue in the original pipeline.

Also, as I was testing this, I was thinking about why is that button even there. If I run the exact same job, I should get the same output. I could see how this might be helpful to a component developer, but it is a little bit unclear how running the exact same job would benefit the user. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 306 at r1](https://reviewable.io/reviews/openmpf/openmpf/595#-LFJISzm8Ry1FsB_9XdK:-LFNYFGU7Wv2qEa7XIVZ:bvmwbn3) ([raw file](https://github.com/openmpf/openmpf/blob/709fa7affbc11b67991dbd44ddd44cde5eeb4144/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L306)):*
> I think if a user deletes a pipeline and then creates another with the same name, they probably are correcting some issue in the original pipeline.

I agree.

> If I run the exact same job, I should get the same output. I could see how this might be helpful to a component developer, but it is a little bit unclear how running the exact same job would benefit the user.

The job may have failed because of an ActiveMQ issue, or other system dependency, so they want to rerun it.

Otherwise, I think the value is being able to change settings and then resubmit the job, as you said.

If you agree, let's do what you said and just check if the pipeline exists before resubmitting it.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
Review status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 299 at r2](https://reviewable.io/reviews/openmpf/openmpf/595#-LFOUJtL5qAhNUzVgO-7:-LFOUJtMECO0G5NZ8GVH:buj4h0) ([raw file](https://github.com/openmpf/openmpf/blob/8f8accbbe7512c68c48f3d5544c991cc79e299f1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L299)):*
> ```Java
>             throw new WfmProcessingException(String.format("A job with id %d is not known to the system.", priority));
>         }
>         else if (!jobRequest.getStatus().isTerminal()) {
> ```

Let's remove the "else" parts of this conditional chain since throwing the exception will leave the method early.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 318 at r2](https://reviewable.io/reviews/openmpf/openmpf/595#-LFOdjjc2fOjEufytFFe:-LFOdjjgEAgmJRRZ5-ZU:b4udwi6) ([raw file](https://github.com/openmpf/openmpf/blob/8f8accbbe7512c68c48f3d5544c991cc79e299f1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L318)):*
> ```Java
>             jobRequest = initializeInternal(jobRequest, jsonJobRequest);
>             markupResultDao.deleteByJobId(jobId);
>             FileSystemUtils.deleteRecursively(propertiesUtil.getJobArtifactsDirectory(jobId));
> ```

We should delete the markup and output object folders too:

After first run (job 866):

```
[mpf@10 share]$ find . | grep 866
./artifacts/866
./artifacts/866/0
./artifacts/866/0/0
./artifacts/866/0/0/AAA.jpg
./markup/866
./markup/866/4
./markup/866/4/d7c4d5a9-4257-44b2-a9a0-89edb87e138f.png
./markup/866/0
./markup/866/0/409cb2c9-9e91-4e96-8cc6-a8250fb485ec.png
./output-objects/866
./output-objects/866/detection.json
```

Stopped service, tried to resubmit. Job stayed in progress. Noticed that some files were left behind:

```
[mpf@10 share]$ find . | grep 866
./markup/866
./markup/866/4
./markup/866/4/d7c4d5a9-4257-44b2-a9a0-89edb87e138f.png
./markup/866/0
./markup/866/0/409cb2c9-9e91-4e96-8cc6-a8250fb485ec.png
./output-objects/866
./output-objects/866/detection.json
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by brosenberg42** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @jrobble)

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 299 at r2](https://reviewable.io/reviews/openmpf/openmpf/595#-LFOUJtL5qAhNUzVgO-7:-LFSHtRl5BZvem8xyTCu:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8f8accbbe7512c68c48f3d5544c991cc79e299f1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L299)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's remove the "else" parts of this conditional chain since throwing the exception will leave the method early.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java, line 318 at r2](https://reviewable.io/reviews/openmpf/openmpf/595#-LFOdjjc2fOjEufytFFe:-LFSHxGm4WrMFQDQ67M-:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8f8accbbe7512c68c48f3d5544c991cc79e299f1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestBoImpl.java#L318)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We should delete the markup and output object folders too:

After first run (job 866):

```
[mpf@10 share]$ find . | grep 866
./artifacts/866
./artifacts/866/0
./artifacts/866/0/0
./artifacts/866/0/0/AAA.jpg
./markup/866
./markup/866/4
./markup/866/4/d7c4d5a9-4257-44b2-a9a0-89edb87e138f.png
./markup/866/0
./markup/866/0/409cb2c9-9e91-4e96-8cc6-a8250fb485ec.png
./output-objects/866
./output-objects/866/detection.json
```

Stopped service, tried to resubmit. Job stayed in progress. Noticed that some files were left behind:

```
[mpf@10 share]$ find . | grep 866
./markup/866
./markup/866/4
./markup/866/4/d7c4d5a9-4257-44b2-a9a0-89edb87e138f.png
./markup/866/0
./markup/866/0/409cb2c9-9e91-4e96-8cc6-a8250fb485ec.png
./output-objects/866
./output-objects/866/detection.json
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Comment by jrobble** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2, 3 of 3 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/595)*

**Pull request merged**
