### PR TITLE
Add user-specified segment boundaries

### PR DESCRIPTION
**Pull request by clnowacki**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1283

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1439)

### CODE REVIEW

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1439)* status: 0 of 36 files reviewed, 3 unresolved discussions (waiting on @clnowacki and @jrobble)

___
*[trunk/interop/src/main/java/org/mitre/mpf/interop/JsonMediaOutputObject.java, line 68 at r3](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3wc994NJagxY_0VOK:-Mr3wc994NJagxY_0VOL:bf83bvx) ([raw file](https://github.com/openmpf/openmpf/blob/e3c458da764e32f87a00a6d9c0f35c69ddb68374/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonMediaOutputObject.java#L68)):*
> ```Java
> 	public int getLength() { return length; }
> 
> 	private SortedSet<JsonMediaRange> frameRanges;
> ```

Added the ranges to the output object so people with only the output object know that the entire video was not processed.
___
*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/JobCreationMediaData.java, line 43 at r3](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3wxKt1ptGW6-IbQMl:-Mr3wxKt1ptGW6-IbQMm:b-f64l2n) ([raw file](https://github.com/openmpf/openmpf/blob/e3c458da764e32f87a00a6d9c0f35c69ddb68374/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/JobCreationMediaData.java#L43)):*
> ```Java
>     private Map<String, String> metadata = new HashMap<>();
> 
>     private List<JobCreationMediaRange> frameRanges = new ArrayList<>();
> ```

Moved from JobCreationRequest since it most likely doesn't make sense the apply the ranges to different pieces of media. Also discussed with Jeff changing the field name to make sure users don't confuse it with the segmenting that WFM does.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java, line 131 at r1](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3xUBlDqlK0QtDaRb7:-Mr3xUBlDqlK0QtDaRb8:b3w7raj) ([raw file](https://github.com/openmpf/openmpf/blob/478dbeb2204a122135fb96fc7c801731ddd7e6b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L131)):*
> ```Java
>                     " \nFor algorithmProperties, the key should be the algorithm name, and the value should be a" +
>                     " Map of String key-value pairs representing properties specific to the named algorithm." +
>                     " \n\n An optional list of segment boundaries, to be used instead of the automatic segmenting normally" +
> ```

This was little bit inaccurate since the automatic segmenting did get applied when the user provided ranges when they were long enough
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestServiceImpl.java, line 129 at r1](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3xjOW-3JIBY_1talZ:-Mr3xjOW-3JIBY_1tal_:bust19b) ([raw file](https://github.com/openmpf/openmpf/blob/478dbeb2204a122135fb96fc7c801731ddd7e6b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestServiceImpl.java#L129)):*
> ```Java
>         if ((!jobCreationRequest.getSegmentFrameBoundaries().isEmpty()) &&
>                 (!jobCreationRequest.getSegmentTimeBoundaries().isEmpty())) {
>             LOG.warn("Both frame and time segment boundaries were provided: using frame boundaries for this job");
> ```

Accepting both is a small change. The other option would be to reject the job since we wouldn't be doing what the user asked for.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java, line 248 at r1](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3y1j45aSaXmE9WHPr:-Mr3y1j45aSaXmE9WHPs:b7n34y9) ([raw file](https://github.com/openmpf/openmpf/blob/478dbeb2204a122135fb96fc7c801731ddd7e6b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/BatchJobImpl.java#L248)):*
> ```Java
>         _detectionProcessingErrors = new ArrayList<>(detectionProcessingErrors);
> 
>         if (!segmentFrameBoundaries.isEmpty()) {
> ```

Moved to MediaImpl
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfo.java, line 70 at r1](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3yMK-0BYKsRCW7QU4:-Mr3yMK-0BYKsRCW7QU5:b-dn2e1s) ([raw file](https://github.com/openmpf/openmpf/blob/478dbeb2204a122135fb96fc7c801731ddd7e6b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfo.java#L70)):*
> ```Java
>             }
>         },
>                 timeIdx -> {
> ```

I felt that named methods was more clear now that there were two lambdas.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfo.java, line 96 at r2](https://reviewable.io/reviews/openmpf/openmpf/1439#-MqQ6FIE5zbTZe4GbutR:-MqQ6FIE5zbTZe4GbutS:b-w1mfzp) ([raw file](https://github.com/openmpf/openmpf/blob/e713996eb7970480801a49a5b16ab12a8b3178ab/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfo.java#L96)):*
> ```Java
>     private static IntUnaryOperator getFrameUsingFps(double fps, int startTime) {
>         double framesPerMs = fps / 1000;
>         return timeIdx -> (int)Math.rint(framesPerMs * ((timeIdx < startTime) ? startTime : timeIdx - startTime));
> ```

I think we should always be rounding down here. Say that frame 5 is shown at 100ms and frame 6 is shown 150ms. At 149ms, frame 5 is still being shown. Also, when `timeIdx < startTime`, I think we should return frame 0. When `timeIdx < startTime`, that code ends up returning the frame for `2 * startTime`. I used this to verify:
```java
    @Test
    public void myTest() {
        double fps = 29.97;
        int startTime = 160;
        var times = new ArrayList<Integer>();
        for (int i = 0; i < 10; i++) {
            times.add(startTime + (int) (i * 1000/ fps));
        }

        for (int i = 0; i < times.size(); i++) {
            System.out.println(i + ": " + times.get(i));
        }
        System.out.println();

        System.out.println("2 * startTime: " + getFrameFromMs(2 * startTime, fps, startTime));
        System.out.println("0: " + getFrameFromMs(0, fps, startTime));
        System.out.println("100: " + getFrameFromMs(100, fps, startTime));
    }

    private static int getFrameFromMs(int timeMs, double fps, int startTime) {
        double framesPerMs = fps / 1000;
        return (int) (framesPerMs * ((timeMs < startTime) ? startTime : timeMs - startTime));
    }
```
It ouputs:
```
0: 160
1: 193
2: 226
3: 260
4: 293
5: 326
6: 360
7: 393
8: 426
9: 460

2 * startTime: 4
0: 4
100: 4
```
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/TimePair.java, line 45 at r3](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3yll2DC-k4jW7LHT9:-Mr3yll2DC-k4jW7LHTA:b-m353r0) ([raw file](https://github.com/openmpf/openmpf/blob/e3c458da764e32f87a00a6d9c0f35c69ddb68374/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/TimePair.java#L45)):*
> ```Java
> 
> 
> 	public TimePair(@JsonProperty("startInclusive") int startInclusive,
> ```

Since Java doesn't retain argument names in the compiled output, you need to add annotations to get the JSON deserializer to use a constuctor with arguments.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1439)* status: 0 of 36 files reviewed, 4 unresolved discussions (waiting on @clnowacki)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/Media.java, line 94 at r3](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr8SHEb8M2YSq2Yncji:-Mr8SHEcCpUvNZND_xE_:b-i24hsn) ([raw file](https://github.com/openmpf/openmpf/blob/e3c458da764e32f87a00a6d9c0f35c69ddb68374/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/Media.java#L94)):*
> ```Java
>     public FrameTimeInfo getFrameTimeInfo();
> 
>     public ImmutableSet<TimePair> getFrameRanges();
> ```

Let's rename `TimePair` to `MediaRange`. I know that historically it's always been called `TimePair`, but that's kind of a misnomer since it represents a range of frames, not time.

Now that we're using the same object to represent both time and frame ranges, we should name it something more generic. `MediaRange` aligns well with `JobCreationMediaRange`.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1439)* status: 0 of 38 files reviewed, 4 unresolved discussions (waiting on @clnowacki and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/Media.java, line 94 at r3](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr8SHEb8M2YSq2Yncji:-Mr8d6iHEg6yzSDE1XTr:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e3c458da764e32f87a00a6d9c0f35c69ddb68374/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/Media.java#L94)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's rename `TimePair` to `MediaRange`. I know that historically it's always been called `TimePair`, but that's kind of a misnomer since it represents a range of frames, not time.

Now that we're using the same object to represent both time and frame ranges, we should name it something more generic. `MediaRange` aligns well with `JobCreationMediaRange`.
</blockquote></details>

Done.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java, line 101 at r3](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr8mxUTCiHKXw1YQ3OW:-Mr8mxUTCiHKXw1YQ3OX:bb8kywe) ([raw file](https://github.com/openmpf/openmpf/blob/e3c458da764e32f87a00a6d9c0f35c69ddb68374/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L101)):*
> ```Java
>                 // If this is the first detection task in the pipeline, we should segment the entire media for detection.
>                 // If this is not the first detection task, we should build segments based off of the previous tasks's
>                 // tracks. Note that the TimePairs created for these Tracks use the non-feed-forward version of timeUtils.createTimePairsForTracks
> ```

Please do a full code search for "TimePair". It's still in some comments and in `createTimePairMessages` and `rangeToClosedTimePair`.

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 19 files at r1, 21 of 35 files at r3, 1 of 1 files at r4, 9 of 12 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1439)* status: 36 of 38 files reviewed, 3 unresolved discussions (waiting on @clnowacki)

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1439)* status: 36 of 38 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java, line 131 at r1](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3xUBlDqlK0QtDaRb7:-MrS9aaGAZy034vQQkV-:b32wtd) ([raw file](https://github.com/openmpf/openmpf/blob/478dbeb2204a122135fb96fc7c801731ddd7e6b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/JobController.java#L131)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This was little bit inaccurate since the automatic segmenting did get applied when the user provided ranges when they were long enough
</blockquote></details>

ok
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestServiceImpl.java, line 129 at r1](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3xjOW-3JIBY_1talZ:-MrS9gda0SnYazezFfqL:b32wtd) ([raw file](https://github.com/openmpf/openmpf/blob/478dbeb2204a122135fb96fc7c801731ddd7e6b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/JobRequestServiceImpl.java#L129)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Accepting both is a small change. The other option would be to reject the job since we wouldn't be doing what the user asked for.
</blockquote></details>

ok
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfo.java, line 70 at r1](https://reviewable.io/reviews/openmpf/openmpf/1439#-Mr3yMK-0BYKsRCW7QU4:-MrS9ia16j4c8aJfC2Nx:b-t77xc3) ([raw file](https://github.com/openmpf/openmpf/blob/478dbeb2204a122135fb96fc7c801731ddd7e6b0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/FrameTimeInfo.java#L70)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I felt that named methods was more clear now that there were two lambdas.
</blockquote></details>

agreed

**Review by brosenberg42 — APPROVED** [review]

**Review by clnowacki — COMMENTED** [review]
> Reviewed 1 of 35 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1439)* status: 37 of 38 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @clnowacki)

**Review by jrobble — APPROVED** [review]

**Pull request merged**
