### PR TITLE
Move old components to the openmpf-component-archive repo

### PR DESCRIPTION
**Pull request by clnowacki**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1350

**Related PRs**

- https://github.com/openmpf/openmpf-components/pull/272
- https://github.com/openmpf/openmpf-contrib-components/pull/74
- https://github.com/openmpf/openmpf-docker/pull/150
- https://github.com/openmpf/openmpf.github.io/pull/135

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1388)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1388)* status: all files reviewed, 11 unresolved discussions (waiting on @clnowacki)

___
*[trunk/jenkins/scripts/config_files/openmpf-open-source-package.json, line 2 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-MiboMhxA-V48keiZGQ3:-MiboMi44NWMgNv24ZJv:byi7r7e) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/jenkins/scripts/config_files/openmpf-open-source-package.json#L2)):*
> ```JSON
> {
>     "MPF_Components": [
> ```

Since we're no longer performing non-Docker Jenkins builds, it's time to retire the content of `/openmpf/trunk/jenkins`. There is one catch. This package file is mentioned in the Development Environment Guide.

I think we should move this file out of the openmpf repo and into `openmpf-build-tools/config-files/openmpf-example-package.json` (making sure to update the links in the Development Environment Guide). I don't really want to be in the business of updating it. As you can tell, it's already behind. Adding new entries is relatively straight-forward anyway. That's why I think we should rename it to "example".

This file is missing the other ACS components, NlpTextCorrection, KeywordTagging, and OcvYoloDetection. Since it will be just an example, I think we should slim it down. Minimally, I think we should keep everything we use in the system tests. Specifically, I think we should add OcvYoloDetection, remove AzureOcrTextDetection (since it requires an account to use anyway), and leave everything else as is.

Tagging @brosenberg42 in case he has an opinion.
___
*[trunk/mpf-rest-client/src/main/java/org/mitre/mpf/rest/client/Main.java, line 137 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-MidF6g68ZMceSeOuuE5:-MidF6g79Wzr6CDAjVQS:bjnus6j) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-rest-client/src/main/java/org/mitre/mpf/rest/client/Main.java#L137)):*
> ```Java
>         System.out.println("Number of available pipelines: " + pipelines.size());
>         System.out.println("Available pipelines:\n" +
>                 pipelines.stream().map(Pipeline::getName).collect(Collectors.joining("\n")) + "\n");
> ```

While testing this I realized that `openmpf/trunk/mpf-rest-client/README.md` is wrong. The following command is missing the `<host-prefix>` argument:

```
java -jar target/mpf-rest-client-*-jar-with-dependencies.jar <username> <raw-password> <face-image-file-path>
```

However, instead of adding that, I think we should just say:


```
# Run

Run this command in the same directory to print usages:

`java -jar target/mpf-rest-client-*-jar-with-dependencies.jar`
```
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic6t9R6nU3GYrfG3WL:-Mic6t9R6nU3GYrfG3WM:b-t69cco) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L61)):*
> ```Java
> import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
> 
> import java.io.IOException;
> ```

Never used.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 63 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic6uLm1ZhxewG5vi4K:-Mic6uLm1ZhxewG5vi4L:b-t69cco) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L63)):*
> ```Java
> import java.io.IOException;
> import java.net.URI;
> import java.net.URL;
> ```

Never used.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 103 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic6x6GDFUfO_xyZZF_:-Mic6x6GDFUfO_xyZZFa:b-t69cco) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L103)):*
> ```Java
> 
>     @Autowired
>     private ObjectMapper _objectMapper;
> ```

Never used.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 211 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic72cECH7lni-DdfQF:-Mic72cF9Ky2FRHN1sii:b-t69cco) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L211)):*
> ```Java
> 
> 
>     private static boolean tracksMatch(JsonTrackOutputObject expectedTrack,
> ```

Never used.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mid8Po-9SUC7Qb2T7aw:-Mid8Po-9SUC7Qb2T7ax:bid8jgt) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L61)):*
> ```Java
> /**
>  *
>  * NOTE: Please keep the tests in this class in alphabetical order.  While they will automatically run that way regardless
> ```

Let's remove this entire comment block.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 45 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mid8BBK2pZ9UOfllryr:-Mid8BBN8n0ATbB60pah:b15gbod) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L45)):*
> ```Java
> 
> /**
>  * NOTE: Please keep the tests in this class in alphabetical order.  While they will automatically run that way regardless
> ```

Let's remove this entire comment block.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 646 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic7vkO8ewmYJCpPc6c:-Mic7vkP27f8rImd2erC:bj0f2s2) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L646)):*
> ```Java
> 
> 
>     private static Map<String, String> getTinyYoloConfig(Map<String, String> otherProperties) {
> ```

Never used.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 1185 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic8TgO617VEMGXaxOI:-Mic8TgO617VEMGXaxOJ:b-aike3z) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L1185)):*
> ```Java
>     @Test(timeout = 15 * MINUTES)
>     public void runMultipleDetectionAlgorithmsVideo() throws Exception {
>         String multipleActionTaskName = "TEST MULTIPLE-ACTION DETECTION TASK 2";
> ```

Here you call it `TEST MULTIPLE-ACTION DETECTION`, but above you call it `TEST MULTIPLE-ACTION` (without `DETECTION`). Please use the same names for consistency (except for the 2 at the end of this one).
___
*[trunk/mpf-system-tests/src/test/resources/output/face/runFaceCombinedDetectImage.json, line 332 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic96J73xwvy6zbFgAl:-Mic96J73xwvy6zbFgAm:b17amcq) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/resources/output/face/runFaceCombinedDetectImage.json#L332)):*
> ```JSON
>   ],
>   "objectId": "1b3f09a1-ea4a-49f6-b46d-a1f54ff20ca6",
>   "pipeline": {
> ```

The order of fields in this file is off. Please add a version where they are in the proper order, for sanity. The POJOs are designed to generate the JSON so that the fields are in a specific order.

Same thing for the other JSON output files you added.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1388)* status: all files reviewed, 11 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/jenkins/scripts/config_files/openmpf-open-source-package.json, line 2 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-MiboMhxA-V48keiZGQ3:-Mj-wkbIAAP9JVvxL7-0:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/jenkins/scripts/config_files/openmpf-open-source-package.json#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Since we're no longer performing non-Docker Jenkins builds, it's time to retire the content of `/openmpf/trunk/jenkins`. There is one catch. This package file is mentioned in the Development Environment Guide.

I think we should move this file out of the openmpf repo and into `openmpf-build-tools/config-files/openmpf-example-package.json` (making sure to update the links in the Development Environment Guide). I don't really want to be in the business of updating it. As you can tell, it's already behind. Adding new entries is relatively straight-forward anyway. That's why I think we should rename it to "example".

This file is missing the other ACS components, NlpTextCorrection, KeywordTagging, and OcvYoloDetection. Since it will be just an example, I think we should slim it down. Minimally, I think we should keep everything we use in the system tests. Specifically, I think we should add OcvYoloDetection, remove AzureOcrTextDetection (since it requires an account to use anyway), and leave everything else as is.

Tagging @brosenberg42 in case he has an opinion.
</blockquote></details>

Done.
___
*[trunk/mpf-rest-client/src/main/java/org/mitre/mpf/rest/client/Main.java, line 137 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-MidF6g68ZMceSeOuuE5:-Mj-x7QQA7kgeBk2-q_2:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-rest-client/src/main/java/org/mitre/mpf/rest/client/Main.java#L137)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

While testing this I realized that `openmpf/trunk/mpf-rest-client/README.md` is wrong. The following command is missing the `<host-prefix>` argument:

```
java -jar target/mpf-rest-client-*-jar-with-dependencies.jar <username> <raw-password> <face-image-file-path>
```

However, instead of adding that, I think we should just say:


```
# Run

Run this command in the same directory to print usages:

`java -jar target/mpf-rest-client-*-jar-with-dependencies.jar`
```

</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic6t9R6nU3GYrfG3WL:-Mj15zAr7PQzWstlBTvb:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L61)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Never used.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 63 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic6uLm1ZhxewG5vi4K:-Mj16-GU2pHUqjORju5P:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L63)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Never used.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 103 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic6x6GDFUfO_xyZZF_:-Mj169OM1ismFaLkDqa5:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L103)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Never used.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java, line 211 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic72cECH7lni-DdfQF:-Mj16FzjD4_fjumOYzC-:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestStreamingJobStartStop.java#L211)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Never used.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 61 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mid8Po-9SUC7Qb2T7aw:-Mj16PdT4ZGnQcrjja3g:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L61)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's remove this entire comment block.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 45 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mid8BBK2pZ9UOfllryr:-Mj-yBRE-rbw03sWcwRm:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L45)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's remove this entire comment block.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 646 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic7vkO8ewmYJCpPc6c:-Mj-yVEY0KglrCHJScjw:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L646)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Never used.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 1185 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic8TgO617VEMGXaxOI:-Mj-yoeP039iULZZqMIV:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L1185)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Here you call it `TEST MULTIPLE-ACTION DETECTION`, but above you call it `TEST MULTIPLE-ACTION` (without `DETECTION`). Please use the same names for consistency (except for the 2 at the end of this one).
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/resources/output/face/runFaceCombinedDetectImage.json, line 332 at r2](https://reviewable.io/reviews/openmpf/openmpf/1388#-Mic96J73xwvy6zbFgAl:-Mj196Op7_5V58xpiV9R:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aa16af541111e8c1d59839dc1851e0c04492d1c9/trunk/mpf-system-tests/src/test/resources/output/face/runFaceCombinedDetectImage.json#L332)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The order of fields in this file is off. Please add a version where they are in the proper order, for sanity. The POJOs are designed to generate the JSON so that the fields are in a specific order.

Same thing for the other JSON output files you added.
</blockquote></details>

Done.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1388)* status: all files reviewed, 3 unresolved discussions (waiting on @clnowacki)

___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 1161 at r3](https://reviewable.io/reviews/openmpf/openmpf/1388#-MjB-zig5HczPLiyea1m:-MjB-zig5HczPLiyea1n:b-er89fo) ([raw file](https://github.com/openmpf/openmpf/blob/dbc4f1c0db7b77742fd1861bdcd106979715f70a/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L1161)):*
> ```Java
>         addTask(multipleActionTaskName, "OCV FACE DETECTION ACTION", "OCV TINY YOLO OBJECT DETECTION ACTION");
> 
>         String pipelineName = "TEST MULTIPLE-ACTION DETECTION PIPELINE 2";
> ```

Call this `TEST MULTIPLE-ACTION TASK PIPELINE 2` for consistency.
___
*[trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsImage.json, line 2 at r3](https://reviewable.io/reviews/openmpf/openmpf/1388#-MjB0EaJ5gN0tSmcFcaB:-MjB0EaK0DlfdTDjiIKe:bqzrjhd) ([raw file](https://github.com/openmpf/openmpf/blob/dbc4f1c0db7b77742fd1861bdcd106979715f70a/trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsImage.json#L2)):*
> ```JSON
> {
>   "algorithmProperties": null,
> ```

Please regenerate this so the fields are in the proper order.
___
*[trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsVideo.json, line 0 at r3](https://reviewable.io/reviews/openmpf/openmpf/1388#-MjB0L2uD7UMU12bCQAl:-MjB0L2uD7UMU12bCQAm:bqzrjhd) ([raw file](https://github.com/openmpf/openmpf/blob/dbc4f1c0db7b77742fd1861bdcd106979715f70a/trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsVideo.json#L0)):*
Please regenerate this so the fields are in the proper order.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1388)* status: 16 of 19 files reviewed, 3 unresolved discussions (waiting on @jrobble)

___
*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java, line 1161 at r3](https://reviewable.io/reviews/openmpf/openmpf/1388#-MjB-zig5HczPLiyea1m:-MjFLBxDC25yoKbtph-J:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/dbc4f1c0db7b77742fd1861bdcd106979715f70a/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemOnDiff.java#L1161)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Call this `TEST MULTIPLE-ACTION TASK PIPELINE 2` for consistency.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsVideo.json, line  at r3](https://reviewable.io/reviews/openmpf/openmpf/1388#-MjB0L2uD7UMU12bCQAl:-MjFKyJZDBoiVXO4gOWq:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/dbc4f1c0db7b77742fd1861bdcd106979715f70a/trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsVideo.json#L)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please regenerate this so the fields are in the proper order.
</blockquote></details>

Done.
___
*[trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsImage.json, line 2 at r3](https://reviewable.io/reviews/openmpf/openmpf/1388#-MjB0EaJ5gN0tSmcFcaB:-MjFMhtZ3P9WyT_BpNHi:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/dbc4f1c0db7b77742fd1861bdcd106979715f70a/trunk/mpf-system-tests/src/test/resources/output/face/runMultipleDetectionAlgorithmsImage.json#L2)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please regenerate this so the fields are in the proper order.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @clnowacki)

**Pull request merged**
