### PR TITLE
Add job warning when callback fails.

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1072)

### CODE REVIEW

**Comment by brosenberg42** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 216 at r1](https://reviewable.io/reviews/openmpf/openmpf/1072#-M5OLCsMEk5FENeTtwGP:-M5RI8qo5_IKDsWYVoxE:b-ulbvsg) ([raw file](https://github.com/openmpf/openmpf/blob/740235214d7f60cdeb6ced8aa2d0282ac97201c1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L216)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, related to https://github.com/openmpf/openmpf/issues/1080, I noticed that in the job status UI the job status was BUILDING_OUTPUT_OBJECT at 99% while waiting to complete the callback. When I refreshed that web page the status changed to COMPLETE, and then when the callback failed it changed to COMPLETE_WITH_WARNINGS.
</blockquote></details>

There is nothing I can do about that. The job has to be complete before the callback is sent.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 216 at r1](https://reviewable.io/reviews/openmpf/openmpf/1072#-M5OLCsMEk5FENeTtwGP:-M5S13kR9pr87IzgdWA2:b-8uegpj) ([raw file](https://github.com/openmpf/openmpf/blob/740235214d7f60cdeb6ced8aa2d0282ac97201c1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L216)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

There is nothing I can do about that. The job has to be complete before the callback is sent.
</blockquote></details>

Consider marking the job 100% COMPLETE (or whatever the final job status is) in the `job` object we use to make the async callback, but set the status to 99% SENDING_CALLBACK in `inProgressBatchJobs` and the DB. When the async process completes, then set the final 100% job status in those places, based on the success of the callback.

**Comment by brosenberg42** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 216 at r1](https://reviewable.io/reviews/openmpf/openmpf/1072#-M5OLCsMEk5FENeTtwGP:-M5S93V3AKu9-2ghw10x:b-a86sia) ([raw file](https://github.com/openmpf/openmpf/blob/740235214d7f60cdeb6ced8aa2d0282ac97201c1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L216)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Consider marking the job 100% COMPLETE (or whatever the final job status is) in the `job` object we use to make the async callback, but set the status to 99% SENDING_CALLBACK in `inProgressBatchJobs` and the DB. When the async process completes, then set the final 100% job status in those places, based on the success of the callback.
</blockquote></details>

We need to assume that the instant we send the callback, the remote server is going to attempt to get more information about the job. When they do this, WFM needs to say it is complete.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 216 at r1](https://reviewable.io/reviews/openmpf/openmpf/1072#-M5OLCsMEk5FENeTtwGP:-M5SDvQHBQTntWKuzgPY:b-f4rn7) ([raw file](https://github.com/openmpf/openmpf/blob/740235214d7f60cdeb6ced8aa2d0282ac97201c1/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L216)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We need to assume that the instant we send the callback, the remote server is going to attempt to get more information about the job. When they do this, WFM needs to say it is complete.
</blockquote></details>

Good point. I will mention this to the end users to see if they have any issue with it.

**Pull request merged**
