### PR TITLE
Feat/angular jobs2

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1601
- https://github.com/openmpf/openmpf/issues/1611

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1627)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 434 of 437 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1627)* status: all files reviewed, 6 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1627#-NPx1v8U7w-GGWMjbu_M:-NPx1v8U7w-GGWMjbu_N:b-1079bd) (no related file):*
The `{}` button on the Job Status page shows a blank page. It's not displaying the JSON.

The fix is how I added "lib" to this line in `output_object.jsp`:

```
<script src="../resources/js/lib/jquery-1.11.0.min.js"></script>
```

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1627#-NQ2xrIf6yPmtFIXzeOm:-NQ2xrIf6yPmtFIXzeOn:b-5gh5pt) (no related file):*
The "TiesDb" and "Callback" `IN PROGRESS` column spinners continue to spin even when the job is complete. I need to refresh the page for the table cells to show the expected "ERROR" button.

This happens in FF and Chrome when I have broadcasts enabled. It does not happen when I have polling enabled since the page refreshes on the next poll.

___
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/Application.java` line 124 at r2](https://reviewable.io/reviews/openmpf/openmpf/1627#-NJgZ9H53ydw4sCn_OfD:-NJgZ9H53ydw4sCn_OfE:bs8grxo) ([raw file](https://github.com/openmpf/openmpf/blob/a6086c18de875e885e79d561789078f5d508e065/trunk/workflow-manager/src/main/java/org/mitre/mpf/Application.java#L124)):*
> ```Java
> 
>         servlet.addInitParameter(
>             "org.atmosphere.interceptor.HeartbeatInterceptor.heartbeatFrequencyInSeconds", "60");
> ```

What impact does this have? Is this just to keep the atmosphere web socket open?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDaoImpl.java` line 98 at r3](https://reviewable.io/reviews/openmpf/openmpf/1627#-NQ84ZvE9b2jwwFUcgZu:-NQ84ZvFCmXZ_wzYBGXq:byjttv) ([raw file](https://github.com/openmpf/openmpf/blob/f070882db2e127b4d1897b4f5b0d6d08e106ab16/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/hibernate/HibernateJobRequestDaoImpl.java#L98)):*
> ```Java
>     @Override
>     public void newJobCreated() {
>         _jobCount.incrementAndGet();
> ```

I noticed we're not doing `_startupCountFuture.join();` here. Is that because the `countAll` thread was already kicked off such that any new jobs added to the DB since then won't be included in that initial query results?
___
*[`trunk/workflow-manager/src/main/webapp/resources/ui-plugins/datatables-plugins/datatables-responsive/Readme.md` line 0 at r3](https://reviewable.io/reviews/openmpf/openmpf/1627#-NPsybr3Eb5lCKKvyIo8:-NPsybr3Eb5lCKKvyIo9:b7564ya) ([raw file](https://github.com/openmpf/openmpf/blob/8f51d1bfb82b84d1989f59b009ce39c5607e484e/trunk/workflow-manager/src/main/webapp/resources/ui-plugins/datatables-plugins/datatables-responsive/Readme.md#L0)):*
Is this file supposed to be empty?
___
*[`trunk/workflow-manager/src/main/webapp/resources/layouts/directives/navbar.html` line 46 at r3](https://reviewable.io/reviews/openmpf/openmpf/1627#-NQ2LeMq7Cwp-quAop8r:-NQ2LeMq7Cwp-quAop8s:b-jotnlk) ([raw file](https://github.com/openmpf/openmpf/blob/f070882db2e127b4d1897b4f5b0d6d08e106ab16/trunk/workflow-manager/src/main/webapp/resources/layouts/directives/navbar.html#L46)):*
> ```HTML
>                     <a class="dropdown-toggle active" id="jobs_dropdown" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Jobs<span class="caret"></span></a>
>                     <ul class="dropdown-menu">
>                         <li><a ui-sref="/jobs" id="menu_jobs" title="View status of queued jobs">Status</a></li>
> ```

I had to change this to `ui-sref="jobs"` so that I could use the "Job" --> "Status" link in the top menu bar.

**Comment by jrobble** [comment]
*[`trunk/workflow-manager/src/main/webapp/resources/js/directives.js` line 368 at r3](https://reviewable.io/reviews/openmpf/openmpf/1627#-NQBusJ2-Y_0PGqTHwva:-NQBusJ2-Y_0PGqTHwvb:b-oruv9) ([raw file](https://github.com/openmpf/openmpf/blob/f070882db2e127b4d1897b4f5b0d6d08e106ab16/trunk/workflow-manager/src/main/webapp/resources/js/directives.js#L368)):*
> ```JavaScript
> 
>             // uib-pagination does not disable links with ellipses.
>             const disableEllipses = () => {
> ```

We discussed changing the "Next" text in the rightmost pagination button to "More" when doing a search. One way to do that would to modify the link text inside the `pagination-next` element. Another easier way may be to set the `uib-pagination` `next-text` setting.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1627)* status: 433 of 438 files reviewed, 7 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1627#-NPx1v8U7w-GGWMjbu_M:-NQjT6obEh_X5aa1Yd58:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The `{}` button on the Job Status page shows a blank page. It's not displaying the JSON.

The fix is how I added "lib" to this line in `output_object.jsp`:

```
<script src="../resources/js/lib/jquery-1.11.0.min.js"></script>
```
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1627#-NQ2xrIf6yPmtFIXzeOm:-NQjUi6gB-GClbfztNiR:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The "TiesDb" and "Callback" `IN PROGRESS` column spinners continue to spin even when the job is complete. I need to refresh the page for the table cells to show the expected "ERROR" button.

This happens in FF and Chrome when I have broadcasts enabled. It does not happen when I have polling enabled since the page refreshes on the next poll.
</blockquote></details>

Done.

___
___
*[`trunk/workflow-manager/src/main/webapp/resources/js/directives.js` line 368 at r3](https://reviewable.io/reviews/openmpf/openmpf/1627#-NQBusJ2-Y_0PGqTHwva:-NQjXddu5HQq1dX-_qXs:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f070882db2e127b4d1897b4f5b0d6d08e106ab16/trunk/workflow-manager/src/main/webapp/resources/js/directives.js#L368)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

We discussed changing the "Next" text in the rightmost pagination button to "More" when doing a search. One way to do that would to modify the link text inside the `pagination-next` element. Another easier way may be to set the `uib-pagination` `next-text` setting.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/webapp/resources/layouts/directives/navbar.html` line 46 at r3](https://reviewable.io/reviews/openmpf/openmpf/1627#-NQ2LeMq7Cwp-quAop8r:-NQjV2J96T1BdpnHRisE:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f070882db2e127b4d1897b4f5b0d6d08e106ab16/trunk/workflow-manager/src/main/webapp/resources/layouts/directives/navbar.html#L46)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I had to change this to `ui-sref="jobs"` so that I could use the "Job" --> "Status" link in the top menu bar. 
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 5 of 5 files at r4, 5 of 7 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1627)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
