### PR TITLE
Update WFM to label stationary vs. non-stationary video tracks (#1258).

### PR DESCRIPTION
**Pull request by hhuangMITRE**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1263)

### CODE REVIEW

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1263)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/stationarytracklabeling/StationaryTrackLabelingProcessor.java, line 126 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVHp-ao0BWWH6WQnZIZ:-MVHp-ao0BWWH6WQnZI_:b-ptou9) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/stationarytracklabeling/StationaryTrackLabelingProcessor.java#L126)):*
> ```Java
>                     _log.warn(String.format("Dropping %d stationary tracks for job id %s.",
>                             trackSizeDiff, job.getId()));
>                     _inProgressBatchJobs.addWarning(
> ```

We don't want this job to end in `COMPLETE_WITH_WARNINGS` when we do something the user requested. We should just log that we are dropping tracks.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/stationarytracklabeling/StationaryTrackLabelingProcessor.java, line 146 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVHoVKl9LHiBfvBBO0U:-MVHoVKm0XTTbgjB73lM:bu3o5e3) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/stationarytracklabeling/StationaryTrackLabelingProcessor.java#L146)):*
> ```Java
>         for (Track track : tracks) {
>             Track newTrack = processTrack(jobId, mediaId, iouThreshold, minMovingObjects, track);
>             if (newTrack.getTrackProperties().get("IS_STATIONARY_TRACK") == "TRUE" && dropStationaryTracks) {
> ```

In Java `==` is for reference/pointer equality, this should be using `.equals()`. `==` happens to work in this case because Java interns short strings
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java, line 102 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVI-qc-7CviAmZSCa85:-MVI-qc-7CviAmZSCa86:b-gyr6ul) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java#L102)):*
> ```Java
> 					.completionPredicate(new SplitCompletedPredicate(true)) // We need to forward the body of the last message on to the next processor.
> 					.removeHeader(MpfHeaders.SPLIT_COMPLETED)
> 					.process(StationaryTrackLabelingProcessor.REF) // Detect and flag stationary tracks. Remove stationary tracks if requested by job.
> ```

We should do track merging first.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 6 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java, line 102 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVI-qc-7CviAmZSCa85:-MVI62WfC56_cLkQMlpJ:b6vxt14) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java#L102)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

We should do track merging first.
</blockquote></details>

Got it, thanks!

@jrobble I recall that we had discussed placing stationary track labeling before track merging. I assume we've decided to change it to labeling of merged tracks.

**Comment by brosenberg42** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java, line 102 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVI-qc-7CviAmZSCa85:-MVIE8Jh8Ln6rMGv1dwX:bwb5bv2) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java#L102)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

Got it, thanks!

@jrobble I recall that we had discussed placing stationary track labeling before track merging. I assume we've decided to change it to labeling of merged tracks.
</blockquote></details>

Track merging will affect the size of the average bounding box and the number of detections labeled as moving. This will cause `MOVING_TRACK_MAX_IOU` and `MOVING_TRACK_MIN_DETECTIONS` to not work as described.

**Review by hhuangMITRE — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1263)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java, line 102 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVI-qc-7CviAmZSCa85:-MVIGBVv14VlcF5P_sJr:bz8xn7w) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java#L102)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Track merging will affect the size of the average bounding box and the number of detections labeled as moving. This will cause `MOVING_TRACK_MAX_IOU` and `MOVING_TRACK_MIN_DETECTIONS` to not work as described.
</blockquote></details>

I see, if labeling happens before merging, a merged track may show movement, but individual pre-merged tracks could be independently classified as stationary. Also users would also notice that the IOU/moving track calculations would be incorrect for merged tracks as well.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java, line 102 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVI-qc-7CviAmZSCa85:-MVIIkuBD1X8XQdLtTgd:b-pqmckx) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java#L102)):*
<details><summary><i>Previously, hhuangMITRE (Howard W Huang) wrote…</i></summary><blockquote>

I see, if labeling happens before merging, a merged track may show movement, but individual pre-merged tracks could be independently classified as stationary. Also users would also notice that the IOU/moving track calculations would be incorrect for merged tracks as well. 
</blockquote></details>

@hhuangmitre , I've discussed this with Brian, and thinking about it more, I agree with doing track merging before detecting motion. I was originally trying to account for situations arising from the inherent inaccuracy of our track merging approach, but that's a separate concern that should be addressed independently.

**Comment by hhuangMITRE** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java, line 102 at r1](https://reviewable.io/reviews/openmpf/openmpf/1263#-MVI-qc-7CviAmZSCa85:-MVILlCw0Nq1Xc6BXH4F:b-nu6lvn) ([raw file](https://github.com/openmpf/openmpf/blob/2038eb80a515e19fdd9acfa9855ac9275d10ee70/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DetectionResponseRouteBuilder.java#L102)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

@hhuangmitre , I've discussed this with Brian, and thinking about it more, I agree with doing track merging before detecting motion. I was originally trying to account for situations arising from the inherent inaccuracy of our track merging approach, but that's a separate concern that should be addressed independently.
</blockquote></details>

@jrobble Got it, thanks Jeff!

**Pull request merged**
