### PR TITLE
Limited when and where we set the ld path.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/569)

### CODE REVIEW

**Comment by jrobble** [comment]
Currently fails due to:

```
Caused by: java.lang.UnsatisfiedLinkError: /opt/mpf/lib/libmpfopencvjni.so: libopencv_dnn.so.3.3: cannot open shared object file: No such file or directory
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[na:1.8.0_144]
```

From this [post](https://wrapper.tanukisoftware.com/doc/english/howto-system-library-path.html):

> Java loads native libraries (JNI) by searching the path defined with the java.library.path. system property. [...] This is sufficient for most JNI libraries, however some libraries themselves make use of other dynamically linked libraries. Java will locate the initial JNI library using the Java library path, but the secondary libraries are loaded using the default mechanism for the platform.

We are trying to avoid setting LD_LIBRARY_PATH.

**Comment by jrobble** [comment]
The way to solve this problem is to export LD_LIBRARY_PATH in setenv.sh:

```
[mpf@somehost-7-mpfd7 bin]$ cat /opt/apache-tomcat/bin/setenv.sh 
export LD_LIBRARY_PATH=/opt/mpf/lib
export CATALINA_OPTS="-server -Xms256m -XX:PermSize=512m -XX:MaxPermSize=512m -Djgroups.tcp.port=7800 -Djava.library.path=/opt/mpf/lib -Djgroups.tcpping.initial_hosts='$ALL_MPF_NODES' -Dtransport.guarantee='NONE' -Dweb.rest.protocol='http'"
```

**Comment by jrobble** [comment]
After implementing that approach, I get:

```
[mpf@somehost-7-mpfd7 bin]$ ldd amq_detection_component 
	linux-vdso.so.1 =>  (0x00007ffd1e3d4000)
	liblog4cxx.so.10 => /lib64/liblog4cxx.so.10 (0x00007f035bf12000)
	libactivemq-cpp.so.19 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f035bcf6000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f035baf2000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f035b8ed000)
	libQtCore.so.4 => not found
	libprotobuf.so.8 => not found
	libpython2.7.so.1.0 => /lib64/libpython2.7.so.1.0 (0x00007f035b521000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f035b21a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f035af18000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f035ad02000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f035a935000)
	libaprutil-1.so.0 => /lib64/libaprutil-1.so.0 (0x00007f035a70c000)
	libldap_r-2.4.so.2 => /lib64/libldap_r-2.4.so.2 (0x00007f035a4ad000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f035a29e000)
	libexpat.so.1 => /lib64/libexpat.so.1 (0x00007f035a074000)
	libdb-5.3.so => /lib64/libdb-5.3.so (0x00007f0359cb5000)
	libapr-1.so.0 => /lib64/libapr-1.so.0 (0x00007f0359a86000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f035c302000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f0359883000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f035964c000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f0359433000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f0359216000)
	libssl.so.10 => /lib64/libssl.so.10 (0x00007f0358fa4000)
	libcrypto.so.10 => /lib64/libcrypto.so.10 (0x00007f0358b43000)
	libssl3.so => /lib64/libssl3.so (0x00007f03588f1000)
	libsmime3.so => /lib64/libsmime3.so (0x00007f03586ca000)
	libnss3.so => /lib64/libnss3.so (0x00007f035839d000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007f035816e000)
	libplds4.so => /lib64/libplds4.so (0x00007f0357f6a000)
	libplc4.so => /lib64/libplc4.so (0x00007f0357d65000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f0357b27000)
	libfreebl3.so => /lib64/libfreebl3.so (0x00007f0357924000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f03576d7000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f03573ef000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f03571bc000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f0356fb8000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f0356daa000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f0356b94000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f035698c000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f0356788000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f0356561000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f03562ff000)
```

The C++ component executor depends on some libs stored in /opt/mpf/libs.

**Comment by jrobble** [comment]
Successfully deployed this on a clean set of VMs.

---

Review status: 0 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/569#-:-LEWOiHxBf0Hj1zlPpxu:b-sifxb2)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r1, 1 of 1 files at r2, 5 of 5 files at r4.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/569#-:-LEjeSah9VrIUwwzlnL1:bnfp4nl)*

**Pull request merged**
