### PR TITLE
Feature/merge task output

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226)

### CODE REVIEW

**Review by brosenberg42 — APPROVED** [review]
Do you think "NO TRACKS", "TRACKS SUPPRESSED", and "TRACKS MERGED" should show up first in the JSON output? I was thinking we could add a custom comparator here: https://github.com/openmpf/openmpf/blob/feature/merge-task-output/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonMediaOutputObject.java#L111 

I was doing some testing with this (obviously needs better naming):
```java
private static class MyComp implements Comparator<String>  {
    private static final Set<String> _special = new HashSet<>(Arrays.asList(
            JsonActionOutputObject.NO_TRACKS_TYPE,
            JsonActionOutputObject.TRACKS_MERGED_TYPE,
            JsonActionOutputObject.TRACKS_SUPPRESSED_TYPE));

    @Override
    public int compare(String left, String right) {
        boolean leftIsSpecial = _special.contains(left);
        boolean rightIsSpecial = _special.contains(right);
        if (leftIsSpecial == rightIsSpecial) {
            return stringCompare().compare(left, right);
        }
        return leftIsSpecial
                ? -1
                : 1;
    }
}
```

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226#-:-MO8Q2hi8Ko-3H1ln6Zr:b-rerer3)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 417 at r1](https://reviewable.io/reviews/openmpf/openmpf/1226#-MO8REx73vpfZE9VGJbK:-MO8REx73vpfZE9VGJbL:bl5bzrn) ([raw file](https://github.com/openmpf/openmpf/blob/ee3bf40efc68f80a9e40a2744694a7394e5e9edf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L417)):*
> ```Java
> 
>                             String type = tasksToMerge.contains(taskIndex) ? prevUnmergedTaskType :
>                                     jsonTrackOutputObject.getType();
> ```

You may want to add a comment here explaining that `tasksToMerge` will never contain task 0 so the null initial value of `prevUnmergedTaskType` is never used.

**Review by jrobble — COMMENTED** [review]
I added this. It's more convenient to see these types up front then have to scroll through long JSON.

> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226#-:-MOAE3TS8QPYBCRLq7PF:brcr4jd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Comment by jrobble** [comment]
I decided to address https://github.com/openmpf/openmpf/issues/1220 in this PR since the algorithm name is affected by task merging.

**Review by brosenberg42 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, 28 of 28 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 423 at r3](https://reviewable.io/reviews/openmpf/openmpf/1226#-MOC8kVf5w8Veks3ym41:-MOC8kVf5w8Veks3ym42:b-weo5r4) ([raw file](https://github.com/openmpf/openmpf/blob/d121f0cda20213459d442c8e299799a59eac97be/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L423)):*
> ```Java
>                             // tasksToMerge will never contain task 0, so the initial null values of
>                             // prevUnmergedTaskType and prevUnmergedAlgorithm are never used.
>                             String type = tasksToMerge.contains(taskIndex) ? prevUnmergedTaskType :
> ```

This `type` never gets applied to JsonTrackOutputObject.getType(). I ran a job where OUTPUT_MERGE_WITH_PREVIOUS_TASK was true for all tasks, I saw this:
```
            "TEXT REGION": [
               {
                  "source": "+#EAST TEXT DETECTION ACTION#TESSERACT OCR TEXT DETECTION (WITH FF REGION) ACTION#AZURE TRANSLATION (WITH FF REGION) ACTION#KEYWORD TAGGING (WITH FF REGION) ACTION",
                  "algorithm": "EAST",
                  "tracks": [
                     {
                        "id": "63d172a3e4530e24a972abecfd7e79d8088693ec32c05285d51fb574c6546011",
                        "startOffsetFrame": 0,
                        "stopOffsetFrame": 1,
                        "startOffsetTime": 0,
                        "stopOffsetTime": 0,
                        "type": "TEXT",
                        "source": "+#EAST TEXT DETECTION ACTION#TESSERACT OCR TEXT DETECTION (WITH FF REGION) ACTION#AZURE TRANSLATION (WITH FF REGION) ACTION#KEYWORD TAGGING (WITH FF REGION) ACTION",
                        "confidence": 95,
```
The key for this group is `TEXT REGION`, but the track has `"type": "TEXT"`. When I run a job with just EAST, the type in the tracks is `TEXT REGION`

**Review by jrobble — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226)* status: 32 of 36 files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java, line 423 at r3](https://reviewable.io/reviews/openmpf/openmpf/1226#-MOC8kVf5w8Veks3ym41:-MOIALju0mYcJucyfKK8:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/d121f0cda20213459d442c8e299799a59eac97be/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/JobCompleteProcessorImpl.java#L423)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This `type` never gets applied to JsonTrackOutputObject.getType(). I ran a job where OUTPUT_MERGE_WITH_PREVIOUS_TASK was true for all tasks, I saw this:
```
            "TEXT REGION": [
               {
                  "source": "+#EAST TEXT DETECTION ACTION#TESSERACT OCR TEXT DETECTION (WITH FF REGION) ACTION#AZURE TRANSLATION (WITH FF REGION) ACTION#KEYWORD TAGGING (WITH FF REGION) ACTION",
                  "algorithm": "EAST",
                  "tracks": [
                     {
                        "id": "63d172a3e4530e24a972abecfd7e79d8088693ec32c05285d51fb574c6546011",
                        "startOffsetFrame": 0,
                        "stopOffsetFrame": 1,
                        "startOffsetTime": 0,
                        "stopOffsetTime": 0,
                        "type": "TEXT",
                        "source": "+#EAST TEXT DETECTION ACTION#TESSERACT OCR TEXT DETECTION (WITH FF REGION) ACTION#AZURE TRANSLATION (WITH FF REGION) ACTION#KEYWORD TAGGING (WITH FF REGION) ACTION",
                        "confidence": 95,
```
The key for this group is `TEXT REGION`, but the track has `"type": "TEXT"`. When I run a job with just EAST, the type in the tracks is `TEXT REGION`
</blockquote></details>

Done.

**Review by brosenberg42 — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226)* status: 35 of 36 files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226)* status: 35 of 36 files reviewed, all discussions resolved (waiting on @brosenberg42)

**Review by brosenberg42 — APPROVED** [review]

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jrobble — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1226)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
