### PR TITLE
Now copies over all OpenCV 3.3 libs

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/256)

### CODE REVIEW

**Comment by jrobble** [comment]
@dpierce17, once this lands you can start deploying new Jenkins packages created from the develop branch.

**Comment by brosenberg42** [comment]
I get the following errors catalina.out when the markup model appears:
```
(process:13506): GLib-GObject-WARNING **: cannot register existing type 'GVfs'

(process:13506): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(process:13506): GLib-GObject-CRITICAL **: g_type_register_dynamic: assertion 'parent_type > 0' failed

(process:13506): GLib-GObject-WARNING **: cannot register existing type 'GVolumeMonitor'

(process:13506): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(process:13506): GLib-GObject-CRITICAL **: g_type_register_dynamic: assertion 'parent_type > 0' failed

(process:13506): GLib-GIO-WARNING **: Tried to implement non-registered extension point gio-volume-monitor

(process:13506): GLib-GIO-WARNING **: Tried to implement non-registered extension point gio-vfs
```

CopySharedLibDependencies.cmake filters out the libraries in "Table 2-1. LSB Core Module Library Names" from http://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Common/LSB-Common/requirements.html#TBL-CORELIB .
Maybe we should also add the libraries listed in "Table 2-3. LSB Desktop Module Library Names"

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/256#-:-Kv82vX3aKDzWfNlz6vc:bc29nxa)*

**Comment by jrobble** [comment]
I didn't see this issue on the deployment VM, and it's not happening on my dev VM. I'm now installing the deployment package on a clean local CentOS VM after running "sudo yum update" to see if it's an issue with using more recent system dependencies. If not, I say we land this but keep a lookout for issues since the functionality continued to work. I'll let you know how my test turns out.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/256#-:-Kv8hpSb1XVqi6dezFFG:b-vpnh7h)*

**Comment by jrobble** [comment]
I don't see these issues on a deployment VM after doing "sudo yum update". However, after speaking with you, I believe it is a good idea to omit the "Table 2-3. LSB Desktop Module Library Names" from the copied libs. They are just bloat, and could potentially cause issues if copied over to a minimal VM without a UI.

---

Review status: 0 of 4 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/256#-:-KvAJ89W8qVc_LbSZYFa:b-c88t1s)*

**Comment by jrobble** [comment]
I landed this to unblock @dpierce17. I will omit the "Table 2-3. LSB Desktop Module Library Names" from the copied libs in a separate PR.

**Pull request merged**
