### PR TITLE
Ubuntu transition

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1374
- https://github.com/openmpf/openmpf/issues/1105

**Related PRs:**
- https://github.com/openmpf/openmpf/pull/1447
- https://github.com/openmpf/openmpf-docker/pull/157
- https://github.com/openmpf/openmpf-components/pull/287
- https://github.com/openmpf/openmpf-contrib-components/pull/76
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/108
- https://github.com/openmpf/openmpf-java-component-sdk/pull/56

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)

### CODE REVIEW

**Review by jrobble — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: 0 of 97 files reviewed, all discussions resolved (waiting on @brosenberg42)

**Comment by jrobble** [comment]
___
*[pom.xml, line 154 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRKt5P3uAUgG7nzSEd:-MuRKt5P3uAUgG7nzSEe:b-5ch3v2) ([raw file](https://github.com/openmpf/openmpf/blob/f9c9c1ac47d9afd15eb431a27a2edc06f823efc4/pom.xml#L154)):*
> ```XML
>         <google.protobuf.version>2.6.1</google.protobuf.version>
>         <janino.version>2.7.8</janino.version>
>         
> ```

It seems that the `@ApiImplicitParam` isn't being respected in the new Swagger page:

```
    @RequestMapping(value = {"/rest/system-message"}, method = RequestMethod.POST )
    @ApiOperation(value="Adds a system message.",
            produces = "application/json", response = MpfResponse.class )
    @ApiResponses(@ApiResponse(code = 201, message = "Successfully added"))
    @ApiImplicitParams({    // need to use this instead of ApiParam because it causes the rendering of the Swagger page to be wrong for the type of parameter
            @ApiImplicitParam(name = "msg", value = "The message", required = true, dataType = "string", paramType = "body"),
            @ApiImplicitParam(name = "msgType", value = "The message type refers to the audience it is intended for (defaults to 'all')", allowableValues = "all,admin,login", required = false, dataType = "string", paramType = "query"),
            @ApiImplicitParam(name = "removeStrategy", value = "Strategy governing how a message is to be removed from the queue (defaults to 'manual'", allowableValues = "atServerStartup,manual", required = false, dataType = "string", paramType = "query"),
            @ApiImplicitParam(name = "severity", value = "Severity of the message (defaults to 'info')", allowableValues = "info,warning,error", required = false, dataType = "string", paramType = "query")
    })
```

Comparing the old page:



to the new page;



Note the drop-downs in the old page for the various parameters.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 84 of 86 files at r1, 13 of 13 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, 8 of 8 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: all files reviewed, 8 unresolved discussions (waiting on @brosenberg42)

___
*[trunk/bin/mpf-scripts/mpf/mpf_sys.py, line 196 at r7](https://reviewable.io/reviews/openmpf/openmpf/1447#-Mz1yXXJDl6ZpRFi5xqG:-Mz1yXXJDl6ZpRFi5xqH:b-patcw4) ([raw file](https://github.com/openmpf/openmpf/blob/3a325006265c649c9d53abafb274ae5cee45ead5/trunk/bin/mpf-scripts/mpf/mpf_sys.py#L196)):*
> ```Python
> 
> class PostgresManager(BaseMpfSystemDependencyManager):
>     SERVICE_NAME = 'postgresql-12'
> ```

I sent you a message about how `mpf start` isn't properly starting postgres.
___
*[trunk/mpf-install/src/main/scripts/mpf-profile.sh, line 66 at r3](https://reviewable.io/reviews/openmpf/openmpf/1447#-MvOz4Ee5nNyyGgZf8eo:-MvOz4Ee5nNyyGgZf8ep:b-i2w61g) ([raw file](https://github.com/openmpf/openmpf/blob/9b0e5160f2a84840e0e09595a1ae42b2f9eabca0/trunk/mpf-install/src/main/scripts/mpf-profile.sh#L66)):*
> ```Shell
> 
> # enable tab completion for mpf script
> command -v register-python-argcomplete > /dev/null && eval "$(register-python-argcomplete mpf)"
> ```

Tab complete doesn't work in Ubuntu. Please remove these lines.
___
*[trunk/workflow-manager/pom.xml, line 104 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRdmxl85mpTp_S43oW:-MuRdmxl85mpTp_S43oX:ba6xw9b) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/pom.xml#L104)):*
> ```XML
>             </exclusions>
>         </dependency>
> 
> ```

Can this be removed?
___
*[trunk/workflow-manager/pom.xml, line 968 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRf-MV54tF6U2S-Zuc:-MuRf-MV54tF6U2S-Zud:bvjn1pz) ([raw file](https://github.com/openmpf/openmpf/blob/f9c9c1ac47d9afd15eb431a27a2edc06f823efc4/trunk/workflow-manager/pom.xml#L968)):*
> ```XML
>         </profile>
>         <profile>
>             <id>protractor</id>
> ```

Should we remove all the protractor test stuff?

- `openmpf/trunk/workflow-manager/src/test/README.md`
- `openmpf/trunk/workflow-manager/src/test/package.json`
- `openmpf/trunk/workflow-manager/src/test/protractor`
- `openmpf/trunk/workflow-manager/src/test/karma`
- `openmpf/trunk/workflow-manager/src/test/delibs`

If you tested this stuff, and it works, we can keep it. Otherwise, I think it's OBE at this point.
___
*[trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/ServerMediaCtrl.js, line 329 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS0n4yCNgTNJI5D3bb:-MuS0n4zArrRwBvEC6MX:b-e8h7xm) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/ServerMediaCtrl.js#L329)):*
> ```JavaScript
>                             url: "server/get-all-files-filtered",
>                             type: "POST",
>                             headers: csrfHeaders(),
> ```

Why are these headers added in some places but not others? For example:

```
                   selectedFileTable = $('#selected_file_list').DataTable({
                        destroy: true,
                        // data: filesToSubmit,
                        stateSave: false,
                        scrollY: '50vh',
                        serverSide: true,
                        scrollCollapse: true,
                        fixedColumns: true, // set widths
                        autoWidth: false, // set widths
                        ajax: function (data, callback, settings) {
```

Are the CSRF headers automatically added for stuff like this?

```
    this.cancelJob = function (jobId) {
        // jobs/{id}/cancel
        var promise = $http({
            url: 'jobs/' + jobId + '/cancel',
            method: "POST"
        }).then(function (response) {
            return response.data;
        });
        return promise;
    };
```
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebUI.java, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS59C04NlOYSHH2wTq:-MuS59C04NlOYSHH2wTr:b-a3n2et) ([raw file](https://github.com/openmpf/openmpf/blob/e83cf36c4b71abafcdf437295b14745b903ad6c2/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebUI.java#L1)):*
> ```Java
> /******************************************************************************
> ```

This was removed, but should we also remove the protractor stuff?
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java, line 339 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS6mYE-aK6tfuw4i9P:-MuS6cNP83C4IX8VxtSu:bvmjpd4) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java#L339)):*
> ```Java
>                                         metadataCaptor.capture());
>         var metadata = metadataCaptor.getValue();
>         assertEquals("4032", metadata.get("FRAME_WIDTH"));
> ```

Why are these values different now?

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: all files reviewed, 8 unresolved discussions (waiting on @brosenberg42)

___
*[pom.xml, line 154 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRKt5P3uAUgG7nzSEd:-Mz31EJ87lGZAUxeE1sD:bat14ql) ([raw file](https://github.com/openmpf/openmpf/blob/f9c9c1ac47d9afd15eb431a27a2edc06f823efc4/pom.xml#L154)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

It seems that the `@ApiImplicitParam` isn't being respected in the new Swagger page:

```
    @RequestMapping(value = {"/rest/system-message"}, method = RequestMethod.POST )
    @ApiOperation(value="Adds a system message.",
            produces = "application/json", response = MpfResponse.class )
    @ApiResponses(@ApiResponse(code = 201, message = "Successfully added"))
    @ApiImplicitParams({    // need to use this instead of ApiParam because it causes the rendering of the Swagger page to be wrong for the type of parameter
            @ApiImplicitParam(name = "msg", value = "The message", required = true, dataType = "string", paramType = "body"),
            @ApiImplicitParam(name = "msgType", value = "The message type refers to the audience it is intended for (defaults to 'all')", allowableValues = "all,admin,login", required = false, dataType = "string", paramType = "query"),
            @ApiImplicitParam(name = "removeStrategy", value = "Strategy governing how a message is to be removed from the queue (defaults to 'manual'", allowableValues = "atServerStartup,manual", required = false, dataType = "string", paramType = "query"),
            @ApiImplicitParam(name = "severity", value = "Severity of the message (defaults to 'info')", allowableValues = "info,warning,error", required = false, dataType = "string", paramType = "query")
    })
```

Comparing the old page:



to the new page;



Note the drop-downs in the old page for the various parameters.
</blockquote></details>

This works better:

```
    @RequestMapping(value = {"/rest/system-message"}, method = RequestMethod.POST)
    @ApiOperation(value="Adds a system message.",
            notes="Use a \"quoted string\" for the message in the request body.",
            produces = "application/json", response = MpfResponse.class )
    @ApiResponses(@ApiResponse(code = 201, message = "Successfully added"))
    @ResponseBody
    public ResponseEntity<MpfResponse> postSystemMessageRest(
            @ApiParam(required = true, value = "The message") @RequestBody String msg,
            @ApiParam(required = false, value = "The message type refers to the audience it is intended for (defaults to 'all')", allowableValues = "all,admin,login") @RequestParam(value = "msgType", required = false) String msgType,
            @ApiParam(required = false, value = "Strategy governing how a message is to be removed from the queue (defaults to 'manual')", allowableValues = "atServerStartup,manual") @RequestParam(value = "removeStrategy", required = false) String removeStrategy,
            @ApiParam(required = false, value = "Severity of the message (defaults to 'info')", allowableValues = "info,warning,error") @RequestParam(value = "severity", required = false) String severity,
            HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse )
            throws InterruptedException, IOException
    {
        SystemMessage systemMessage = new SystemMessage();
        systemMessage.setMsg( msg );
        systemMessage.setMsgType( msgType );
        systemMessage.setRemoveStrategy( removeStrategy );
        systemMessage.setSeverity( severity );
        //P038: todo: would prefer to return the ID of the newly POSTed item within or instead of MpfResponse since now we have to do a GET
        //      of all the messages just to find out which ID we can delete later
        return changeSystemMessageQueue( "POST", systemMessage, -1, httpServletRequest, httpServletResponse );
    }
```

Note the following part:

```
"Use a \"quoted string\" for the message in the request body."
```

I was trying to get some sort of description or example associated with the `@RequestBody` itself, but nothing I did worked. I found [this doc](https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X) for the current 1.5.X annotations. It seems that only the newer 2.X annotations support that, as shown [here](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#requestbody).

One point of confusion is that there's a `@RequestBody` that's part of `org.springframework.web.bind.annotation` and another that's part of `io.swagger.v3.oas.annotations.parameters`.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: 103 of 135 files reviewed, 8 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/mpf-install/src/main/scripts/mpf-profile.sh, line 66 at r3](https://reviewable.io/reviews/openmpf/openmpf/1447#-MvOz4Ee5nNyyGgZf8eo:-MzFKgm23Brz3YKiQ_Dp:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/9b0e5160f2a84840e0e09595a1ae42b2f9eabca0/trunk/mpf-install/src/main/scripts/mpf-profile.sh#L66)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Tab complete doesn't work in Ubuntu. Please remove these lines.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/pom.xml, line 104 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRdmxl85mpTp_S43oW:-MzFKl1n8uf4cZAeDEK-:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/pom.xml#L104)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Can this be removed?
</blockquote></details>

Done.
___
*[trunk/workflow-manager/pom.xml, line 968 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRf-MV54tF6U2S-Zuc:-MzFKyriA-0XPGFhsZBt:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f9c9c1ac47d9afd15eb431a27a2edc06f823efc4/trunk/workflow-manager/pom.xml#L968)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should we remove all the protractor test stuff?

- `openmpf/trunk/workflow-manager/src/test/README.md`
- `openmpf/trunk/workflow-manager/src/test/package.json`
- `openmpf/trunk/workflow-manager/src/test/protractor`
- `openmpf/trunk/workflow-manager/src/test/karma`
- `openmpf/trunk/workflow-manager/src/test/delibs`

If you tested this stuff, and it works, we can keep it. Otherwise, I think it's OBE at this point.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/ServerMediaCtrl.js, line 329 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS0n4yCNgTNJI5D3bb:-MzFIXIY1HuBueQXlmye:bj541om) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/src/main/webapp/resources/mytheme/js/controllers/ServerMediaCtrl.js#L329)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why are these headers added in some places but not others? For example:

```
                   selectedFileTable = $('#selected_file_list').DataTable({
                        destroy: true,
                        // data: filesToSubmit,
                        stateSave: false,
                        scrollY: '50vh',
                        serverSide: true,
                        scrollCollapse: true,
                        fixedColumns: true, // set widths
                        autoWidth: false, // set widths
                        ajax: function (data, callback, settings) {
```

Are the CSRF headers automatically added for stuff like this?

```
    this.cancelJob = function (jobId) {
        // jobs/{id}/cancel
        var promise = $http({
            url: 'jobs/' + jobId + '/cancel',
            method: "POST"
        }).then(function (response) {
            return response.data;
        });
        return promise;
    };
```
</blockquote></details>

The headers for `$http` are added here: https://github.com/openmpf/openmpf/blob/feature/ubuntu/trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/app.js#L163
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebUI.java, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS59C04NlOYSHH2wTq:-MzFL-H98Y4_QPrEaqsB:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e83cf36c4b71abafcdf437295b14745b903ad6c2/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebUI.java#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This was removed, but should we also remove the protractor stuff?
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java, line 339 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS6mYE-aK6tfuw4i9P:-MzFJKYOB7ZATDRMfzp_:by5u571) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java#L339)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why are these values different now?
</blockquote></details>

The newer version of Tika reports it differently

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: 100 of 136 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[pom.xml, line 154 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRKt5P3uAUgG7nzSEd:-MzH_2Y8B-nTYVLaPx2T:b-ubipa3) ([raw file](https://github.com/openmpf/openmpf/blob/f9c9c1ac47d9afd15eb431a27a2edc06f823efc4/pom.xml#L154)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This works better:

```
    @RequestMapping(value = {"/rest/system-message"}, method = RequestMethod.POST)
    @ApiOperation(value="Adds a system message.",
            notes="Use a \"quoted string\" for the message in the request body.",
            produces = "application/json", response = MpfResponse.class )
    @ApiResponses(@ApiResponse(code = 201, message = "Successfully added"))
    @ResponseBody
    public ResponseEntity<MpfResponse> postSystemMessageRest(
            @ApiParam(required = true, value = "The message") @RequestBody String msg,
            @ApiParam(required = false, value = "The message type refers to the audience it is intended for (defaults to 'all')", allowableValues = "all,admin,login") @RequestParam(value = "msgType", required = false) String msgType,
            @ApiParam(required = false, value = "Strategy governing how a message is to be removed from the queue (defaults to 'manual')", allowableValues = "atServerStartup,manual") @RequestParam(value = "removeStrategy", required = false) String removeStrategy,
            @ApiParam(required = false, value = "Severity of the message (defaults to 'info')", allowableValues = "info,warning,error") @RequestParam(value = "severity", required = false) String severity,
            HttpServletRequest httpServletRequest, HttpServletResponse httpServletResponse )
            throws InterruptedException, IOException
    {
        SystemMessage systemMessage = new SystemMessage();
        systemMessage.setMsg( msg );
        systemMessage.setMsgType( msgType );
        systemMessage.setRemoveStrategy( removeStrategy );
        systemMessage.setSeverity( severity );
        //P038: todo: would prefer to return the ID of the newly POSTed item within or instead of MpfResponse since now we have to do a GET
        //      of all the messages just to find out which ID we can delete later
        return changeSystemMessageQueue( "POST", systemMessage, -1, httpServletRequest, httpServletResponse );
    }
```

Note the following part:

```
"Use a \"quoted string\" for the message in the request body."
```

I was trying to get some sort of description or example associated with the `@RequestBody` itself, but nothing I did worked. I found [this doc](https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X) for the current 1.5.X annotations. It seems that only the newer 2.X annotations support that, as shown [here](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#requestbody).

One point of confusion is that there's a `@RequestBody` that's part of `org.springframework.web.bind.annotation` and another that's part of `io.swagger.v3.oas.annotations.parameters`.
</blockquote></details>

Please use the code I provided above. I created [this task](https://github.com/openmpf/openmpf/issues/1509) that we can consider for a later time.

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: 100 of 136 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 337 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS50y32C8mm7ON_DU-:-MuS50y32C8mm7ON_DU0:b2v5cxg) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L337)):*
> ```Java
>         String callbackMethod) throws MalformedURLException {
> 
>         var params = objectMapper.createObjectNode();
> ```

Have you run this test?

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: 99 of 136 files reviewed, 3 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[pom.xml, line 154 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuRKt5P3uAUgG7nzSEd:-MzKaSnSCyG6KKhMfGF1:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f9c9c1ac47d9afd15eb431a27a2edc06f823efc4/pom.xml#L154)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please use the code I provided above. I created [this task](https://github.com/openmpf/openmpf/issues/1509) that we can consider for a later time.
</blockquote></details>

Done.
___
*[trunk/bin/mpf-scripts/mpf/mpf_sys.py, line 196 at r7](https://reviewable.io/reviews/openmpf/openmpf/1447#-Mz1yXXJDl6ZpRFi5xqG:-MzL3YHh9blmAoMXbBuc:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/3a325006265c649c9d53abafb274ae5cee45ead5/trunk/bin/mpf-scripts/mpf/mpf_sys.py#L196)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I sent you a message about how `mpf start` isn't properly starting postgres.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 337 at r2](https://reviewable.io/reviews/openmpf/openmpf/1447#-MuS50y32C8mm7ON_DU-:-MzL6a_l9FB8E9hE7jn9:b2nhswy) ([raw file](https://github.com/openmpf/openmpf/blob/eb8f75d0ce8df617c88380c7811cd466201cea91/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L337)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Have you run this test?
</blockquote></details>

Yes

**Review by jrobble — APPROVED** [review]
> Reviewed 31 of 32 files at r8, 5 of 5 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1447)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
