### PR TITLE
Fix CSRF login issues.

### PR DESCRIPTION
**Pull request by jrobble**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1495

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1494)

### CODE REVIEW

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/LoginController.java, line 106 at r1](https://reviewable.io/reviews/openmpf/openmpf/1494#-MwhxMN-AjLmTFc8PsL3:-MwhxMN-AjLmTFc8PsL4:bgfgy5l) ([raw file](https://github.com/openmpf/openmpf/blob/d2ae4b38d15c81e65f57e2908ee5a5a42a09e027/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/LoginController.java#L106)):*
> ```Java
>     }
> 
>     @RequestMapping(value = { "/logout" }, method = RequestMethod.GET)
> ```

A dedicated logout endpoint allows us to redirect back to the login endpoint. This enables a clean separation between the old and new sessions and allows Spring to properly send a new, valid, CSRF token during the next login sequence.

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

**Review by jrobble — COMMENTED** [review]
> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1494)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

**Review by brosenberg42 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1494)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Comment by jrobble** [comment]
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/TimeoutFilter.java` line 88 at r3](https://reviewable.io/reviews/openmpf/openmpf/1494#-N7NEJgk7aXntiq57Hin:-N7NEJgo9fTw45LyKYLs:bs7glwx) ([raw file](https://github.com/openmpf/openmpf/blob/c6818934ed5dbcd2a867cd79d316095b8b208ed5/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/TimeoutFilter.java#L88)):*
> ```Java
>                               FilterChain chain) throws IOException, ServletException {
>         HttpSession session = request.getSession(false);
>         if (session == null) {
> ```

This change results in a timeout message appearing instead of a bootout message when the same user logs in using different browsers at the same time.

When a bootout should occur the URL is `/workflow-manager/bootout`. Before your changes, that resulted in executing this code below:

```
if (excludeUrl) {
    log.debug("URI matches exclude pattern={}, keep going", excludeUrl);
    chain.doFilter(request, response);
```

**Review by jrobble — COMMENTED** [review]
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1494)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

**Pull request merged**
