### PR TITLE
S3 improvements

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/977
- https://github.com/openmpf/openmpf/issues/1030
- https://github.com/openmpf/openmpf/issues/849
- https://github.com/openmpf/openmpf/issues/1496

**Related PRs:**
- https://github.com/openmpf/openmpf.github.io/pull/145

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1497)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 16 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1497)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java, line 44 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRQUn44oq1Rb2pM9_h:-MzRQUn5B-opTyMh--yc:b-g3m2q5) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java#L44)):*
> ```Java
>             if (s3Host == null || s3Host.isBlank()) {
>                 throw new StorageException(String.format(
>                         "When %s is provided, %s almost must be provided.",
> ```

"almost must"?

Let's say: "When %s is provided, %s must be provided."
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java, line 66 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRQoFz-YKFTzEg3ZOZ:-MzRQoG-DXVGR9sTDPIK:b-fknpkx) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java#L66)):*
> ```Java
>     static final S3UrlUtil PATH_STYLE = new S3UrlUtil() {
>         @Override
>         public String getResultsBucketName(URI bucketUri) throws StorageException{
> ```

Needs space before brace: `StorageException{`
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java, line 190 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRtrFM2yzfzp2XjsvN:-MzRtrFM2yzfzp2XjsvO:b-hpy57p) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java#L190)):*
> ```Java
>             var bucket = getResultsBucketName(uri);
>             var path = uri.getPath();
>             if (path.startsWith("/")) {
> ```

For path style you check that the object key is not blank, but you don't check that for the virtual  host style.
___
*[trunk/workflow-manager/src/main/resources/workflow-properties.json, line 361 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRWWqL1CkCat7JTwyc:-MzRWWqL1CkCat7JTwyd:b1tl7v5) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/resources/workflow-properties.json#L361)):*
> ```JSON
>     {
>         "name": "S3_REGION",
>         "description": "Region to use when downloading and uploading to S3.",
> ```

Please give an example in the description.
___
*[trunk/workflow-manager/src/main/resources/workflow-properties.json, line 368 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRWbCz7FP5HaTyrOUx:-MzRWbCz7FP5HaTyrOUy:b-vgwlpl) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/resources/workflow-properties.json#L368)):*
> ```JSON
>     {
>         "name": "S3_USE_VIRTUAL_HOST",
>         "description": "When true, the S3 client will configured to virtual host style access (bucket name is part of domain name), otherwise path style access (bucket name is first segment in URL path) will be used.",
> ```

Please give an example of each type in the description.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1497)* status: 14 of 16 files reviewed, 5 unresolved discussions (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java, line 44 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRQUn44oq1Rb2pM9_h:-MzV0Lip6DB8vNOmfN-L:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java#L44)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

"almost must"?

Let's say: "When %s is provided, %s must be provided."
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java, line 66 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRQoFz-YKFTzEg3ZOZ:-MzV0_Gk36v68WvCajLI:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java#L66)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Needs space before brace: `StorageException{`
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java, line 190 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRtrFM2yzfzp2XjsvN:-MzV1Wt2B2vwRA-qQ5IT:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java#L190)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For path style you check that the object key is not blank, but you don't check that for the virtual  host style.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/resources/workflow-properties.json, line 361 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRWWqL1CkCat7JTwyc:-MzV414M18ef-aaZf-zL:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/resources/workflow-properties.json#L361)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please give an example in the description.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/resources/workflow-properties.json, line 368 at r1](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzRWbCz7FP5HaTyrOUx:-MzV41JU2kGUsFAAd0Tl:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/aca7b842d7c9bd5e66e343daec2e53a1c59bb324/trunk/workflow-manager/src/main/resources/workflow-properties.json#L368)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please give an example of each type in the description.
</blockquote></details>

Done.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1497)* status: 11 of 16 files reviewed, 6 unresolved discussions (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java, line 159 at r2](https://reviewable.io/reviews/openmpf/openmpf/1497#-MzVm08bDq-ascTbne6r:-MzVqvK-9xQ3y-YSttzj:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0438f151ac912e83062a90020cd87142135f12dd/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/S3UrlUtil.java#L159)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

If the user doesn't provide a valid URL for the results bucket this line will cause a NPE and the job will get stuck in progress. Both `getHost()` and `getPath()` can return null. 
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 4 of 4 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1497)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
