### PR TITLE
Refactored ITWebStreamingHealthReports into ITWebStreamingReports to also test summary reports.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/451)

### CODE REVIEW

**Comment by brosenberg42** [comment]
testPostSummaryReportCallback times out on my local machine.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/451#-:-L4uyCn9wtHRmkYwE2jx:b-x62nxp)*

**Comment by jrobble** [comment]
Does `testPostPeriodicHealthReportCallback` pass?

Please email me the console output of the test run.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/451#-:-L4xz5iJd590o3O7ETWY:b-2lafek)*

**Comment by jrobble** [comment]
Updated to work with SUBSENSE MOTION DETECTION (WITH TRACKING) PIPELINE. Requires https://github.com/openmpf/openmpf-contrib-components/pull/36 to land first.

Decided not to use HelloWorld Test component because building it ahead of time messes up ITComponentRegistration.canRegisterAndUnregisterCppComponent().

Decided not to use HelloWorld Sample component because it's not part of a normal build.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/451#-:-L5CA28G9Kt4Ra_feG6J:b76ul86)*

**Comment by brosenberg42** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 108 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/451#-L5FJ03zBZ7lqXlDJGfG:-L5FJ03zBZ7lqXlDJGfH:bipdhk1) ([raw file](https://github.com/openmpf/openmpf/blob/24c06ccd8a1ffb50017dfd7dae9284d6b5ad2e99/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L108)):*
> ```Java
>             .getJSON(new URL(pipelinesUrl), WebRESTUtils.MPF_AUTHORIZATION);
> 
>         Assert.assertTrue("Please register the component that supports the following pipeline: " + PIPELINE_NAME,
> ```

I think this should be `Assume.assumeTrue(...)`

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 279 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/451#-L5FJeHRHFHMdkA9XXq0:-L5FJeHRHFHMdkA9XXq1:b3twbja) ([raw file](https://github.com/openmpf/openmpf/blob/24c06ccd8a1ffb50017dfd7dae9284d6b5ad2e99/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L279)):*
> ```Java
>                 } catch (Exception e) {
>                     log.error("Exception caught while processing health report POST callback.", e);
>                     Assert.fail();
> ```

This doesn't actually make the test fail because it executed on a separate thread.

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 322 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/451#-L5FJvjt2CQ6ACyxiKhe:-L5FJvjt2CQ6ACyxiKhf:b3twbja) ([raw file](https://github.com/openmpf/openmpf/blob/24c06ccd8a1ffb50017dfd7dae9284d6b5ad2e99/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L322)):*
> ```Java
>                 } catch (Exception e) {
>                     log.error("Exception caught while processing summary report POST callback.", e);
>                     Assert.fail();
> ```

This doesn't actually make the test fail because it executed on a separate thread.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/451)*

**Comment by jrobble** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 108 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/451#-L5FJ03zBZ7lqXlDJGfG:-L5FWxIPWCxlVu6bT6Ni:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/24c06ccd8a1ffb50017dfd7dae9284d6b5ad2e99/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L108)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think this should be `Assume.assumeTrue(...)`
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 279 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/451#-L5FJeHRHFHMdkA9XXq0:-L5FYsU6ilCcipFuhv3K:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/24c06ccd8a1ffb50017dfd7dae9284d6b5ad2e99/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L279)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This doesn't actually make the test fail because it executed on a separate thread.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java, line 322 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/451#-L5FJvjt2CQ6ACyxiKhe:-L5FYt1i3HnQQ83ToIfJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/24c06ccd8a1ffb50017dfd7dae9284d6b5ad2e99/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITWebStreamingReports.java#L322)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This doesn't actually make the test fail because it executed on a separate thread.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/451)*

**Pull request merged**
