### PR TITLE
Add transient pipelines support

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1428

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1472)

### CODE REVIEW

**Review by clnowacki — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1472)* status: 0 of 20 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientTask.java, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf/1472#-MxfM56SDxZLXnFsWBYK:-MxfM56SDxZLXnFsWBYL:b8vejk9) ([raw file](https://github.com/openmpf/openmpf/blob/3117ac2997321487a78958c18924b44cd9f6f6b5/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientTask.java#L49)):*
> ```Java
> 
>     private final ImmutableList<String> _actions;
>     @NotEmpty
> ```

It is not possible to create a transient pipeline that consists of a list of the names of existing tasks, without also listing the entire definition of the actions with the task, because the actions list is required to be Not Empty. So for example, it is not possible to create a pipeline like this, even though the tasks listed are well-defined within the system:

 "pipelineDefinition": {
     "pipeline": [
        "CAFFE GOOGLENET DETECTION TASK",
        "TENSORFLOW VEHICLE COLOR DETECTION TASK"
      ],
     "tasks": [
       {
        "name": "CAFFE GOOGLENET DETECTION TASK"
        },
       {
         "name": "TENSORFLOW VEHICLE COLOR DETECTION TASK"
       }
      ]
},

**Review by clnowacki — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1472)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1472#-MxfU71b7uvmgIzMWljW:-MxfU71c0Hr7GtqnyhlK:bfeadll) (no related file):*
Putting this here as a reminder that when the github.io documentation for this feature is done, we should add a link to it in the JobController @ApiOperation annotation.

---

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1472)* status: 0 of 20 files reviewed, 2 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientTask.java, line 49 at r2](https://reviewable.io/reviews/openmpf/openmpf/1472#-MxfM56SDxZLXnFsWBYK:-MxiuS13-LxZpHqjRSII:b-3wg55i) ([raw file](https://github.com/openmpf/openmpf/blob/3117ac2997321487a78958c18924b44cd9f6f6b5/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientTask.java#L49)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

It is not possible to create a transient pipeline that consists of a list of the names of existing tasks, without also listing the entire definition of the actions with the task, because the actions list is required to be Not Empty. So for example, it is not possible to create a pipeline like this, even though the tasks listed are well-defined within the system:

 "pipelineDefinition": {
     "pipeline": [
        "CAFFE GOOGLENET DETECTION TASK",
        "TENSORFLOW VEHICLE COLOR DETECTION TASK"
      ],
     "tasks": [
       {
        "name": "CAFFE GOOGLENET DETECTION TASK"
        },
       {
         "name": "TENSORFLOW VEHICLE COLOR DETECTION TASK"
       }
      ]
},
</blockquote></details>

[partial-transient.json](https://github.com/openmpf/openmpf/blob/feature/pipeline-in-job/trunk%2Fworkflow-manager%2Fsrc%2Ftest%2Fresources%2Ftransient-pipelines%2Fpartial-transient.json) has an example of how you do that.
The specific issue above is that if you want to use preexisting tasks, you should only reference them, not define them as well. The pipeline above should be defined as:
```json
{
    "pipelineDefinition": {
        "pipeline": [
            "CAFFE GOOGLENET DETECTION TASK",
            "TENSORFLOW VEHICLE COLOR DETECTION TASK"
        ]
    }
}
```
When resolving the tasks in the `"pipeline"` list, it will look for a task defined in the `"tasks"` element. If it isn't there, then it will look for a preexisting non-transient task. It works this way so that the job producer trying to run a fully transient pipeline doesn't need to know what tasks exist in the system in order to submit their job.

**Review by clnowacki — COMMENTED** [review]
> Reviewed 19 of 20 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1472)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientAction.java, line 28 at r2](https://reviewable.io/reviews/openmpf/openmpf/1472#-MxpM-LSCYzVBLC-CtRx:-MxpM-LSCYzVBLC-CtRy:bk73321) ([raw file](https://github.com/openmpf/openmpf/blob/3117ac2997321487a78958c18924b44cd9f6f6b5/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientAction.java#L28)):*
> ```Java
> 
> 
> package org.mitre.mpf.rest.api.pipelines.temp;
> ```

Could we change the name of this directory from .../pipelines/temp to .../pipelines/transients?

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1472)* status: 8 of 21 files reviewed, 2 unresolved discussions (waiting on @brosenberg42, @clnowacki, and @jrobble)

___
*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientAction.java, line 28 at r2](https://reviewable.io/reviews/openmpf/openmpf/1472#-MxpM-LSCYzVBLC-CtRx:-My7Z8bn0l9YTm0Xhdw6:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/3117ac2997321487a78958c18924b44cd9f6f6b5/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/pipelines/temp/TransientAction.java#L28)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

Could we change the name of this directory from .../pipelines/temp to .../pipelines/transients?
</blockquote></details>

Done.

**Review by clnowacki — COMMENTED** [review]
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1472)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

**Review by clnowacki — APPROVED** [review]

**Pull request merged**
