### PR TITLE
Add timestamps to summary report

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/429)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[trunk/detection/executor/cpp/streaming/BasicAmqMessageSender.cpp, line 129 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42jYIKFoGQEp_WSOCe:-L42jYIKFoGQEp_WSOCf:b6zrrk4) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/BasicAmqMessageSender.cpp#L129)):*
> ```cpp
>                 protobuf_detection->set_y_left_upper(frame_location.y_left_upper);
>                 protobuf_detection->set_width(frame_location.width);
>                 protobuf_detection->set_height(frame_location.height);
> ```

Good catch!

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 155 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42qQQKzybTDbv_1NBe:-L42qQQKzybTDbv_1NBf:b-t3wyl5) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L155)):*
> ```cpp
>         }
>         catch (const FatalError &ex) {
>             sender.SendSummaryReport(0, detection_type, {}, { {0, GetTimestampMillis()} }, ex.what());
> ```

I don't think we need to send in an initialized timestamp map here.

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 164 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42qXmkF4EdecsvD57e:-L42kuo7_Et6s1HUJXsb:bx4e4b5) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L164)):*
> ```cpp
>     void Run() {
>         int frame_number = -1;
>         std::unordered_map<int, long> frame_timestamps { {frame_number, GetTimestampMillis()} };
> ```

I don't think we need to create an initial entry for this map.

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 249 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L432d0mjzQ4EvwbsO6H:-L42yM0leRFFfHtl2dJj:bv0ragz) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L249)):*
> ```cpp
> 
> 
>     void FixTracks(int frame_number, std::vector<MPFVideoTrack> &tracks) {
> ```

Writing some gtests for this (potentially by separating it out into a util) would be nice, but I know we're running out of time, so I can make a wishlist item for that. What do you prefer?

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 252 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42qsfJEkiLkSIls8A6:-L42qsfJEkiLkSIls8A7:b-f7w8mo) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L252)):*
> ```cpp
>         int segment_number = frame_number / settings_.segment_size;
>         int segment_begin = segment_number * settings_.segment_size;
>         int segment_end = segment_begin + settings_.segment_size - 1;
> ```

Instead of calculating all this again, could we just save and pass in the VideoSegmentInfo? Maybe it can be used in `IsBeginningOfSegment` and `IsEndOfSegment` too, or maybe it will make those obsolete.

---

*[trunk/protobuf/src/main/proto/detection.proto, line 243 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42i_9mhzU8eMVb4UQK:-L42i_9mhzU8eMVb4UQL:bh58ugc) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/protobuf/src/main/proto/detection.proto#L243)):*
> ```protobuf
> message StreamingVideoDetection {
>     optional int32 frame_number = 1;
>     optional int64 time = 2;
> ```

AudioRequest and AudioResponse use `int32` for time. Should that be `int64`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/429)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.cpp, line 75 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L44JhiUZfjwOherF3Fv:-L44JhiUZfjwOherF3Fw:brm49v4) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.cpp#L75)):*
> ```cpp
>         segment_detections_.push_back(std::move(track));
>     }
>     return true;
> ```

This should only return true when generating the first track.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/429)*

**Comment by brosenberg42** [comment]
Review status: 6 of 13 files reviewed at latest revision, 7 unresolved discussions.

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 155 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42qQQKzybTDbv_1NBe:-L47PGZ1mrAFPhCv8Wdt:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L155)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't think we need to send in an initialized timestamp map here.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 164 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42qXmkF4EdecsvD57e:-L47PGvRFMmHRo-lgGUQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L164)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I don't think we need to create an initial entry for this map.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 249 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L432d0mjzQ4EvwbsO6H:-L47PMd3Z_oBgU8wiNFb:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L249)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Writing some gtests for this (potentially by separating it out into a util) would be nice, but I know we're running out of time, so I can make a wishlist item for that. What do you prefer?
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/streaming/main.cpp, line 252 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42qsfJEkiLkSIls8A6:-L47PIUeiQoQLlIt7DdQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/executor/cpp/streaming/main.cpp#L252)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of calculating all this again, could we just save and pass in the VideoSegmentInfo? Maybe it can be used in `IsBeginningOfSegment` and `IsEndOfSegment` too, or maybe it will make those obsolete.
</blockquote></details>

Done.

---

*[trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.cpp, line 75 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L44JhiUZfjwOherF3Fv:-L47PL9Qpcw1eU4c4W91:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/detection/test-components/cpp/CplusplusHelloWorld/StreamingHelloWorld.cpp#L75)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This should only return true when generating the first track.
</blockquote></details>

Done.

---

*[trunk/protobuf/src/main/proto/detection.proto, line 243 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42i_9mhzU8eMVb4UQK:-L47PnEOk5wRkmjHBTmB:b-hlv247) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/protobuf/src/main/proto/detection.proto#L243)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

AudioRequest and AudioResponse use `int32` for time. Should that be `int64`?
</blockquote></details>

Yea, I think so.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/429)*

**Comment by jrobble** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[trunk/detection/executor/cpp/streaming/test/test_streaming_executor.cpp, line 176 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L47fP0emI6Jc0PJixqe:-L47fP0fLCFOGopa24ql:b4c9lyr) ([raw file](https://github.com/openmpf/openmpf/blob/a05e7d26c7222177018233ceb5a9c7ef45d64f24/trunk/detection/executor/cpp/streaming/test/test_streaming_executor.cpp#L176)):*
> ```cpp
>             createTrack({5, 10, 15, 23}) });
> 
> }
> ```

:thumbsup: 

---

*[trunk/protobuf/src/main/proto/detection.proto, line 243 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/429#-L42i_9mhzU8eMVb4UQK:-L47bZ06X3ayPOlN0w_b:b-no7vwb) ([raw file](https://github.com/openmpf/openmpf/blob/9dc51956b9e5dcc43bf5b4786a30e3ec555f2eba/trunk/protobuf/src/main/proto/detection.proto#L243)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Yea, I think so.
</blockquote></details>

Ok. I created https://github.com/openmpf/openmpf/issues/434 for later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/429)*

**Pull request merged**
