### PR TITLE
Fixed testBadPipeline() by expecting exception.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/298)

### CODE REVIEW

**Comment by jrobble** [comment]
Resolves this issue:

```
Error Message

Missing pipeline: "X".
Stacktrace

org.mitre.mpf.wfm.exceptions.InvalidPipelineObjectWfmProcessingException: Missing pipeline: "X".
	at org.mitre.mpf.wfm.service.PipelineServiceImpl.createJsonPipeline(PipelineServiceImpl.java:172)
	at org.mitre.mpf.wfm.businessrules.impl.JobRequestBoImpl.createRequest(JobRequestBoImpl.java:129)
	at org.mitre.mpf.mst.TestSystem.runPipelineOnMedia(TestSystem.java:224)
	at org.mitre.mpf.mst.TestSystemNightly.testBadPipeline(TestSystemNightly.java:150)
Standard Output

2017-10-22 20:59:27,213 INFO [Time-limited test] org.mitre.mpf.mst.TestSystemNightly - Beginning test #8 testBadPipeline()
```

**Comment by dpierce17** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 151 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/298#-KxEZBExZHg5TTQSxLym:-KxEZBExZHg5TTQSxLyn:b-9omaod) ([raw file](https://github.com/openmpf/openmpf/blob/61e4fb0dd29ce47d35f20d2d23a02f7dcab67f2e/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L151)):*
> ```Java
>         log.info("Beginning test #{} testBadPipeline()", testCtr);
>         List<JsonMediaInputObject> media = toMediaObjectList(ioUtils.findFile("/samples/face/meds-aa-S001-01.jpg"));
>             long jobId = runPipelineOnMedia("X", media, Collections.emptyMap(), propertiesUtil.isOutputObjectsEnabled(),
> ```

check indentation, the statement that starts with long jobId looks like it has extra indentation

---

*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 153 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/298#-KxE_Uq4ZECt8Lq4pLDO:-KxE_QUJAuHzzHAArp_b:b-z6vsmg) ([raw file](https://github.com/openmpf/openmpf/blob/61e4fb0dd29ce47d35f20d2d23a02f7dcab67f2e/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L153)):*
> InvalidPipelineObjectWfmProcessingException
If the InvalidPipelineObjectWfmProcessingException is thrown, then the log.error statement is never executed.  Is that the intent? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/298)*

**Comment by jrobble** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 151 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/298#-KxEZBExZHg5TTQSxLym:-KxF5mfNRtZEjORqhCKc:be2n437) ([raw file](https://github.com/openmpf/openmpf/blob/61e4fb0dd29ce47d35f20d2d23a02f7dcab67f2e/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L151)):*
<details><summary><i>Previously, dpierce17 wrote…</i></summary><blockquote>

check indentation, the statement that starts with long jobId looks like it has extra indentation
</blockquote></details>

I will fix this.

---

*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 153 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/298#-KxE_Uq4ZECt8Lq4pLDO:-KxF5dMM24_kcr_ez7gv:bsmrmin) ([raw file](https://github.com/openmpf/openmpf/blob/61e4fb0dd29ce47d35f20d2d23a02f7dcab67f2e/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L153)):*
<details><summary><i>Previously, dpierce17 wrote…</i></summary><blockquote>

> InvalidPipelineObjectWfmProcessingException
If the InvalidPipelineObjectWfmProcessingException is thrown, then the log.error statement is never executed.  Is that the intent? 
</blockquote></details>

Yeah, that's the intent. It's why I changed `log.info()` to `log.error()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/298)*

**Comment by dpierce17** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/298)*

**Pull request merged**
