### PR TITLE
Json output update branch2

### PR DESCRIPTION
**Pull request by dpierce17**
Changed comments in TestSystemNightly as you requested.   But, I don't see the media line you're referring to in runFaceOcvCustomDetectVideo-defaultCompare.json (i.e. "path": "file:///home/mpf/dev/mpf/trunk/mpf-system-tests/target/test-classes/samples/person/chokepoint_P2E_S5_C1.mp) so I'm not sure how to make the change that you requested.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/105)

### CODE REVIEW

**Comment by jrobble** [comment]
Don't worry about the chokepoint_P2E_S5_C1 thing. Your JSON only includes the piece of media specified in the test. That's how it should be.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 224 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/105#-Km2-QrjGDR0fni2yUjb:-Km2-QrjGDR0fni2yUjc:b-qevcwf) ([raw file](https://github.com/openmpf/openmpf/blob/470b5e5bf37a6bfdf8e4f4fd960d0f029fe8585c/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L224)):*
> ```Java
> //        // uncomment to generate default output
> //        String actionName = "TEST X OCV FACE";
> //        addAction(actionName, "FACECV", Collections.emptyMap());
> ```

Do you need the 3 lines above? As mentioned in the other pull request, "OCV FACE DETECTION PIPELINE" comes with OpenMPF by default, so you shouldn't have to add an action for it. The action used by that pipeline comes with OpenMPF by default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/105#-:-Km202JfyujEay6UolpZ:b-xwgr6a)*

**Comment by dpierce17** [comment]
Yes, I need the 3 lines above.  The alternate block of lines for running the nightly test include the explicit setting of the MIN_FACE_SIZE property rather than relying on the default - so I'd like to leave it in.

**Comment by dpierce17** [comment]
I kicked off a openmpf-github-with-pull-request Jenkins build  (this was build #104 and #105, I tried it twice). Both builds failed, and I'm not sure why.  I looked at the console output and saw a few errors, these included a fatal: Could not read from remote repository error, plus many warnings that looked like:
[WARN] ActiveMQ is not currently running.
[WARN] MySQL is not currently running.
[WARN] Redis is not currently running.
[WARN] Node Manager is not currently running.
[WARN] Node amq_detection_component is not currently running.
[WARN] Node mpf-speech-detection is not currently running.

Can you or Brian advise?

**Comment by jrobble** [comment]
@brosenberg42 is fixing Jenkins

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/105#-:-Km2eX_doeI724GBTyis:bv75lgn)*

**Comment by jrobble** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/105)*

**Comment by dpierce17** [comment]
Yes, these failures still remain:
    org.mitre.mpf.mst.TestSystemNightly.testTiffImageMarkup
    org.mitre.mpf.mst.TestSystemNightly.testPriorities
But it was my understanding that these failures have nothing to do with updating the JSON output objects.  Can you advise?

**Pull request merged**
