### PR TITLE
Clean up pipeline services

### PR DESCRIPTION
**Pull request by brosenberg42**
Issue #149

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/157)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 25 of 27 files at r1, 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelineServiceImpl.java, line 59 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KonYK5R7BGCRPZo3uge:-KonYK5R7BGCRPZo3ugf:b-nu7tgc) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelineServiceImpl.java#L59)):*
> ```Java
> 
> @Component
> public class PipelineServiceImpl implements PipelinesService {
> ```

If we're going to stick with the plural, PipelinesService, then this should be PipelinesServiceImpl. I prefer renaming the interface to PipelineService though.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelineServiceImpl.java, line 235 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KonYZuYQaV-H6hEOvEG:-KonYZuZ8UE0UkMx6ujK:b65xdvz) ([raw file](https://github.com/openmpf/openmpf/blob/745ccaa0158f9ef75f159475e414a294142e27c5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelineServiceImpl.java#L235)):*
> ```Java
> 
>     @Deprecated
>     public Tuple<Boolean, String> saveDeprecated(String type) {
> ```

I'm happy to see the deprecated methods go. The last one are in PipelineController. There's a separate issue for that.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java, line 27 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KorqCFzDtmuHeTu95DT:-KorqCG-uRCMez5m89C9:b4g3joi) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java#L27)):*
> ```Java
>  ******************************************************************************/
> 
> package org.mitre.mpf.wfm.pipeline;
> ```

Should this be in org.mitre.mpf.wfm.service.pipeline instead?

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java, line 36 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KonXbXe3UzkhFOg7oxW:-KonXbXe3UzkhFOg7oxX:b71gi1h) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java#L36)):*
> ```Java
> import java.util.SortedSet;
> 
> public interface PipelinesService {
> ```

You used the plural in the name. If we do this, shouldn't we also rename to "PipelinesManager", "PipelinesController", and "JobsController" for consistency? I prefer renaming the interface to PipelineService.

---

*[trunk/workflow-manager/src/main/resources/applicationContext-minimal.xml, line 38 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KorpCNEEzBCKvBKR9km:-KorpCNEEzBCKvBKR9kn:b-bnisr6) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/resources/applicationContext-minimal.xml#L38)):*
> ```XML
>     <context:component-scan base-package="org.mitre.mpf.wfm.util" use-default-filters="false">
>         <context:include-filter type="assignable" expression="org.mitre.mpf.wfm.util.PropertiesUtil"/>
>         <context:include-filter type="assignable" expression="org.mitre.mpf.wfm.pipeline.PipelineServiceImpl"/>
> ```

Should this be PipelineService instead? I don't see any other "impl" up here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/157)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java, line 27 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KorqCFzDtmuHeTu95DT:-Korun0SRWgT1eGlMuWp:bvxw1zq) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should this be in org.mitre.mpf.wfm.service.pipeline instead?
</blockquote></details>

If we move this, what do you think we should do with the org.mitre.mpf.wfm.pipeline.xml package (if anything)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/157)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java, line 27 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KorqCFzDtmuHeTu95DT:-KorzOMlWvZdVBlDD4Zk:b5njp1s) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/pipeline/PipelinesService.java#L27)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

If we move this, what do you think we should do with the org.mitre.mpf.wfm.pipeline.xml package (if anything)?
</blockquote></details>

Let's leave it since those classes are used by more than the service.

That said, you can just move PipelineService and PipelineServiceImpl to org.mitre.mpf.wfm.service.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/157)*

**Comment by brosenberg42** [comment]
Review status: 5 of 23 files reviewed at latest revision, 5 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineService.java, line 27 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KorqCFzDtmuHeTu95DT:-Kow2ykmQbPSOHQLPZrJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineService.java#L27)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's leave it since those classes are used by more than the service.

That said, you can just move PipelineService and PipelineServiceImpl to org.mitre.mpf.wfm.service.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineService.java, line 36 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KonXbXe3UzkhFOg7oxW:-Kow29tbpaT7mkaFTMRJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineService.java#L36)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You used the plural in the name. If we do this, shouldn't we also rename to "PipelinesManager", "PipelinesController", and "JobsController" for consistency? I prefer renaming the interface to PipelineService.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineServiceImpl.java, line 59 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KonYK5R7BGCRPZo3uge:-Kow2BN_vo0ZAKznyZAL:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/PipelineServiceImpl.java#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

If we're going to stick with the plural, PipelinesService, then this should be PipelinesServiceImpl. I prefer renaming the interface to PipelineService though.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/resources/applicationContext-minimal.xml, line 38 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/157#-KorpCNEEzBCKvBKR9km:-Kow2wN23LeIw5AKw1oC:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/0b15fb02ccbf571c0357a394617b7efd91819197/trunk/workflow-manager/src/main/resources/applicationContext-minimal.xml#L38)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should this be PipelineService instead? I don't see any other "impl" up here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/157)*

**Comment by jrobble** [comment]
:lgtm:

---

Reviewed 20 of 20 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/157#-:-KowDEYaz7LqKhsLKUbC:bnfp4nl)*

**Pull request merged**
