### PR TITLE
Add StreamingServiceManager and use it during component registration.

### PR DESCRIPTION
**Pull request by brosenberg42**
Issue #333

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/342)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/component/RegisterComponentModel.java, line 43 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0r4lIe4zksNJ1Zzxf:-Kz0r4lIe4zksNJ1Zzxg:b-ptk64q) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/component/RegisterComponentModel.java#L43)):*
> ```Java
>     private String _algorithmName;
>     private String _serviceName;
>     private String _streamingServiceName;
> ```

For batch and streaming I see that the service name is set to `descriptor.componentName`. Will they ever be different?

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceModel.java, line 39 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0nt7fC_RXxJdLows_:-Kz0nt7gYiVOqYO1Fncv:bw18nx4) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceModel.java#L39)):*
> ```Java
> public class StreamingServiceModel {
> 
> 	private String serviceName;
> ```

In some classes (such as this one) you prefix data members with underscores and in other classes (such as `StreamingServiceManagerImpl`) you don't. Is there a reason?

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 498 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0pe82DEG-YsZmx8Zx:-Kz0pe8328aFRGbp7FXL:bx3g1ng) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L498)):*
> ```Java
>         if (existingSvc) {
>             throw new ComponentRegistrationSubsystemException(String.format(
>                     "Couldn't add the %s streaming service because another service already has that name",
> ```

End in period.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 515 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0poqs4cGxyXgiuXCz:-Kz0poqs4cGxyXgiuXD-:b-nolejg) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L515)):*
> ```Java
>         }
>         else {
>         	throw new IllegalArgumentException(String.format("Stream processing is not supported for %s components.",
> ```

Add a TODO here about supporting other languages.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/342)*

**Comment by jrobble** [comment]
I ran this and it works as expected. See inline comments.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceManagerImpl.java, line 106 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz2F-Au2wOuFHEpzKjE:-Kz2F-Av9gvBhRzF7chQ:bke98yv) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceManagerImpl.java#L106)):*
> ```Java
> 	private void save() {
> 		try (OutputStream outputStream = _propertiesUtil.getStreamingServices().getOutputStream()) {
> 			_objectMapper.writeValue(outputStream, _serviceModels);
> ```

Please use `writerWithDefaultPrettyPrinter()` like it's done with nodeServicesPalette.json:

```
try (OutputStream outStream = paletteResource.getOutputStream()) {
            objectMapper.writerWithDefaultPrettyPrinter()
                    .writeValue(outStream, nodeManagerFilePaletteMap);
            return true;
        }
```

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 515 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0poqs4cGxyXgiuXCz:-Kz21XwIZ77nwyv9jOoF:bg4nfzu) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L515)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a TODO here about supporting other languages.
</blockquote></details>

Note that this exception brings down the whole registration process so that nothing gets registered after it's thrown:

```
2017-11-15 23:14:27,730 ERROR [localhost-startStop-1] o.s.web.context.ContextLoader - Context initialization failed
java.lang.IllegalArgumentException: Stream processing is not supported for JAVA components.
	at org.mitre.mpf.wfm.service.component.AddComponentServiceImpl.saveStreamingService(AddComponentServiceImpl.java:515) ~[AddComponentServiceImpl.class:na]
```

Tomcat starts, but trying to access http://localhost:8080/workflow-manager shows a blank page.

Should we throw a `ComponentRegistrationSubsystemException` instead so that it can be caught and handled appropriately in `registerDeployedComponent()`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/342#-:-Kz2FV1_jLsKzv29Ivkz:bdmi3w3)*

**Comment by brosenberg42** [comment]
Review status: 10 of 15 files reviewed at latest revision, 5 unresolved discussions.

---

*[trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/component/RegisterComponentModel.java, line 43 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0r4lIe4zksNJ1Zzxf:-Kz4ztW2Vw2Ntf-S_Fkp:bq4ycpc) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/mpf-rest-api/src/main/java/org/mitre/mpf/rest/api/component/RegisterComponentModel.java#L43)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

For batch and streaming I see that the service name is set to `descriptor.componentName`. Will they ever be different?
</blockquote></details>

Right now it will always be set to `descriptor.componentName`. I think it is better to store the name instead of relying on a naming convention.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceManagerImpl.java, line 106 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz2F-Au2wOuFHEpzKjE:-Kz53bEkL77G9nS5rCGm:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceManagerImpl.java#L106)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please use `writerWithDefaultPrettyPrinter()` like it's done with nodeServicesPalette.json:

```
try (OutputStream outStream = paletteResource.getOutputStream()) {
            objectMapper.writerWithDefaultPrettyPrinter()
                    .writeValue(outStream, nodeManagerFilePaletteMap);
            return true;
        }
```

</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceModel.java, line 39 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0nt7fC_RXxJdLows_:-Kz5-xniIPkoZl9u1hH9:bg8qg5) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceModel.java#L39)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

In some classes (such as this one) you prefix data members with underscores and in other classes (such as `StreamingServiceManagerImpl`) you don't. Is there a reason?
</blockquote></details>

I prefer the underscore naming convention. It very easy to forget a `this.` and assign to the wrong variable. Also, `_` is shorter than `this.` When I originally wrote AddComponentServiceImpl it used the underscore naming convention, but at some point it was changed to not use underscores. 
I was originally considering making the fields of this class public final since the getters don't really do anything. I decided to use getters and forgot to rename the fields. 

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 498 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0pe82DEG-YsZmx8Zx:-Kz53cXjKSscGJdfar2V:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L498)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

End in period.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 515 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0poqs4cGxyXgiuXCz:-Kz52I5szlDxTPXkSzS5:bberi06) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L515)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note that this exception brings down the whole registration process so that nothing gets registered after it's thrown:

```
2017-11-15 23:14:27,730 ERROR [localhost-startStop-1] o.s.web.context.ContextLoader - Context initialization failed
java.lang.IllegalArgumentException: Stream processing is not supported for JAVA components.
	at org.mitre.mpf.wfm.service.component.AddComponentServiceImpl.saveStreamingService(AddComponentServiceImpl.java:515) ~[AddComponentServiceImpl.class:na]
```

Tomcat starts, but trying to access http://localhost:8080/workflow-manager shows a blank page.

Should we throw a `ComponentRegistrationSubsystemException` instead so that it can be caught and handled appropriately in `registerDeployedComponent()`?

</blockquote></details>

You are right that the wrong exception was being thrown.  If I were to just change the exception being thrown, registerDeployedComponent would call `removeComponentService.deleteCustomPipelines(model, true);` and re-throw the exception, so it would still stop the application context from starting. `StartupComponentRegistrationServiceImpl`stops registering components after the first failure, so I think it might be better to just log an error here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/342)*

**Comment by jrobble** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/util/JsonDropLeadingUnderscore.java, line 1 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/342#-KzQPOI8GHhJs0VOcVyO:-KzQPOI8GHhJs0VOcVyP:b-r09svn) ([raw file](https://github.com/openmpf/openmpf/blob/45d76bb34d9271b61ebfe36e832d80f93214a2fa/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/util/JsonDropLeadingUnderscore.java#L1)):*
> ```Java
> package org.mitre.mpf.mvc.util;
> ```

Add header comments, please.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceModel.java, line 39 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0nt7fC_RXxJdLows_:-KzQIfIlnRTP6OkHifHr:btumvfz) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/StreamingServiceModel.java#L39)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I prefer the underscore naming convention. It very easy to forget a `this.` and assign to the wrong variable. Also, `_` is shorter than `this.` When I originally wrote AddComponentServiceImpl it used the underscore naming convention, but at some point it was changed to not use underscores. 
I was originally considering making the fields of this class public final since the getters don't really do anything. I decided to use getters and forgot to rename the fields. 
</blockquote></details>

I think I may have reverted `AddComponentServiceImpl` back to not using underscores for consistency. The use of underscores in the `org.mitre.mpf.wfm.service` package is mixed. Let's not worry about it for now.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 515 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/342#-Kz0poqs4cGxyXgiuXCz:-KzQOqTi5SMH-L1eIhOY:btd51a6) ([raw file](https://github.com/openmpf/openmpf/blob/f353a28dfbabed3a0cb82b5e7ac2db167048d35e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L515)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

You are right that the wrong exception was being thrown.  If I were to just change the exception being thrown, registerDeployedComponent would call `removeComponentService.deleteCustomPipelines(model, true);` and re-throw the exception, so it would still stop the application context from starting. `StartupComponentRegistrationServiceImpl`stops registering components after the first failure, so I think it might be better to just log an error here.
</blockquote></details>

I agree.

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestStreamingServiceManager.java, line 127 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/342#-KzQP6DIWaWyMHjhudRi:-KzQP6DIWaWyMHjhudRj:b54go1d) ([raw file](https://github.com/openmpf/openmpf/blob/45d76bb34d9271b61ebfe36e832d80f93214a2fa/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestStreamingServiceManager.java#L127)):*
> ```Java
> 
> 		Files.lines(_mockProperties.getStreamingServices().getFile().toPath())
> 				.forEach(System.out::println);
> ```

Is this debug that can be removed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/342)*

**Comment by brosenberg42** [comment]
Review status: 13 of 15 files reviewed at latest revision, 2 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/util/JsonDropLeadingUnderscore.java, line 1 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/342#-KzQPOI8GHhJs0VOcVyO:-KzTeC92DUFoumJ111_d:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/45d76bb34d9271b61ebfe36e832d80f93214a2fa/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/util/JsonDropLeadingUnderscore.java#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add header comments, please.
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestStreamingServiceManager.java, line 127 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/342#-KzQP6DIWaWyMHjhudRi:-KzTe9NzOGRH5Drw1hHF:bb77ufg) ([raw file](https://github.com/openmpf/openmpf/blob/45d76bb34d9271b61ebfe36e832d80f93214a2fa/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/service/TestStreamingServiceManager.java#L127)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this debug that can be removed?
</blockquote></details>

Yes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/342)*

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/342)*

**Pull request merged**
