### PR TITLE
added removal of zero size detections to DetectionPaddingProcessor

### PR DESCRIPTION
**Pull request by clnowacki**
**Issues:**

- https://github.com/openmpf/openmpf/issues/1337
- https://github.com/openmpf/openmpf/issues/1353
- https://github.com/openmpf/openmpf/issues/1256
- https://github.com/openmpf/openmpf/issues/1362
- https://github.com/openmpf/openmpf/issues/1359

**Related PRs:**

- https://github.com/openmpf/openmpf-components/pull/260

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1352)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1352)* status: all files reviewed, 5 unresolved discussions (waiting on @clnowacki)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdIqxYs6A7fj4I9PsJL:-MdIqxYs6A7fj4I9PsJM:b1ghvt8) ([raw file](https://github.com/openmpf/openmpf/blob/eaebfa4503caaa0fae58563005f23cd4351ac3f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L59)):*
> ```Java
> import java.util.*;
> import java.util.function.Function;
> import java.util.stream.Collectors;
> ```

This import is not used.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 197 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdIrGge1vpf0XE61C3G:-MdIrGge1vpf0XE61C3H:b-4bqmwz) ([raw file](https://github.com/openmpf/openmpf/blob/eaebfa4503caaa0fae58563005f23cd4351ac3f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L197)):*
> ```Java
>             // We could end up here if speech detection is run on media of type VIDEO, and in that case, all detections
>             // in the track have size zero, so we need to simply pass these tracks through without filtering.
>             if (track.getType().equals("SPEECH")) {
> ```

Please handle `SOUND` in the same way as `SPEECH`. I didn't think of that before.

You mentioned that you want to tackle [this task](https://github.com/openmpf/openmpf/issues/1362) as part of this PR. Please make sure to update the "Issues:" part of the PR description to include it.

---

You could optimize this to only check the type of the first track because all of the tracks have the same type.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 203 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdItg481X5EDJnG8hzT:-MdItg49CrXIZct1LgRI:bl1qr9z) ([raw file](https://github.com/openmpf/openmpf/blob/eaebfa4503caaa0fae58563005f23cd4351ac3f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L203)):*
> ```Java
>             SortedSet<Detection> goodDetections = new TreeSet<>();
>             for (Detection detection : track.getDetections()) {
>                 if (detection.getWidth() == 0 && detection.getHeight() == 0) {
> ```

I think you want to use the "or" operator instead of the "and" operator here since a 0 width or height would result in capturing 0 pixels, which is what messes up components downstream.

Also, we should check if the bounding box is completely out of frame. If so, that would also result in capturing 0 pixels and lead to problems. 

I ran a test with MPFVideoCapture with these properties:

```
                      {"SEARCH_REGION_ENABLE_DETECTION", "true"},
                      {"SEARCH_REGION_TOP_LEFT_X_DETECTION", "-200"},
                      {"SEARCH_REGION_TOP_LEFT_Y_DETECTION", "-200"},
                      {"SEARCH_REGION_BOTTOM_RIGHT_X_DETECTION", "-100"},
                      {"SEARCH_REGION_BOTTOM_RIGHT_Y_DETECTION", "-100"} },
```

It returned the full frame. I don't think we want to rely on this behavior, so we should check in the WFM ahead of time. Otherwise we could be hiding issues.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 211 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdIxCPs4UecLSfZ0fiJ:-MdIxCPt6s-1QQzmBaU8:b-atx3gt) ([raw file](https://github.com/openmpf/openmpf/blob/eaebfa4503caaa0fae58563005f23cd4351ac3f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L211)):*
> ```Java
>             if (goodDetections.size() > 0) {
>                 // This is needed because image "tracks" do not respect the "inclusiveness" of the stop frame:
>                 // an image track has start frame 0 and end frame 1, for no apparent reason.
> ```

The user said we can fix the issue so that images start and stop at frame 0. Just making a note that we decided to do that in a separate PR because of the number of changes to the system tests it would require. 

For future reference [this is the task](https://github.com/openmpf/openmpf/issues/1359).
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 238 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdJax7D1H--gzHgcywm:-MdJax7ECxkLUpC47SOD:b-jbbwl7) ([raw file](https://github.com/openmpf/openmpf/blob/eaebfa4503caaa0fae58563005f23cd4351ac3f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L238)):*
> ```Java
> 
>         if (zeroSizeFramesString.isPresent()) {
>             _log.warn(String.format("Dropped one or more detection regions for job id %s with zero width and height. " +
> ```

As discussed, please generate a job warning that shows up in the JSON output object.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1352)* status: 0 of 36 files reviewed, 4 unresolved discussions (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdIqxYs6A7fj4I9PsJL:-MeAOaI4CbJVqURkh6AR:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f749d4cf1cccffcb8fc699eb5059baba6f3bef3c/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This import is not used.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 197 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdIrGge1vpf0XE61C3G:-MeVbVVRET7S8uVm4RZ0:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f749d4cf1cccffcb8fc699eb5059baba6f3bef3c/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L197)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please handle `SOUND` in the same way as `SPEECH`. I didn't think of that before.

You mentioned that you want to tackle [this task](https://github.com/openmpf/openmpf/issues/1362) as part of this PR. Please make sure to update the "Issues:" part of the PR description to include it.

---

You could optimize this to only check the type of the first track because all of the tracks have the same type.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 203 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdItg481X5EDJnG8hzT:-MeRRu349tneHurgPqEU:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f749d4cf1cccffcb8fc699eb5059baba6f3bef3c/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L203)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think you want to use the "or" operator instead of the "and" operator here since a 0 width or height would result in capturing 0 pixels, which is what messes up components downstream.

Also, we should check if the bounding box is completely out of frame. If so, that would also result in capturing 0 pixels and lead to problems. 

I ran a test with MPFVideoCapture with these properties:

```
                      {"SEARCH_REGION_ENABLE_DETECTION", "true"},
                      {"SEARCH_REGION_TOP_LEFT_X_DETECTION", "-200"},
                      {"SEARCH_REGION_TOP_LEFT_Y_DETECTION", "-200"},
                      {"SEARCH_REGION_BOTTOM_RIGHT_X_DETECTION", "-100"},
                      {"SEARCH_REGION_BOTTOM_RIGHT_Y_DETECTION", "-100"} },
```

It returned the full frame. I don't think we want to rely on this behavior, so we should check in the WFM ahead of time. Otherwise we could be hiding issues.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 211 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdIxCPs4UecLSfZ0fiJ:-MeRRvw96sI-z0VPyQig:b-7rl0jd) ([raw file](https://github.com/openmpf/openmpf/blob/f749d4cf1cccffcb8fc699eb5059baba6f3bef3c/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L211)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The user said we can fix the issue so that images start and stop at frame 0. Just making a note that we decided to do that in a separate PR because of the number of changes to the system tests it would require. 

For future reference [this is the task](https://github.com/openmpf/openmpf/issues/1359).
</blockquote></details>

done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 238 at r1](https://reviewable.io/reviews/openmpf/openmpf/1352#-MdJax7D1H--gzHgcywm:-MeRS-I8C9G6IAmrOId1:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/f749d4cf1cccffcb8fc699eb5059baba6f3bef3c/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L238)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, please generate a job warning that shows up in the JSON output object.
</blockquote></details>

Done.

**Comment by jrobble** [comment]
I haven't review this yet, but I realized it's related to https://github.com/openmpf/openmpf/issues/1256.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 10 of 13 files at r3, 24 of 25 files at r4, 2 of 2 files at r5, 10 of 10 files at r6.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1352)* status: all files reviewed, 6 unresolved discussions (waiting on @clnowacki)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mf-5vB3C7XLaib8DQ_g:-Mekni7v1cIf4PKGxzt8:b-tydqda) (no related file):*
What do you think about renaming `DetectionPaddingProcessor` to `DetectionTransformationProcessor` to be more generic?

The stuff you added falls under "validation", but I think `DetectionValidationAndTransformationProcessor` is too verbose.

---
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 50 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MeeXJ8C1Mo1e-u0ZUCj:-MeeXJ8D4yd88PwF_xEx:b-9v8k91) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L50)):*
> ```Java
> import org.mitre.mpf.wfm.util.AggregateJobPropertiesUtil;
> import org.mitre.mpf.wfm.util.JsonUtils;
> import org.mitre.mpf.wfm.util.PropertiesUtil;
> ```

Not used. I fixed this in my updates.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 124 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefZGJp1N_TTZclU4mT:-MefZGJqD-lUHdvoF_85:b-8ag2oj) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L124)):*
> ```Java
> 
>                             processTracks(job.getId(), media.getId(), trackMergingContext.getTaskIndex(), actionIndex,
>                                     xPadding, yPadding, frameWidth, frameHeight, filteredTracks);
> ```

`filteredTracks` is only used here, which is only if padding is required. If padding is not required then we don't update the job with the `filteredTracks`. This means we would still be using the ill-formed detections.

 I fixed this in my updates.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 252 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MezwpgN67wj14iy_jH4:-MezwpgO99HIGkjBNrvM:b-rrvvkg) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L252)):*
> ```Java
>                     jobId, zeroSizeFramesString.get()));
>             _inProgressBatchJobs.addWarning(
>                     jobId, mediaId, IssueCodes.PADDING, String.format(
> ```

I think it's better to use a different error code for zero-size detections / detections that fall outside of the frame. Let's use `INVALID_DETECTION`.

 I did this in my updates.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java, line 317 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mef_qbD10UnDdNHShjh:-Mef_qbD10UnDdNHShji:b-q1ft2p) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/padding/DetectionPaddingProcessor.java#L317)):*
> ```Java
>                     "Shrunk one or more detection regions to nothing. " +
>                             "1-pixel detection regions used instead. %s", shrunkToNothingString.get()));
>             _inProgressBatchJobs.setTracks(jobId, mediaId, taskIndex, actionIndex, newTracks);
> ```

The job is only updated if `shrunkToNothingString.isPresent()`. We should be updating the tracks in the job even if that's not true. The detections in the track may have changed due to applying padding.

 I fixed this in my updates.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 302 at r6](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mf-4PYF8mAdIfodJZ1d:-Mf-4PYF8mAdIfodJZ1e:b-rpz6uw) ([raw file](https://github.com/openmpf/openmpf/blob/48dcd4c04152fb964ec1bc893705efe59cbfbda8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L302)):*
> ```Java
>         // NOTE: All tracks should be the same type.
>         switch (tracks.first().getType().toUpperCase()) {
>             case "SPEECH":
> ```

My changes now use a new system property for figuring out these types. I wanted to move away from all instances of hard-coding "SPEECH" in the WFM.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupSplitter.java, line 257 at r6](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mf-4dNv22P6J_jrxjld:-Mf-4dNv22P6J_jrxjle:b-jglqid) ([raw file](https://github.com/openmpf/openmpf/blob/48dcd4c04152fb964ec1bc893705efe59cbfbda8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupSplitter.java#L257)):*
> ```Java
> 
>             String objectType = track.getType();
>             if ("SPEECH".equalsIgnoreCase(objectType) || "AUDIO".equalsIgnoreCase(objectType)) {
> ```

I reused your system property here.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/AggregateJobPropertiesUtil.java, line 434 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mefdnll5JhfKLv_JA0a:-Mefdnll5JhfKLv_JA0b:blxostn) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/AggregateJobPropertiesUtil.java#L434)):*
> ```Java
>     }
> 
>     public boolean isOutputLastTaskOnly(Media media, BatchJob job) {
> ```

This is not used, so I removed it.
___
*[trunk/workflow-manager/src/main/resources/properties/mpf.properties, line 103 at r6](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mf-4uhn4AYDysFd5NCY:-Mf-4uho2h2kq2dLyFds:b98eqxh) ([raw file](https://github.com/openmpf/openmpf/blob/3f1edfcf74f8b85a808c3bd95dc18fb59f15514c/trunk/workflow-manager/src/main/resources/properties/mpf.properties#L103)):*
> ```INI
> # Definition of which data types are to be exempt from removal of ill-formed detections. These types do not normally
> # generate bounding boxes for detections.
> detection.illformed.detection.removal.exempt.types=SPEECH,SOUND
> ```

I renamed this by moving `exempt` to the end to be consistent with `detection.video.track.merging.exempt.types`. I wanted to preserve the prefix on the latter.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 289 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefmnBU3oW_7rOW2Xk3:-MefmnBU3oW_7rOW2Xk4:b-hw4t27) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L289)):*
> ```Java
> 
>     @Test
>     public void testRemoveZeroSizeDetectionsOneZeroDetection() {
> ```

Check that the correct detection was removed.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 316 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefmzS0-4C7dm7ojf1E:-MefmzS0-4C7dm7ojf1F:b-hw4t27) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L316)):*
> ```Java
> 
>     @Test
>     public void testRemoveOutsideFrameDetectionsOneDetection() {
> ```

Check that the correct detection was removed.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 370 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefnB0X09tr70cpjF8W:-MefnB0X09tr70cpjF8X:b-pt0ly5) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L370)):*
> ```Java
> 
>     @Test
>     public void testRemoveIllFormedDetectionsOneOfEach() {
> ```

Check that the correct detections were removed / remain.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 427 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefnW2D9admnnD4VLEA:-MefnW2D9admnnD4VLEB:b-w4ts7i) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L427)):*
> ```Java
>     public void testRemoveZeroSizeDetectionsSingleDetectionTrack() {
>         SortedSet<Detection> detections = new TreeSet<>();
>         Detection detection1 = new Detection(50, 60, 0, 0, 1, 1, 1, Collections.emptyMap());
> ```

Test the case where only height or width is 0, not both. This can be combined with another test if you want.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 442 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mefnv6g95GklDex5gwp:-Mefnv6g95GklDex5gwq:b-hw4t27) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L442)):*
> ```Java
> 
>     @Test
>     public void testRemoveZeroSizeDetectionsOneZeroDetectionAtEnd() {
> ```

Check that the correct detection was removed.

**Review by clnowacki — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1352)* status: 39 of 44 files reviewed, 6 unresolved discussions (waiting on @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mf-5vB3C7XLaib8DQ_g:-Mf4ZpbXCM8xfdiA_VYw:bb3c15n) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What do you think about renaming `DetectionPaddingProcessor` to `DetectionTransformationProcessor` to be more generic?

The stuff you added falls under "validation", but I think `DetectionValidationAndTransformationProcessor` is too verbose.
</blockquote></details>

Changing to DetectionTransformationProcessor

---
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 289 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefmnBU3oW_7rOW2Xk3:-Mf4KXer8Cnm-qeAsO7c:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L289)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check that the correct detection was removed.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 316 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefmzS0-4C7dm7ojf1E:-Mf4KZ-L49jPF5avIVTV:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L316)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check that the correct detection was removed.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 370 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefnB0X09tr70cpjF8W:-Mf4K_BGD8qJ0aAbMLAg:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L370)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check that the correct detections were removed / remain.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 427 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-MefnW2D9admnnD4VLEA:-Mf4QGjRCpXPCk1yrk0Y:b-r91368) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L427)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Test the case where only height or width is 0, not both. This can be combined with another test if you want.
</blockquote></details>

Modified testRemoveZeroSizeDetectionsOneZeroDetectionAtEnd to cover this.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java, line 442 at r5](https://reviewable.io/reviews/openmpf/openmpf/1352#-Mefnv6g95GklDex5gwp:-Mf4QapY72gNIODNTn1J:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e6ccbcdba73180bbab5e3aea0b2485cc73388691/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionPaddingProcessor.java#L442)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check that the correct detection was removed.
</blockquote></details>

Done.

**Pull request merged**
