### PR TITLE
Update configuration files to support docker deployments

### PR DESCRIPTION
**Pull request by bquinn17**
Update configuration files to support docker deployments while upholding backwards compatibility.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/627)

### CODE REVIEW

**Comment by jrobble** [comment]
Your update-config-docker branch is not up to date with the develop branch. It seems like your branch is based off master. Please create a new feature branch off of develop, update it with your changes, and create a new PR with that one.

I noticed this while looking at openmpf/trunk/mpf-install/src/main/scripts/mpf-profile.sh. I saw:

```
export ALL_MPF_NODES=$THIS_MPF_NODE[7800]
```

`ALL_MPF_NODES` has been completed removed and replaced with `CORE_MPF_NODES`.

Please start using the develop branches and get your container running those. 

---

Review status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @bquinn17 and @jrobble)

---

*[trunk/workflow-manager/src/main/resources/properties/mpf.properties, line 32 at r1](https://reviewable.io/reviews/openmpf/openmpf/627#-LGAyHsQAtY5UfhT3HAM:-LGAyHsQAtY5UfhT3HAN:bkd8zcg) ([raw file](https://github.com/openmpf/openmpf/blob/85f12f488cd298b292ddde77d392684bfed16f8f/trunk/workflow-manager/src/main/resources/properties/mpf.properties#L32)):*
> ```INI
> 
> output.site.name=mpf1
> mpf.output.objects.activemq.hostname=${env:ACTIVE_MQ_HOST}
> ```

Notice here that `ACTIVE_MQ_HOST` is prefaced with `env:`. You will need to preface your new env. variables with`env:` in this file as well. In Release 2.1.0 we started using the Apache Commons Configuration library, which requires that prefix. You've been using the master branches, which still use Spring to read the properties files.

Note that jGroupsTCPConfig.xml doesn't use that prefix for env. variables because that file is not parsed by the Apache Commons Configuration library; it's parsed by JGroups. Also, all of the application context files are still parsed by Spring, so the way you use `REDIS_HOST` in the other file should be fine.

I don't think the `${SOME_ENV_VAR:some_default_value}` syntax is valid when using the Apache Commons Configuration library. The colon character seems reserved for separating the prefix, such as `env:`, from the property name that needs to be interpolated.

So where you have:

`jmx.amq.broker.uri=service:jmx:rmi:///jndi/rmi://${AMQ_HOST:localhost}:1099/jmxrmi`

I think you're going to have to change that to:

`jmx.amq.broker.uri=service:jmx:rmi:///jndi/rmi://${env:AMQ_HOST}:1099/jmxrmi`

And where you have:

`jdbc.url=jdbc:simon:mysql://${MYSQL_HOST:localhost}:3306/mpf`

You're going to have to change that to:

`jdbc.url=jdbc:simon:mysql://${env:MYSQL_HOST}:3306/mpf`

Because we can no longer specify a default value (I think), we're going to have to make sure that the values for `AMQ_HOST` and `MYSQL_HOST` are specified in the mpf.sh file. Even if we could specify a default value using the new syntax, all of the env. variables should be specified in mpf.sh for completeness and consistency. Thus, you should include `AMQ_HOST`, `MYSQL_HOST`, and `REDIS_HOST` in the mpf.sh file and other files that set env. variables.

Here are the files that you need to add your new env. variables to:

- openmpf/trunk/mpf-install/src/main/scripts/mpf-profile.sh
- openmpf/trunk/ansible/install/ansible/roles/master/templates/mpf-profile.sh.j2
- openmpf/trunk/jenkins/scripts/MPF/Jenkins.pm

For the latter file, it's this part:

```
	my $mpfsh = << "END_MPF_SH";
export MPF_USER="$mpfUser"
export MPF_HOME="$mpfPath/trunk/install"
export MPF_LOG_PATH="$mpfLogPath"
export MASTER_MPF_NODE="$hostname"
export THIS_MPF_NODE="$hostname"
export CORE_MPF_NODES="\$THIS_MPF_NODE"
export JAVA_HOME="/usr/java/latest"
export JGROUPS_TCP_ADDRESS="\$THIS_MPF_NODE"
export JGROUPS_TCP_PORT=7800
export JGROUPS_FILE_PING_LOCATION="\$MPF_HOME/share/nodes"
# CATALINA_OPTS is set in <TOMCAT_HOME>/bin/setenv.sh
export ACTIVE_MQ_HOST="failover://(tcp://\$MASTER_MPF_NODE:61616)?jms.prefetchPolicy.all=1&startupMaxReconnectAttempts=1"
export LD_LIBRARY_PATH="/usr/local/lib"
END_MPF_SH
```

And this part:

```
	my @vars = ("MPF_USER", "MPF_HOME", "MPF_LOG_PATH", "MASTER_MPF_NODE", "THIS_MPF_NODE", "CORE_MPF_NODES", "JAVA_HOME",
	    "JGROUPS_TCP_ADDRESS", "JGROUPS_TCP_PORT", "JGROUPS_FILE_PING_LOCATION", "ACTIVE_MQ_HOST", "LD_LIBRARY_PATH");
```

In all cases, you should set your env. variables to `$MASTER_MPF_NODE`.

Let's rename your `AMQ_HOST` env. variable to `ACTIVE_MQ_HOST` for naming consistency.

Also, related to what we discussed yesterday, everywhere the current code is using `ACTIVE_MQ_HOST`, that should be changed to `ACTIVE_MQ_BROKER_URI`. You should be able to do a find + replace on the openmpf repo code, for the most part. `ACTIVE_MQ_BROKER_URI` should be defined using your new `ACTIVE_MQ_HOST` env. variable instead of `MASTER_NODE`.  `ACTIVE_MQ_HOST` should be set to the value of `MASTER_NODE` anyway, so the end result is the same, but that way it will keep things more sane in the off chance someone wants to change `ACTIVE_MQ_HOST` to something other than the master node (for a non-Docker deployment).

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/627#-:-LGAxQvC6j6lSW9DjLif:bitbk6p)*

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed, 1 unresolved discussion (waiting on @bquinn17)

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/627)*

**Comment by bquinn17** [comment]
@jrobble All of the changes have been updated and everything is looking good on the docker side. Instead of using default values for the environment variables, new ones have been added to all of the scripts that set env vars, as per your suggestion. The environment variables are then updated by the dockerfile for docker deployments.

**Comment by jrobble** [comment]
I've been out of the loop. Should I go ahead and review this now?

**Comment by bquinn17** [comment]
@jrobble yes if you could review it that would be great. I've been using this branch in the Docker builds, so everything is good on that side.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/resources/properties/mpf.properties, line 32 at r4](https://reviewable.io/reviews/openmpf/openmpf/627#-LHtGkKU-bNMKJ_eb6j3:-LHtKYda4hrWvzNXqJ6I:bx9epdd) ([raw file](https://github.com/openmpf/openmpf/blob/ac8c591e2d516c953574bf16ac412bb83da822b1/trunk/workflow-manager/src/main/resources/properties/mpf.properties#L32)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

The name of this property, and all of the code that defines variables using this property, are misleading. The property should really be `mpf.output.objects.amq.broker.uri`. The code should be referring to is as the ActiveMQ broker URI, not the ActiveMQ host.
</blockquote></details>

Specifically, `MasterNode.loadConfigFile()` uses the `activeMqHostname` parameter.

**Pull request merged**
