### PR TITLE
Updated runDetectMarkupMultipleMediaTypes.json to capture additional …

### PR DESCRIPTION
**Pull request by jrobble**
…detections.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/216)

### CODE REVIEW

**Comment by jrobble** [comment]
This PR addresses [this change](https://github.com/openmpf/openmpf-components/commit/e88297a8da363da0ea93514926250275b06a8157#diff-895039859e521ed78593fc7e4f99b5dbR949).

**Comment by jrobble** [comment]
Currently running openmpf-nightly build # 108.

**Comment by jrobble** [comment]
Currently running openmpf-nightly build # 111.

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: 1 of 2 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/216#-:-KrkTTgk8BdCxJHDVb1L:bnfp4nl)*

**Pull request merged**
