### PR TITLE
Pass all algo props to components

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/85)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 288 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl-IWNWhIt-5WjcoUYh:-Kl-IWNWhIt-5WjcoUYi:b-8grvas) ([raw file](https://github.com/openmpf/openmpf/blob/13a993aa30a5105abb4ed19fe6c2ec3a92602c97/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L288)):*
> ```Java
> 		Rectangle rectangle2 = new Rectangle(second.getX(), second.getY(), second.getWidth(), second.getHeight());
> 
> 		if (rectangle1.getWidth() == 0 || rectangle2.getWidth() == 0 || rectangle1.getHeight() == 0 || rectangle1.getHeight() == 0) {
> ```

This expression doesn't include `rectangle2.getHeight()`, but it checks rectange1's height twice.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 288 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl-IWNWhIt-5WjcoUYh:-Kl-ShsBwynwBfCMl7TB:b-9nd34g) ([raw file](https://github.com/openmpf/openmpf/blob/13a993aa30a5105abb4ed19fe6c2ec3a92602c97/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L288)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This expression doesn't include `rectangle2.getHeight()`, but it checks rectange1's height twice.
</blockquote></details>

Great find!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by brosenberg42** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 288 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl-IWNWhIt-5WjcoUYh:-Kl-VoJWSttkud3SJ3A7:be8add5) ([raw file](https://github.com/openmpf/openmpf/blob/13a993aa30a5105abb4ed19fe6c2ec3a92602c97/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L288)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Great find!
</blockquote></details>

I didn't find it.


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 288 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl-IWNWhIt-5WjcoUYh:-Kl-ehO0lLXUqQWeiYhh:bquwe6b) ([raw file](https://github.com/openmpf/openmpf/blob/13a993aa30a5105abb4ed19fe6c2ec3a92602c97/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L288)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I didn't find it.


</blockquote></details>

IntelliJ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by brosenberg42** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 288 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl-IWNWhIt-5WjcoUYh:-Kl-h3MXWuBHSfbYWomv:b-dqwf0z) ([raw file](https://github.com/openmpf/openmpf/blob/13a993aa30a5105abb4ed19fe6c2ec3a92602c97/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L288)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

IntelliJ?
</blockquote></details>

Yea, I have some of the more strict inspections enabled.
The reason this bug never caused any issues is that if any of the dimensions of the rectangles is 0, then there no intersection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by brosenberg42** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 286 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl-i-QPW6gIcCLjS7kk:-Kl-i-QPW6gIcCLjS7kl:b55n1gb) ([raw file](https://github.com/openmpf/openmpf/blob/f0bc4a2002a3cc745779f44143f9e345b9418ac5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L286)):*
> ```Java
> 
> 		Detection first = (track1End.getMediaOffsetFrame() < track2Start.getMediaOffsetFrame()) ? track1End : track2Start;
> 		Detection second = (first == track1End) ? track2Start : track1End;
> ```

I don't understand why this is necessary. The operations being performed on the rectangles are commutative

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 286 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl-i-QPW6gIcCLjS7kk:-Kl-q-jkZwgkbWRNzHop:bq2pgdc) ([raw file](https://github.com/openmpf/openmpf/blob/f0bc4a2002a3cc745779f44143f9e345b9418ac5/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L286)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I don't understand why this is necessary. The operations being performed on the rectangles are commutative
</blockquote></details>

I can see how this might be useful for live debugging. Truth is though, the ordering is unnecessary because this is always enforced:

`merged.getEndOffsetFrameInclusive() < candidate.getStartOffsetFrameInclusive()`

Track1 will always be first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by brosenberg42** [comment]
Reviewed 5 of 5 files at r1, 10 of 10 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java, line 200 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/85#-Kl3zY5_WSEGx3Dy8aqV:-Kl3zY5_WSEGx3Dy8aqW:b-w2qgag) ([raw file](https://github.com/openmpf/openmpf/blob/a353c1b0d59fcd4d2a6ed3dc5264e9d2e7c10798/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/trackmerging/TrackMergingProcessor.java#L200)):*
> ```Java
> 			try {
> 				minTrackLength = Integer.valueOf(minTrackLengthProperty);
> 			} catch (Exception exception) {
> ```

These should be catching NumberFormatException

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r4.
Review status: 14 of 16 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Comment by brosenberg42** [comment]
Reviewed 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/85)*

**Pull request merged**
