### PR TITLE
Add support for ROTATION_THRESHOLD and ROTATION_FILL_COLOR

### PR DESCRIPTION
**Pull request by brosenberg42**
Resolves https://github.com/openmpf/openmpf/issues/1194
Resolves https://github.com/openmpf/openmpf/issues/1196

Associated PRs:
- https://github.com/openmpf/openmpf/pull/1195
- https://github.com/openmpf/openmpf-components/pull/203
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/93
- https://github.com/openmpf/openmpf-python-component-sdk/pull/33

This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1195)

### CODE REVIEW

**Review by jrobble — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1195)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by jrobble — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1195)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[trunk/video-overlay/src/main/cpp/FrameExtractor.cpp, line 195 at r2](https://reviewable.io/reviews/openmpf/openmpf/1195#-MLjkXgF4PyV2R9UJkGs:-MLjkXgG4dIKvJAeza7O:b-3lqwqe) ([raw file](https://github.com/openmpf/openmpf/blob/5a482e83f29c513e09ee0626eda5625adcee5a93/trunk/video-overlay/src/main/cpp/FrameExtractor.cpp#L195)):*
> ```cpp
>                     // Create the transformation for this frame and apply it.
>                     FeedForwardExactRegionAffineTransformer transformer(
>                             { MPFRotatedRect(x, y, width, height, rotation, false) }, {0, 0, 0},
> ```

I use the EAST extracted artifacts to determine what is being sent via feed-forward to Tesseract. I think we should use the pixel fill color here instead of black. The user may expect the pixel fill color to be used in the generated artifacts.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1195)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[trunk/video-overlay/src/main/cpp/FrameExtractor.cpp, line 195 at r2](https://reviewable.io/reviews/openmpf/openmpf/1195#-MLjkXgF4PyV2R9UJkGs:-MLmeyC_4HxWxl6iBDcE:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/5a482e83f29c513e09ee0626eda5625adcee5a93/trunk/video-overlay/src/main/cpp/FrameExtractor.cpp#L195)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I use the EAST extracted artifacts to determine what is being sent via feed-forward to Tesseract. I think we should use the pixel fill color here instead of black. The user may expect the pixel fill color to be used in the generated artifacts.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1195)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
