### PR TITLE
Add support for linked media

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1650

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1673)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
Why can't they all be this simple? :)

Please update the TiesDb Guide to mention how the `LINKED_MEDIA_HASH` property can be used.

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1673#-:-NTPvcUs7nniHGFtiT9x:bp1zg2j)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 243 at r1](https://reviewable.io/reviews/openmpf/openmpf/1673#-NTQ2Ex6BE02JH1hoiyi:-NTQ2Ex72tOZoZc2Hrkh:blwk8iu) ([raw file](https://github.com/openmpf/openmpf/blob/670a4cf4a7ea97420e53da2516555c9a7139d225/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L243)):*
> ```Java
>     @Override
>     @JsonIgnore
>     public Optional<String> getLinkedHash() {
> ```

I ran a job with S3 copy enabled. It found a record in TiesDb. This is the JSON output:

```json
   "media": [
      {
         "mediaId": 17,
         "parentMediaId": -1,
         "path": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/at3_1m4_01.tif",
         "sha256": "820258067d4211af126d2852f444e0d84bf78696ccffe1869f71236ef035fc72",
         "mimeType": "image/jpeg",
         "mediaType": "IMAGE",
         "length": 1,
         "frameRanges": [],
         "timeRanges": [],
         "mediaMetadata": {
            "EXIF_ORIENTATION": "1",
            "FRAME_HEIGHT": "360",
            "FRAME_WIDTH": "480",
            "HORIZONTAL_FLIP": "FALSE",
            "MIME_TYPE": "image/jpeg",
            "ROTATION": "0"
         },
         "mediaProperties": {
            "LINKED_MEDIA_HASH": "820258067d4211af126d2852f444e0d84bf78696ccffe1869f71236ef035fc72"
         },
```

The `path` shows the image for the most recent job I submitted, but all of the other information in the `media` section, minus `mediaProperties`, is for the image associated with the original job.

I think that `path` should refer to the original media path.

---

Something similar happens when creating a job using a non-existent (bogus) media file in S3. A user can provide a `MEDIA_HASH` that corresponds to valid piece of media that has a record in TiesDb, a `MIME_TYPE` with a valid prefix like `image/wow`, and a bogus `mediaUri`, and the job will complete.

In that case the `media` section in the JSON will use the bogus `mediaUri` but use the rest of the info for the media in the original job.

I'm not saying this is a problem. I just wanted to point it out. If the user does something like that they should expect strange results.

The difference between this bogus media case and the "LINKED_MEDIA_HASH" one I explained above is that in the above case the media in the second job is understandably a different piece of media than in the original job, whereas in the bogus media case it's supposed to the same piece of media.

**Comment by jrobble** [comment]
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 243 at r1](https://reviewable.io/reviews/openmpf/openmpf/1673#-NTQ2Ex6BE02JH1hoiyi:-NTR7RerEw8gPQqQCecB:b-t77b0x) ([raw file](https://github.com/openmpf/openmpf/blob/670a4cf4a7ea97420e53da2516555c9a7139d225/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L243)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I ran a job with S3 copy enabled. It found a record in TiesDb. This is the JSON output:

```json
   "media": [
      {
         "mediaId": 17,
         "parentMediaId": -1,
         "path": "file:///home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/at3_1m4_01.tif",
         "sha256": "820258067d4211af126d2852f444e0d84bf78696ccffe1869f71236ef035fc72",
         "mimeType": "image/jpeg",
         "mediaType": "IMAGE",
         "length": 1,
         "frameRanges": [],
         "timeRanges": [],
         "mediaMetadata": {
            "EXIF_ORIENTATION": "1",
            "FRAME_HEIGHT": "360",
            "FRAME_WIDTH": "480",
            "HORIZONTAL_FLIP": "FALSE",
            "MIME_TYPE": "image/jpeg",
            "ROTATION": "0"
         },
         "mediaProperties": {
            "LINKED_MEDIA_HASH": "820258067d4211af126d2852f444e0d84bf78696ccffe1869f71236ef035fc72"
         },
```

The `path` shows the image for the most recent job I submitted, but all of the other information in the `media` section, minus `mediaProperties`, is for the image associated with the original job.

I think that `path` should refer to the original media path.

---

Something similar happens when creating a job using a non-existent (bogus) media file in S3. A user can provide a `MEDIA_HASH` that corresponds to valid piece of media that has a record in TiesDb, a `MIME_TYPE` with a valid prefix like `image/wow`, and a bogus `mediaUri`, and the job will complete.

In that case the `media` section in the JSON will use the bogus `mediaUri` but use the rest of the info for the media in the original job.

I'm not saying this is a problem. I just wanted to point it out. If the user does something like that they should expect strange results.

The difference between this bogus media case and the "LINKED_MEDIA_HASH" one I explained above is that in the above case the media in the second job is understandably a different piece of media than in the original job, whereas in the bogus media case it's supposed to the same piece of media.

</blockquote></details>

TBH, I'm not sure what the best thing to do is for the "LINKED_MEDIA_HASH" case. A few thoughts:

- `path` seems like it should refer to the media described by the other info in the `media` section.
- We want to include the path of the media associated with the new job somewhere in the JSON output, even if that media wasn't used for anything.

One idea is to include a new `jobRequestMediaPath` in the media section that refers to the media path associated with the job request whenever we decide to use a record in TiesDb. When we use a record we always populate `path` with the value of the media path used to generate the original JSON output in that record.

I like this approach because a user looking at the JSON will know exactly what media was used to generate the JSON regardless if "LINKED_MEDIA_HASH" was provided or "MEDIA_HASH" + "MIME_TYPE" metadata was provided.

**Comment by jrobble** [comment]
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 243 at r1](https://reviewable.io/reviews/openmpf/openmpf/1673#-NTQ2Ex6BE02JH1hoiyi:-NTREBgu9nik4yBk61JG:b-kumhw7) ([raw file](https://github.com/openmpf/openmpf/blob/670a4cf4a7ea97420e53da2516555c9a7139d225/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L243)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

TBH, I'm not sure what the best thing to do is for the "LINKED_MEDIA_HASH" case. A few thoughts:

- `path` seems like it should refer to the media described by the other info in the `media` section.
- We want to include the path of the media associated with the new job somewhere in the JSON output, even if that media wasn't used for anything.

One idea is to include a new `jobRequestMediaPath` in the media section that refers to the media path associated with the job request whenever we decide to use a record in TiesDb. When we use a record we always populate `path` with the value of the media path used to generate the original JSON output in that record.

I like this approach because a user looking at the JSON will know exactly what media was used to generate the JSON regardless if "LINKED_MEDIA_HASH" was provided or "MEDIA_HASH" + "MIME_TYPE" metadata was provided.



</blockquote></details>

Also, I'm wondering if we should call the property `TIES_DB_LINKED_MEDIA_HASH` because it only makes sense for TiesDb. Originally I was thinking it would be specified as media metadata, but now that you've made it a media property it seems like it should have the `TIES_DB_` prefix like the other properties.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1673)* status: all files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 243 at r1](https://reviewable.io/reviews/openmpf/openmpf/1673#-NTQ2Ex6BE02JH1hoiyi:-NTTHl7V95WR9Hotv-S-:bpil3rq) ([raw file](https://github.com/openmpf/openmpf/blob/670a4cf4a7ea97420e53da2516555c9a7139d225/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L243)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, I'm wondering if we should call the property `TIES_DB_LINKED_MEDIA_HASH` because it only makes sense for TiesDb. Originally I was thinking it would be specified as media metadata, but now that you've made it a media property it seems like it should have the `TIES_DB_` prefix like the other properties.
</blockquote></details>

I think `path` should always be the path the job was submitted with. If a job is submitted with multiple media entries, using the same path as the submission makes it easier to figure out which media object in the output is associated with the media input. When a user is providing the linked media hash, they are saying that the provided media and the linked media are interchangeable. Setting path to the value from TiesDb would be inconsistent with how the job id refers to the new job id.

Regarding the name of the property, I think keeping the name short in the job request is better, but it probably makes sense to rename this method.

**Comment by jrobble** [comment]
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java` line 243 at r1](https://reviewable.io/reviews/openmpf/openmpf/1673#-NTQ2Ex6BE02JH1hoiyi:-NTZT5HU55l-lZkkahu4:b-v21ygr) ([raw file](https://github.com/openmpf/openmpf/blob/670a4cf4a7ea97420e53da2516555c9a7139d225/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/MediaImpl.java#L243)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I think `path` should always be the path the job was submitted with. If a job is submitted with multiple media entries, using the same path as the submission makes it easier to figure out which media object in the output is associated with the media input. When a user is providing the linked media hash, they are saying that the provided media and the linked media are interchangeable. Setting path to the value from TiesDb would be inconsistent with how the job id refers to the new job id.

Regarding the name of the property, I think keeping the name short in the job request is better, but it probably makes sense to rename this method.
</blockquote></details>

As discussed, let's add a `tiesDbSourceMediaPath` underneath the `path` field in the media entry whenever we use a record from TiesDb. It will be consistent with the use of `tiesDbSourceJobId`.

Also, as discussed, let's continue using `LINKED_MEDIA_HASH` as the property name.

**Review by jrobble — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1673)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
