### PR TITLE
Add support for Python components

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)

### CODE REVIEW

**Comment by jrobble** [comment]
I see that the gtests passed on Jenkins.
Finished visual review. Next I will compile and run locally.

---

Reviewed 45 of 45 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[trunk/detection/executor/cpp/batch/CMakeLists.txt, line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBWviyuCYmY-QFxN531:-LBWviyuCYmY-QFxN532:b-l8fi9o) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/CMakeLists.txt#L59)):*
> ```CMake
> include_directories(${MPF_PROTO_PATH})
> 
> set(PYBIND11_CPP_STANDARD -std=c++11)
> ```

Since we’re including the pybind source directly in the openmpf repo, we need to mention pybind in the top-level LICENSE file, similar to what you did for the Darknet component LICENSE.

---

*[trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp, line 219 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBb6VZp52CQexu6FHhk:-LBb6VZp52CQexu6FHhl:b-9rcr5v) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp#L219)):*
> ```cpp
>         class ComponentApi {
>         private:
>             py::object image_job_;
> ```

Please add "_ctor_ to the end of these".

---

*[trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp, line 372 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBb10N5ETF2zARCkamH:-LBb10N5ETF2zARCkamI:beeiqiw) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp#L372)):*
> ```cpp
>         struct ComponentAttrs {
>             std::string detection_type;
>             py::function get_from_image_method;
> ```

Let's add "detection" between "get" and "from" in these names for clarity.

---

*[trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp, line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBX_cDjDMFll2MeHXi6:-LBX_cDl6HxN6ETC9GZc:b-jyo525) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp#L43)):*
> ```cpp
> PythonComponentHandle get_component(bool generic_only=false) {
>     static const log4cxx::LoggerPtr logger = getLogger();
>     if (generic_only) {
> ```

Instead of passing a parameter to this function, it would be cleaner if you just had `get_generic_only_component` do:

```
return PythonComponentHandle(getLogger(), "test_python_components/generic_only_component.py");
```

and change this function to:

```
return PythonComponentHandle(getLogger(), "test_python_components/test_component.py");
```

You can rename it to `get_test_component()`.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py, line 150 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXoJvW7a1yVjlx2Mf2:-LBXoJvY06cerfpOvM1G:b-xkjlu2) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py#L150)):*
> ```Python
>         logger.setLevel(logging.INFO)
>         handler = logging.FileHandler(util.get_full_log_path(log_file_name))
>     handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)-5s [%(filename)s:%(lineno)d] - %(message)s'))
> ```

Note to self: Check this format in log

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py, line 155 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXouab16jZKdQBZQvz:-LBXouab16jZKdQBZQw-:b-l92o5p) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py#L155)):*
> ```Python
> 
> 
> def result_struct_test():
> ```

Should this test be part of a Jenkins run / removed?

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api_util.py, line 253 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBX17yu53s7iSpzLJ2z:-LBX17yu53s7iSpzLJ3-:b-7s8x9z) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api_util.py#L253)):*
> ```Python
> #         },
> #     }
> #     logging.config.dictConfig(conf_dict)
> ```

Please remove this commented-out code.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py, line 56 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXEUS08jxq9WVreeY0:-LBXEUS08jxq9WVreeY1:b4c9lyr) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py#L56)):*
> ```Python
> 
>         # Make sure generators are acceptable return values
>         yield il
> ```

:thumbsup: 

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py, line 134 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXSgsf2N5lnY0yeCA5:-LBXSgsf2N5lnY0yeCA6:bcs7u6e) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py#L134)):*
> ```Python
>     logger.info('About to call get_detections_from_image')
>     results = list(tc.get_detections_from_image(job))
>     # results = list(tc.get_detections_from_video(job))
> ```

Please remove this comment.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550#-:-LBXcb7Y-SbP3Bp2KEhB:bjkgzvl)*

**Comment by jrobble** [comment]
*[trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp, line 372 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBb10N5ETF2zARCkamH:-LBbC2TB7nqSiazL0wmB:b-c8kgtz) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp#L372)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's add "detection" between "get" and "from" in these names for clarity.
</blockquote></details>

* detections

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by jrobble** [comment]
*[trunk/detection/executor/cpp/batch/CMakeLists.txt, line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBWviyuCYmY-QFxN531:-LBbTD0W2DMC_0cWIEuG:b-lmehes) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/CMakeLists.txt#L59)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Would it be better to put it in `openmpf-projects/openmpf/trunk/detection/executor/cpp/batch/pybind11/LICENSE`, or should I just append to https://github.com/openmpf/openmpf/blob/develop/LICENSE?
</blockquote></details>

I'd prefer that we add it to the top-level LICENSE file. At a glance, a developer is only going to look there and not dive into sub-directories. If the pybind code came with its own license file, we should include that in the pybind11 dir too.

Now that I think about it, we should be including the MIT license file in the darknet_lib directory of the darknet component too. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by brosenberg42** [comment]
Review status: 40 of 45 files reviewed at latest revision, 9 unresolved discussions.

---

*[trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp, line 219 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBb6VZp52CQexu6FHhk:-LBbPjYH2uibnvYf602t:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp#L219)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add "_ctor_ to the end of these".
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp, line 372 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBb10N5ETF2zARCkamH:-LBbQB4Q-FClY07LIVXH:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/PythonComponentHandle.cpp#L372)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

* detections
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp, line 43 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBX_cDjDMFll2MeHXi6:-LBbQCvADb4f8AlkV1xk:b-jqmv6m) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_batch_executor.cpp#L43)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of passing a parameter to this function, it would be cleaner if you just had `get_generic_only_component` do:

```
return PythonComponentHandle(getLogger(), "test_python_components/generic_only_component.py");
```

and change this function to:

```
return PythonComponentHandle(getLogger(), "test_python_components/test_component.py");
```

You can rename it to `get_test_component()`.
</blockquote></details>

I was originally doing that so that the logger only got initialized once. That is no longer necessary because I changed how the logger is initialized. 

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py, line 150 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXoJvW7a1yVjlx2Mf2:-LBbO0cD5Ws6JYyUMPyn:bywfpre) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py#L150)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note to self: Check this format in log
</blockquote></details>

For reference, https://github.com/openmpf/openmpf/blob/develop/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/util/tailer/FilteredMpfLogTailerListener.java#L126

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py, line 155 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXouab16jZKdQBZQvz:-LBbOAdS4KKJY2n9nVw8:b-ojnhtz) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py#L155)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Should this test be part of a Jenkins run / removed?
</blockquote></details>

Removed. This is from before test_component.py. All this is tested there.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api_util.py, line 253 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBX17yu53s7iSpzLJ2z:-LBbNX-p2EhfRVBNRrDz:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api_util.py#L253)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please remove this commented-out code.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py, line 134 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXSgsf2N5lnY0yeCA5:-LBbNjje9BgLWR7A4MPT:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py#L134)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please remove this comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by jrobble** [comment]
Reviewed 4 of 5 files at r2.
Review status: 44 of 45 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by jrobble** [comment]
Reviewed 1 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py, line 150 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBXoJvW7a1yVjlx2Mf2:-LBbp1-ODqR4mm_C0WgE:b-vs1pr4) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/test/test_python_components/mpf_component_api.py#L150)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

For reference, https://github.com/openmpf/openmpf/blob/develop/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/util/tailer/FilteredMpfLogTailerListener.java#L126
</blockquote></details>

Looks good.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by jrobble** [comment]
I submitted a job through Swagger with "echo_job" set as a job property. I saw this line in the log file:

```
2018-05-03 17:09:14,814 INFO  [test_component.py:43] - [Job 784:golden.jpg] Received image job: ImageJob(job_name=u'Job 784:golden.jpg', data_uri=u'/home/mpf/git/openmpf-projects/openmpf/trunk/install/share/remote-media/golden.jpg', job_properties={u'PROP3': u'string property', u'PROP1': u'2', u'PROP2': u'true', u'ECHO_JOB': u'test'}, media_properties={}, feed_forward_location=None)
```

Note how "echo_job" became "ECHO_JOB". Because of this difference, I did not see the value echoed in the output object:

```
 "detectionProperties": { 
    "METADATA": "extra info for first result", 
    "echo_job": "echo_job not present", 
    "echo_media": "echo_media not present" 
},
```

Please change all of your properties to use all caps.

---

The `detection_type` in each Python class should be in all caps too, since that is how it will show up in the output object. Separate words with spaces. We have precedent for that with "NO TRACKS".

---

I saw this in the detection.log:

> 2018-05-03 17:40:05,152 WARN [0x7f11f45e97c0] org.mitre.mpf.detection:425 - [Job 790:ffserver.conf] The detection component does not support detection data_type of 0

Please have that output the name of the data type, rather than the number value.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py, line 104 at r2](https://reviewable.io/reviews/openmpf/openmpf/550#-LBbuCnK8rouGw2zpjQd:-LBbuCnK8rouGw2zpjQe:b-tn6pnq) ([raw file](https://github.com/openmpf/openmpf/blob/931cc92353755910fa79ff6c7abf21f80c012f5f/trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py#L104)):*
> ```Python
>         if audio_job.feed_forward_track is not None:
>             return audio_job.feed_forward_track,
>         media_middle_time = (audio_job.stop_time + audio_job.start_time) / 2
> ```

Audio files aren't segmented. In my tests, the stop time was always -1, signifying the whole audio file. Thus, this middle time calculation didn't work as intended.

Note that the Sphinx component [checks for this](https://github.com/openmpf/openmpf-components/blob/develop/java/SphinxSpeechDetection/src/main/java/org/mitre/mpf/detection/sphinx/speech/SphinxSpeechDetectionComponent.java#L81).

You should check for it too, use the DURATION media property to do your calculation, or just hardcode something.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550#-:-LBbq_N05wA2KZXlG5ne:blcetwm)*

**Comment by jrobble** [comment]
*[trunk/detection/executor/cpp/batch/main.cpp, line 142 at r2](https://reviewable.io/reviews/openmpf/openmpf/550#-LBfc6apC-5OXCvXDG1q:-LBfc6apC-5OXCvXDG1r:b86n8yt) ([raw file](https://github.com/openmpf/openmpf/blob/931cc92353755910fa79ff6c7abf21f80c012f5f/trunk/detection/executor/cpp/batch/main.cpp#L142)):*
> ```cpp
> 
> template <typename ComponentHandle>
> int run_job(log4cxx::LoggerPtr &logger, const std::string &broker_uri, const std::string &request_queue,
> ```

Calling this `run_job()` is misleading since the loop in this function pulls AMQ messages and can execute multiple jobs. Please rename it to something like`run_jobs()` or `receive_and_run_jobs()`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by jrobble** [comment]
*[trunk/detection/executor/cpp/batch/main.cpp, line 149 at r2](https://reviewable.io/reviews/openmpf/openmpf/550#-LBfcx1I5bLePj0gzCEx:-LBfcx1I5bLePj0gzCEy:ba2mt9p) ([raw file](https://github.com/openmpf/openmpf/blob/931cc92353755910fa79ff6c7abf21f80c012f5f/trunk/detection/executor/cpp/batch/main.cpp#L149)):*
> ```cpp
>     MPFMessenger messenger(logger);
> 
>     // Remain in loop handling track request messages
> ```

Please change this comment to "job request messages".

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by brosenberg42** [comment]
Review status: 40 of 47 files reviewed at latest revision, 4 unresolved discussions.

---

*[trunk/detection/executor/cpp/batch/CMakeLists.txt, line 59 at r1](https://reviewable.io/reviews/openmpf/openmpf/550#-LBWviyuCYmY-QFxN531:-LBfA5uQ7eV3v45fZAwM:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/e4d26aa70e50815e1244fa7bcf11ce8ad8407a4b/trunk/detection/executor/cpp/batch/CMakeLists.txt#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I'd prefer that we add it to the top-level LICENSE file. At a glance, a developer is only going to look there and not dive into sub-directories. If the pybind code came with its own license file, we should include that in the pybind11 dir too.

Now that I think about it, we should be including the MIT license file in the darknet_lib directory of the darknet component too. 
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py, line 104 at r2](https://reviewable.io/reviews/openmpf/openmpf/550#-LBbuCnK8rouGw2zpjQd:-LBfAvTx8nl05-uzlSxL:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/931cc92353755910fa79ff6c7abf21f80c012f5f/trunk/detection/executor/cpp/batch/test/test_python_components/test_component.py#L104)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Audio files aren't segmented. In my tests, the stop time was always -1, signifying the whole audio file. Thus, this middle time calculation didn't work as intended.

Note that the Sphinx component [checks for this](https://github.com/openmpf/openmpf-components/blob/develop/java/SphinxSpeechDetection/src/main/java/org/mitre/mpf/detection/sphinx/speech/SphinxSpeechDetectionComponent.java#L81).

You should check for it too, use the DURATION media property to do your calculation, or just hardcode something.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by jrobble** [comment]
Reviewed 7 of 7 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[LICENSE, line 60 at r3](https://reviewable.io/reviews/openmpf/openmpf/550#-LBgTFyc8setGnzLCKmV:-LBgTFyc8setGnzLCKmW:b6cj1hf) ([raw file](https://github.com/openmpf/openmpf/blob/46a968af5f7f8bfc251ef5de841bf8ba01de28db/LICENSE#L60)):*
> ```
> OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> Please also refer to the file CONTRIBUTING.md, which clarifies licensing of
> ```

Let's remove these last two lines since we don't include CONTRIBUTING.md.

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 443 at r3](https://reviewable.io/reviews/openmpf/openmpf/550#-LBgZCfk9v99RcriCPkR:-LBgZCfm7BwFdR_ociev:bx21spw) ([raw file](https://github.com/openmpf/openmpf/blob/46a968af5f7f8bfc251ef5de841bf8ba01de28db/trunk/detection/executor/cpp/batch/main.cpp#L443)):*
> ```cpp
>                         }
>                         LOG4CXX_WARN(logger, "[" << job_name.str()
>                                 << "] The detection component does not support detection data_type of "
> ```

Please remove the underscore in "date_type" in this message.

---

*[trunk/detection/executor/cpp/batch/pybind11/LICENSE, line 28 at r3](https://reviewable.io/reviews/openmpf/openmpf/550#-LBgT7Ug1526Ajwo8nMb:-LBgT7Ug1526Ajwo8nMc:b6cj1hf) ([raw file](https://github.com/openmpf/openmpf/blob/46a968af5f7f8bfc251ef5de841bf8ba01de28db/trunk/detection/executor/cpp/batch/pybind11/LICENSE#L28)):*
> ```
> OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
> 
> Please also refer to the file CONTRIBUTING.md, which clarifies licensing of
> ```

Let's remove these last two lines since we don't include CONTRIBUTING.md.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by brosenberg42** [comment]
Review status: 44 of 47 files reviewed at latest revision, 3 unresolved discussions.

---

*[LICENSE, line 60 at r3](https://reviewable.io/reviews/openmpf/openmpf/550#-LBgTFyc8setGnzLCKmV:-LBgf1_t0nxIDgfpWrQ4:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/cacc6ba120cbd81a13afcd855aa4e5351682eb92/LICENSE#L60)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's remove these last two lines since we don't include CONTRIBUTING.md.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 443 at r3](https://reviewable.io/reviews/openmpf/openmpf/550#-LBgZCfk9v99RcriCPkR:-LBgf3-e9gKi573iSMHJ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/cacc6ba120cbd81a13afcd855aa4e5351682eb92/trunk/detection/executor/cpp/batch/main.cpp#L443)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please remove the underscore in "date_type" in this message.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/batch/pybind11/LICENSE, line 28 at r3](https://reviewable.io/reviews/openmpf/openmpf/550#-LBgT7Ug1526Ajwo8nMb:-LBgf46a2rqs-JpR93f3:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/cacc6ba120cbd81a13afcd855aa4e5351682eb92/trunk/detection/executor/cpp/batch/pybind11/LICENSE#L28)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's remove these last two lines since we don't include CONTRIBUTING.md.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Comment by jrobble** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/550)*

**Pull request merged**
