### PR TITLE
Update ansible branch 092517

### PR DESCRIPTION
**Pull request by dpierce17**
testing ansible scripts for updating mpf, generic version with no requirement on mpf version number.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/263)

### CODE REVIEW

**Comment by jrobble** [comment]
Reviewed 2 of 23 files at r1.
Review status: 2 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[trunk/ansible/install/push-configuration.sh, line 28 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvCz5AOVqn0auuKsI16:-KvCz5AOVqn0auuKsI17:b-ogbw5m) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/push-configuration.sh#L28)):*
> ```Shell
> #############################################################################
> 
> # Run the mpf-clean ansible playbook, used to cleanup previously deployed mpf executables, jars and libs
> ```

Is something supposed to go under this comment? It seems like you're missing the line that runs the cleanup script. Maybe I'm missing how the cleanup gets executed. Please explain.

---

*[trunk/ansible/install/ansible/mpf-master.yml, line 195 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvCzD22ev_Hz1e2ZJ_q:-KvCzD22ev_Hz1e2ZJ_r:bt7age3) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/ansible/mpf-master.yml#L195)):*
> ```YAML
>     # this task must run after workflow-manager has started
>     - name: Update the mpf hibernate_sequence in mysql, as needed for upgrade to mpf Release 1.0.0
>       shell: mysql --execute="update mpf.hibernate_sequence set next_val=(SELECT IFNULL( (SELECT max(id)+1 FROM mpf.job_request), 1));"
> ```

What happens if this step is already done? In the future when someone upgrades from R1.0.0 (which is already using SEQUENCE) to R2.0.0, will running this command again break something in the DB?

---

*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml, line 31 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvD-fTRfTkYeWu8OjYJ:-KvD-fTRfTkYeWu8OjYK:b6ivt1s) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml#L31)):*
> ```YAML
>     include_vars: mpf-cleanup-sw-files/vars.yml
> 
>   - name: MPF cleanup, find old mpf files in the jars directory
> ```

Can we give each task a unique name? For example, we could name this to "MPF cleanup, check for old mpf files in the jars directory". That may help with debugging if the Ansible script fails.

It may be simpler to just remove the whole jars directory since I think it's recreated anyway. We might be able to simplify this to something like https://github.com/openmpf/openmpf/commit/a9e7383b27f913cff507ba466c6357e75ebc4595#diff-9d894b0437cfb7c0c79ed16482682dc5R32. 

---

*[trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/mysql.yml, line 35 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvD--U4hUNWKUw0ftc6:-KvD--U5ip7Xd6CiaEqb:b6l36eq) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/mysql.yml#L35)):*
> ```YAML
> 
>   # make sure mpf release 0.8 to 0.9 changes have been applied to MySQL schema.  Leave this check in, because the next line includes the handling commands
>   - name: Check for output_object_version column in mpf.job_request table
> ```

I'm wondering if we need a check like this before we run the mySQL commands to use SEQUENCE.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
Overall, these changes are looking good! I'm pretty excited to be simplifying these scripts and making them more robust. The proof is in the pudding though. We'll see how the tests go. Historically there's trial and error involved and it takes a lot of time to work the kinks out. Your changes are minimal though, so hopefully it goes well. 

---

Review status: 2 of 18 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263#-:-KvD23-HPugRwFqKhwiw:b8jpcu4)*

**Comment by dpierce17** [comment]
*[trunk/ansible/install/push-configuration.sh, line 28 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvCz5AOVqn0auuKsI16:-KvD9pYdbENcv4AIkUMx:bsuch8k) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/push-configuration.sh#L28)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is something supposed to go under this comment? It seems like you're missing the line that runs the cleanup script. Maybe I'm missing how the cleanup gets executed. Please explain.
</blockquote></details>

Yes, I added the comment and neglected to actually make the call to the playbook, fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by dpierce17** [comment]
*[trunk/ansible/install/ansible/mpf-master.yml, line 195 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvCzD22ev_Hz1e2ZJ_q:-KvDB8btWm8E430yQYEc:b-lkpb0p) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/ansible/mpf-master.yml#L195)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What happens if this step is already done? In the future when someone upgrades from R1.0.0 (which is already using SEQUENCE) to R2.0.0, will running this command again break something in the DB?
</blockquote></details>

The only way this would break anything in the DB is if in some future release we add another entity to the hibernate sequence, so realistically this command may have to be updated in the future.  But, repeating this step during a future deployment if current hibernate conditions still apply won't break anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by dpierce17** [comment]
*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml, line 31 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvD-fTRfTkYeWu8OjYJ:-KvDMe1L_yTZFRZErORD:b-wajub) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml#L31)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Can we give each task a unique name? For example, we could name this to "MPF cleanup, check for old mpf files in the jars directory". That may help with debugging if the Ansible script fails.

It may be simpler to just remove the whole jars directory since I think it's recreated anyway. We might be able to simplify this to something like https://github.com/openmpf/openmpf/commit/a9e7383b27f913cff507ba466c6357e75ebc4595#diff-9d894b0437cfb7c0c79ed16482682dc5R32. 


</blockquote></details>

Each task is already uniquely named, there are 8 tasks: 4 are named with "find" the other 4 are named with "remove".  Each "find" and "remove" is named with either "jars", "lib", "libdata" or "bin

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml, line 31 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvD-fTRfTkYeWu8OjYJ:-KvDNdDzrxYSsTpMvf0k:brq0zo5) ([raw file](https://github.com/openmpf/openmpf/blob/fcb925740a8abd9ee0cc71c1c36397350f2cbe70/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml#L31)):*
<details><summary><i>Previously, dpierce17 wrote…</i></summary><blockquote>

Each task is already uniquely named, there are 8 tasks: 4 are named with "find" the other 4 are named with "remove".  Each "find" and "remove" is named with either "jars", "lib", "libdata" or "bin
</blockquote></details>

Oops. I didn't catch that. False alarm. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
Reviewed 1 of 23 files at r1, 13 of 18 files at r2, 10 of 11 files at r3.
Review status: 26 of 44 files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/test/package.json, line 15 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvSRX_UWSwzKqkIurpv:-KvSRX_UWSwzKqkIurpw:bukme7j) ([raw file](https://github.com/openmpf/openmpf/blob/00c5eefaced30c4c8b9593e7791eb55cdcf9ac80/trunk/workflow-manager/src/test/package.json#L15)):*
> ```JSON
>   },
>   "engines": {
>     "node": ">=1.0.0"
> ```

This refers to the version of [node.js](https://nodejs.org/en/), not OpenMPF, so please leave it as 0.10.0.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
Reviewed 7 of 23 files at r1, 2 of 18 files at r2, 2 of 6 files at r4.
Review status: 33 of 44 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml, line 63 at r4](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvgzUk22kOlbFspDJRx:-KvgzUk22kOlbFspDJRy:bj0k37) ([raw file](https://github.com/openmpf/openmpf/blob/5d8b6b46c4a2ab59f66aedc56e4eee518e0b293e/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files/mpf-cleanup-files.yml#L63)):*
> ```YAML
>     register: oldlibdata_find
> 
>   - name: MPF cleanup, remove old mpf files in the libdat directory
> ```

Check spelling "libdat".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
Review status: 33 of 44 files reviewed at latest revision, 4 unresolved discussions.

---

*[trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customPipelines.yml, line 57 at r6](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kvn0egyEEzqVIe8dS_4:-Kvn0egz0vQb0-kbhdfu:b-e556l) ([raw file](https://github.com/openmpf/openmpf/blob/b1bf08f0f261708111bf62f29834192eb957c88d/trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customPipelines.yml#L57)):*
> "{{ tomcat_home }}/webapps/workflow-manager/WEB-INF/classes/{{ item.item }}.xml"

This path was valid on a R0.8 install. Please update this to "{{ mpf_home }}/data/{{ item.item }}.xml", which is the correct path on R0.9+ installs.

---

*[trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customProperties.yml, line 31 at r6](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kvn1od-uJeMiBT2Y0y9:-Kvn1od-uJeMiBT2Y0yA:b7u5gt7) ([raw file](https://github.com/openmpf/openmpf/blob/b1bf08f0f261708111bf62f29834192eb957c88d/trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customProperties.yml#L31)):*
> "{{ tomcat_home }}/webapps/workflow-manager/WEB-INF/classes/properties/mpf-custom.properties"

This path was valid on a R0.8 install. Please update this to "{{ mpf_home }}/config/mpf-custom.properties", which is the correct path on R0.9+ installs.

---

*[trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customProperties.yml, line 47 at r6](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kvn1y-8KgbOH3wDFbDr:-Kvn1y-8KgbOH3wDFbDs:byf1khg) ([raw file](https://github.com/openmpf/openmpf/blob/b1bf08f0f261708111bf62f29834192eb957c88d/trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customProperties.yml#L47)):*
> ```YAML
>   - name: "Copy mpf-custom.properties to {{ mpf_home }}/config/mpf-custom.properties"
>     copy:
>       src="{{ tomcat_home }}/webapps/workflow-manager/WEB-INF/classes/properties/mpf-custom.properties"
> ```

Please update this to "{{ mpf_home }}/config/mpf-custom.properties".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by dpierce17** [comment]
*[trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customProperties.yml, line 47 at r6](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kvn1y-8KgbOH3wDFbDr:-KvnT_8Ak2PfsJUpcK1v:b-kgl7yc) ([raw file](https://github.com/openmpf/openmpf/blob/b1bf08f0f261708111bf62f29834192eb957c88d/trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customProperties.yml#L47)):*
> {{ mpf_home }}/config/mpf-custom.properties
Ok, did that.  But then isn't src and dest the same?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/mpf-master.yml, line 111 at r7](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvnacQWv9bSX-XtbT7j:-KvnacQXnUJaYHEGJAPF:b6qwatb) ([raw file](https://github.com/openmpf/openmpf/blob/33f183b5acd2079ab69064603fd0f6102e38ad26/trunk/ansible/install/ansible/mpf-master.yml#L111)):*
> ```YAML
>         destfile: "{{ mpf_home }}/data/Algorithms.xml"
>         regexp: '(<algorithm\s+name="\w+"\s+actionType="\w+")\s*>'
>         replace: '\1 supportsBatchProcessing="true" supportsStreamProcessing="true">'
> ```

`supportsStreamProcessing` should be set to "false" for now.

Is it possible to only add `supportsBatchProcessing="true" supportsStreamProcessing="false"` if the line that starts with `<algorithm` doesn't already have one of those fields?

If it's not easy to do in Ansible, it might be easier to just run the `sed` command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customPipelines.yml, line 82 at r7](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kvnc5-mfops0ILWC7Pa:-Kvnc5-nQNYizbAj6JEn:bilf6px) ([raw file](https://github.com/openmpf/openmpf/blob/33f183b5acd2079ab69064603fd0f6102e38ad26/trunk/ansible/install/ansible/roles/upgrade/tasks/mpf-to-current/customPipelines.yml#L82)):*
> ```YAML
>     run_once: true
> 
>   - name: After backuping existing Algorithms, Actions, Tasks, and Pipelines files - find original Algorithms.xml
> ```

Instead of going through the files one-by-one, I think you can condense the 8 tasks you added to one task by doing something similar to what the above "Backup existing Algorithms, Actions, Tasks, and Pipelines files" is doing:

```
  - name: Remove old Algorithms, Actions, Tasks, and Pipelines files
    file:
      path: "{{ item.stat.path }}"
      state=absent
    with_items: "{{ files_check_st.results }}"
    when: "files_check_st is defined and {{ item.stat.exists | default(false)}}"
    delegate_to: "{{ master_host }}"
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml, line 32 at r7](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvoVJXCyPiM_PdTeHH4:-KvoVJXDTUYY2elKFPAp:bcbrs23) ([raw file](https://github.com/openmpf/openmpf/blob/33f183b5acd2079ab69064603fd0f6102e38ad26/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml#L32)):*
> ```YAML
>     include_vars: mpf-cleanup-sw-files/vars.yml
> 
>   - include: mpf-cleanup-sw-files/mpf-cleanup-files.yml
> ```

I think you can get rid of the mpf-cleanup-sw-files directory and move mpf-cleanup-files.yml up to roles/cleanup/tasks.

Similarly, I think  you can get rid of the mpf-to-current directory and move everything in there up to roles/upgrade/tasks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by dpierce17** [comment]
*[trunk/ansible/install/ansible/mpf-master.yml, line 111 at r7](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvnacQWv9bSX-XtbT7j:-Kw00L-RtGvDhLFcxrY6:bkvspqs) ([raw file](https://github.com/openmpf/openmpf/blob/33f183b5acd2079ab69064603fd0f6102e38ad26/trunk/ansible/install/ansible/mpf-master.yml#L111)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

`supportsStreamProcessing` should be set to "false" for now.

Is it possible to only add `supportsBatchProcessing="true" supportsStreamProcessing="false"` if the line that starts with `<algorithm` doesn't already have one of those fields?

If it's not easy to do in Ansible, it might be easier to just run the `sed` command.

</blockquote></details>

Running the sed command was difficult because of the need to escape all of the special characters, I couldn't find a way to add sed to ansible that would work.  The replace command worked nicely, if the regex isn't satisfied then the replacement won't be made.  I tested this task on both R0.9.0 and R1.0.0 Algorithm.xml files, and the replace task works on both.  I did change supportsStreamProcessing to false.  Right now, the regex checks for the <algorithm line only having pattern <algorithm name="something" actionType="somethingelse" followed by nothing else except spaces and ">" - if this is true then the two supporting processing attributes are inserted.  I think this replacement works as you requested.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/mpf-master.yml, line 111 at r7](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvnacQWv9bSX-XtbT7j:-Kw0Qe7VH1PXwV3Ns7Rp:b-obtvv8) ([raw file](https://github.com/openmpf/openmpf/blob/33f183b5acd2079ab69064603fd0f6102e38ad26/trunk/ansible/install/ansible/mpf-master.yml#L111)):*
<details><summary><i>Previously, dpierce17 wrote…</i></summary><blockquote>

Running the sed command was difficult because of the need to escape all of the special characters, I couldn't find a way to add sed to ansible that would work.  The replace command worked nicely, if the regex isn't satisfied then the replacement won't be made.  I tested this task on both R0.9.0 and R1.0.0 Algorithm.xml files, and the replace task works on both.  I did change supportsStreamProcessing to false.  Right now, the regex checks for the <algorithm line only having pattern <algorithm name="something" actionType="somethingelse" followed by nothing else except spaces and ">" - if this is true then the two supporting processing attributes are inserted.  I think this replacement works as you requested.
</blockquote></details>

Thanks for the explanation. This should work, so no need to change it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/mpf-master.yml, line 111 at r7](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KvnacQWv9bSX-XtbT7j:-Kw0QzAY2Dyty9dHIV0_:bhgqyvi) ([raw file](https://github.com/openmpf/openmpf/blob/33f183b5acd2079ab69064603fd0f6102e38ad26/trunk/ansible/install/ansible/mpf-master.yml#L111)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Thanks for the explanation. This should work, so no need to change it.
</blockquote></details>

Except for supportsStreamProcessing="false", which I see you did change :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
Reviewed 1 of 25 files at r1, 1 of 5 files at r7.
Review status: 30 of 43 files reviewed at latest revision, 5 unresolved discussions.

---

*[trunk/ansible/install/run-install.py, line 494 at r9](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kw3-R2kwvc6MilxfGZW:-Kw3-R2lHYaDzUE9A3GV:b-654fg3) ([raw file](https://github.com/openmpf/openmpf/blob/a00fbfd98e5f11f86559eeb87d6d4f69eea20d2d/trunk/ansible/install/run-install.py#L494)):*
> ```Python
> # Setup the Ansible playbook command
> ansible_cmd = ['ansible-playbook',
>                '-vvv',
> ```

Note that this verbose option should only be temporary while we're debugging.

---

*[trunk/ansible/install/ansible/roles/child/tasks/main.yml, line 142 at r9](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kw3-ZT5aT5AHgEkjmC6:-Kw3-ZT5aT5AHgEkjmC7:b-tfnhcq) ([raw file](https://github.com/openmpf/openmpf/blob/a00fbfd98e5f11f86559eeb87d6d4f69eea20d2d/trunk/ansible/install/ansible/roles/child/tasks/main.yml#L142)):*
> ```YAML
>   register: java_component_executor
> 
> - debug: msg="debug in mpf-child after Install MPF Java Component Executor, java_component_executor is {{ java_component_executor }} "
> ```

This is also temporary.

I just installed build #32 and everything worked, so these new removal tasks seem to have done the job. 

---

*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml, line 107 at r9](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kw3-qxWJFHtGjJL_FqD:-Kw3-qxWJFHtGjJL_FqE:bwfsv4l) ([raw file](https://github.com/openmpf/openmpf/blob/a00fbfd98e5f11f86559eeb87d6d4f69eea20d2d/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml#L107)):*
This task doesn't work like I expected. The first time I ran `. /opt/mpf/manage/push-configuration.sh` to perform the upgrade everything worked, however, after the upgrade I ran it again and started to encounter issues like the following:

```
failed: [sugarbowl-7-mpfd8] (item={u'uid': 376, u'woth': False, u'mtime': 1507584660.0, u'inode': 203581382, u'isgid': False, u'size': 92368, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 376, u'ischr': False, u'wusr': True, u'xoth': True, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/opt/mpf/lib/libmpfopencvjni.so', u'xusr': True, u'atime': 1507599833.560173, u'isdir': False, u'ctime': 1507599717.659258, u'isblk': False, u'xgrp': True, u'dev': 64768, u'wgrp': False, u'isfifo': False, u'mode': u'0755', u'islnk': False}) => {"failed": true, "item": {"atime": 1507599833.560173, "ctime": 1507599717.659258, "dev": 64768, "gid": 376, "inode": 203581382, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0755", "mtime": 1507584660.0, "nlink": 1, "path": "/opt/mpf/lib/libmpfopencvjni.so", "rgrp": true, "roth": true, "rusr": true, "size": 92368, "uid": 376, "wgrp": false, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/mpf/.ansible/tmp/ansible-tmp-1507600715.08-251268129726822/file\", line 9, in <module>\r\n    import tempfile\r\n  File \"/usr/lib64/python2.7/tempfile.py\", line 35, in <module>\r\n    from random import Random as _Random\r\n  File \"/usr/lib64/python2.7/random.py\", line 49, in <module>\r\n    import hashlib as _hashlib\r\n  File \"/usr/lib64/python2.7/hashlib.py\", line 116, in <module>\r\n    import _hashlib\r\nImportError: /opt/mpf/lib/libssl.so.10: symbol private_ossl_minimum_dh_bits, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Of note:

> libcrypto.so.10 not defined in file libcrypto.so.10

The above error was part of "TASK [cleanup : MPF cleanup, remove old mpf files in the lib directory]". There are many more errors like it. It seems like the error is generated once per file that we try to remove.

I believe the issue is that as soon as we remove the crypto lib Ansible needs it before it can create the next SSH session. Ansible creates one session per task, and sometimes multiple sessions for the same task.

For each item that we try to remove as part of "TASK [cleanup : MPF cleanup, remove old mpf files in the lib directory]", it seems that Ansible creates a new SSH session. For that reason, it would be much quicker to just delete the /opt/mpf/lib directory instead of iterating over each file. Similarly, we should just delete the /opt/mpf/jars, opt/mpf/bin. and /opt/mpf/libexec directories.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml, line 107 at r9](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kw3-qxWJFHtGjJL_FqD:-Kw35WVnxr2U0S2UrnBE:bm1rwts) ([raw file](https://github.com/openmpf/openmpf/blob/a00fbfd98e5f11f86559eeb87d6d4f69eea20d2d/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml#L107)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This task doesn't work like I expected. The first time I ran `. /opt/mpf/manage/push-configuration.sh` to perform the upgrade everything worked, however, after the upgrade I ran it again and started to encounter issues like the following:

```
failed: [sugarbowl-7-mpfd8] (item={u'uid': 376, u'woth': False, u'mtime': 1507584660.0, u'inode': 203581382, u'isgid': False, u'size': 92368, u'roth': True, u'isuid': False, u'isreg': True, u'gid': 376, u'ischr': False, u'wusr': True, u'xoth': True, u'rusr': True, u'nlink': 1, u'issock': False, u'rgrp': True, u'path': u'/opt/mpf/lib/libmpfopencvjni.so', u'xusr': True, u'atime': 1507599833.560173, u'isdir': False, u'ctime': 1507599717.659258, u'isblk': False, u'xgrp': True, u'dev': 64768, u'wgrp': False, u'isfifo': False, u'mode': u'0755', u'islnk': False}) => {"failed": true, "item": {"atime": 1507599833.560173, "ctime": 1507599717.659258, "dev": 64768, "gid": 376, "inode": 203581382, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "mode": "0755", "mtime": 1507584660.0, "nlink": 1, "path": "/opt/mpf/lib/libmpfopencvjni.so", "rgrp": true, "roth": true, "rusr": true, "size": 92368, "uid": 376, "wgrp": false, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/mpf/.ansible/tmp/ansible-tmp-1507600715.08-251268129726822/file\", line 9, in <module>\r\n    import tempfile\r\n  File \"/usr/lib64/python2.7/tempfile.py\", line 35, in <module>\r\n    from random import Random as _Random\r\n  File \"/usr/lib64/python2.7/random.py\", line 49, in <module>\r\n    import hashlib as _hashlib\r\n  File \"/usr/lib64/python2.7/hashlib.py\", line 116, in <module>\r\n    import _hashlib\r\nImportError: /opt/mpf/lib/libssl.so.10: symbol private_ossl_minimum_dh_bits, version libcrypto.so.10 not defined in file libcrypto.so.10 with link time reference\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Of note:

> libcrypto.so.10 not defined in file libcrypto.so.10

The above error was part of "TASK [cleanup : MPF cleanup, remove old mpf files in the lib directory]". There are many more errors like it. It seems like the error is generated once per file that we try to remove.

I believe the issue is that as soon as we remove the crypto lib Ansible needs it before it can create the next SSH session. Ansible creates one session per task, and sometimes multiple sessions for the same task.

For each item that we try to remove as part of "TASK [cleanup : MPF cleanup, remove old mpf files in the lib directory]", it seems that Ansible creates a new SSH session. For that reason, it would be much quicker to just delete the /opt/mpf/lib directory instead of iterating over each file. Similarly, we should just delete the /opt/mpf/jars, opt/mpf/bin. and /opt/mpf/libexec directories.
</blockquote></details>

I believe that at the top of this file we should have a task that deletes /etc/ld.so.conf.d/mpf.conf, immediately followed by a task that runs ldconfig. We can remove the ldconfig task at the end of this file.

This would make Ansible stop looking at the contents of /opt/mpf/lib until the /etc/ld.so.conf.d/mpf.conf file is reinstalled later.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml, line 107 at r9](https://reviewable.io:443/reviews/openmpf/openmpf/263#-Kw3-qxWJFHtGjJL_FqD:-Kw3BVOkxAYhL23NzF_S:bccxov7) ([raw file](https://github.com/openmpf/openmpf/blob/a00fbfd98e5f11f86559eeb87d6d4f69eea20d2d/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml#L107)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I believe that at the top of this file we should have a task that deletes /etc/ld.so.conf.d/mpf.conf, immediately followed by a task that runs ldconfig. We can remove the ldconfig task at the end of this file.

This would make Ansible stop looking at the contents of /opt/mpf/lib until the /etc/ld.so.conf.d/mpf.conf file is reinstalled later.
</blockquote></details>

I did some more debugging. After I got around the libcrypto issue, I ran into the following error the next time I ran `. /opt/mpf/manage/push-configuration.sh`:

```
Error reading file '/opt/mpf/data/Algorithms.xml': failed to load external entity \"/opt/mpf/data/Algorithms.xml\"", "stdout": "", "stdout_lines": [], "warnings": []}
```

That error is part of  "RUNNING HANDLER [upgrade : Merge custom Algorithms, Actions, Tasks, and Pipelines] ***"

I'm wondering if we shouldn't be deleting Algorithms.xml, Actions.xml, Tasks.xml, and Pipelines.xml.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
*[trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml, line 65 at r10](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KwBmSrkIbMcKGYiCLHL:-KwBmSrlevD0A0EWCM3B:b-uhmdk6) ([raw file](https://github.com/openmpf/openmpf/blob/1985ad3c4e75c6214d8d84f8308b72d4e708f694/trunk/ansible/install/ansible/roles/cleanup/tasks/mpf-cleanup-sw-files.yml#L65)):*
> ```YAML
>       paths: "{{ mpf_home }}/data"
>       patterns: "nodeServicesPalette.json"
>     register: oldNodePallet_find
> ```

Correct spelling on `Palette` in this file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
Reviewed 4 of 25 files at r1, 1 of 18 files at r2, 1 of 1 files at r6, 3 of 13 files at r8, 2 of 6 files at r9, 36 of 37 files at r12.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[trunk/ansible/install/ansible/roles/child/tasks/compunregistration.yml, line 29 at r12](https://reviewable.io:443/reviews/openmpf/openmpf/263#-KwufFoRSRXcZfV-jWI9:-KwufFoSmPscM9SZh1zr:bgpkzy0) ([raw file](https://github.com/openmpf/openmpf/blob/c191b88074e4d24bc033110f16dfc683f1855547/trunk/ansible/install/ansible/roles/child/tasks/compunregistration.yml#L29)):*
Remove this:

> TODO: check if component was previously installed before doing this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r13.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/263)*

**Pull request merged**
