### PR TITLE
Fix markup animation. Issue #267

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/269)

### CODE REVIEW

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 133 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvd2X8fmkMfOFInSQoi:-Kvd2X8fmkMfOFInSQoj:bgd5zaf) ([raw file](https://github.com/openmpf/openmpf/blob/5bae793d55aabe1e384aa218066451cc62a61dcd/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L133)):*
> ```Java
> 						boundingBoxMap.putOnFrames(Math.round(track.getStartOffsetFrameInclusive()), Math.round(track.getEndOffsetFrameInclusive()), boundingBox);
> 						break;
> 					} else if (samplingInterval <= 1) {
> ```

Generally speaking, I think the intent is to animate (interpolate) the bounding box between detection regions in the same track. When this code was originally written, I believe the author thought that the only way to get detections in non-consecutive frames was if the sampling interval > 1. However, we now know that:

1. Some algorithm trackers generate tracks where there is not a detection in each frame between the track start and stop
frames.
2. Feed forward may result in tracks that do not have a detection in every frame of the track.
3. USE_KEY_FRAMES may result in tracks that do not have a detection in every frame of the track.

I believe that we should also be animating (interpolating) the bounding box in these three cases even when the sampling interval is <= 1. I believe that it would be better to just check if there is a gap between the current frame and the next. If so, animate (interpolate).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by jrobble** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java, line 109 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvct1UGk4LTcPobfIVC:-Kvct1UHjPYreOdOdGV5:bhu4pl3) ([raw file](https://github.com/openmpf/openmpf/blob/5bae793d55aabe1e384aa218066451cc62a61dcd/trunk/markup/src/main/java/org/mitre/mpf/markup/MarkupRequestConsumer.java#L109)):*
> ```Java
>         }
> 
> 	    log.info("[Markup Request #{}] Marking up {} detections on '{}'.", markupRequest.getRequestId(), markupRequest.getMapEntriesCount(), markupRequest.getDestinationUri());
> ```

Thanks for this. I was going to recommend it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 131 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh6_jJtnAeFW3glZAW:-Kvh6_jKXl1ZylIOZJOL:b-h3f3a8) ([raw file](https://github.com/openmpf/openmpf/blob/a09d2db5c78b60a845ac4c6fff7a1f83f6d1ce26/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L131)):*
> ```Java
> 						// Special case: Speech doesn't populate object locations for each frame in the video, so you have to
> 						// go by the track start and stop frames.
> 						boundingBoxMap.putOnFrames(Math.round(track.getStartOffsetFrameInclusive()), Math.round(track.getEndOffsetFrameInclusive()), boundingBox);
> ```

Math.round()?

Any idea why that might have been used?

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 132 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh2AZGjuaZvRkkrdnY:-Kvh2AZH1MSqv4UFrfdo:bqfsox5) ([raw file](https://github.com/openmpf/openmpf/blob/02dae2f87b7a66cedb2c749dd450d5a802f64b56/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L132)):*
> ```Java
> 			}
> 
> 			boolean isLastDetection = i == (orderedDetections.size() - 1);
> ```

Please use another set of () for clarity:

`boolean isLastDetection = (i == (orderedDetections.size() - 1));`

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 141 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh6F-3Ip92ldspQxCx:-Kvh6F-3Ip92ldspQxCy:b-gn6vnf) ([raw file](https://github.com/openmpf/openmpf/blob/6df288cad7c5f3f0ba616425782d7c110522b2cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L141)):*
Let's update this comment:

>  All we need to do is draw this frame's box. If this is not the end of the track, then no further bounding boxes will be drawn between this detection and the end of the track.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 131 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh6_jJtnAeFW3glZAW:-KvhExHYfWOtxyfUz_GW:b32w12) ([raw file](https://github.com/openmpf/openmpf/blob/a09d2db5c78b60a845ac4c6fff7a1f83f6d1ce26/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L131)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Math.round()?

Any idea why that might have been used?
</blockquote></details>

No

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 141 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh6F-3Ip92ldspQxCx:-KvhFeCW8qsQSNMNg7Jr:b-yli44d) ([raw file](https://github.com/openmpf/openmpf/blob/6df288cad7c5f3f0ba616425782d7c110522b2cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L141)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Let's update this comment:

>  All we need to do is draw this frame's box. If this is not the end of the track, then no further bounding boxes will be drawn between this detection and the end of the track.
</blockquote></details>

In most people's interpretation of  "end of the track", that comment is not accurate. I am only able to understand what you mean because I know what the code used to do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 141 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh6F-3Ip92ldspQxCx:-KvhJKUPR6NRr-K6R76y:bx7a4dk) ([raw file](https://github.com/openmpf/openmpf/blob/6df288cad7c5f3f0ba616425782d7c110522b2cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L141)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

In most people's interpretation of  "end of the track", that comment is not accurate. I am only able to understand what you mean because I know what the code used to do.
</blockquote></details>

Instead of "end of track" should we say "track stop frame"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by brosenberg42** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 133 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvd2X8fmkMfOFInSQoi:-KvhSuB_sfIVDhEuOaw1:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/a09d2db5c78b60a845ac4c6fff7a1f83f6d1ce26/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L133)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Generally speaking, I think the intent is to animate (interpolate) the bounding box between detection regions in the same track. When this code was originally written, I believe the author thought that the only way to get detections in non-consecutive frames was if the sampling interval > 1. However, we now know that:

1. Some algorithm trackers generate tracks where there is not a detection in each frame between the track start and stop
frames.
2. Feed forward may result in tracks that do not have a detection in every frame of the track.
3. USE_KEY_FRAMES may result in tracks that do not have a detection in every frame of the track.

I believe that we should also be animating (interpolating) the bounding box in these three cases even when the sampling interval is <= 1. I believe that it would be better to just check if there is a gap between the current frame and the next. If so, animate (interpolate).
</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 132 at r2](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh2AZGjuaZvRkkrdnY:-KvhSvHB7T55_vez03i2:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/02dae2f87b7a66cedb2c749dd450d5a802f64b56/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L132)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please use another set of () for clarity:

`boolean isLastDetection = (i == (orderedDetections.size() - 1));`

</blockquote></details>

Done.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 141 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh6F-3Ip92ldspQxCx:-KvhSvu4KJ2dZxPTcKHL:b-181mkg) ([raw file](https://github.com/openmpf/openmpf/blob/6df288cad7c5f3f0ba616425782d7c110522b2cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L141)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Instead of "end of track" should we say "track stop frame"?
</blockquote></details>

That still doesn't make sense.
"If this is not the track stop frame," is always true
"no further bounding boxes will be drawn between this detection and the end of the track" is always false because in the next iteration of the loop another bounding box will be drawn. 

I understand what you are getting at, but I don't think we need to have a comment explaining why we don't do something that doesn't make sense to do.
The comment that is already there is pointless.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java, line 141 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/269#-Kvh6F-3Ip92ldspQxCx:-KvhVYzufFaqQuIYKsDd:b-4uk772) ([raw file](https://github.com/openmpf/openmpf/blob/6df288cad7c5f3f0ba616425782d7c110522b2cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupStageSplitter.java#L141)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

That still doesn't make sense.
"If this is not the track stop frame," is always true
"no further bounding boxes will be drawn between this detection and the end of the track" is always false because in the next iteration of the loop another bounding box will be drawn. 

I understand what you are getting at, but I don't think we need to have a comment explaining why we don't do something that doesn't make sense to do.
The comment that is already there is pointless.

</blockquote></details>

My mistake. My comments were describing the old `} else if (i == (track.getDetections().size() - 1)) {` behavior. Let's remove this comment. I think the code is pretty self-explanatory here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/269)*

**Pull request merged**
