### PR TITLE
Json output update branch2

### PR DESCRIPTION
**Pull request by dpierce17**
updated runFaceOcvCustomDetectVideo-defaultCompare.json for Test#3 runFaceOcvCustomDetectVideo test

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/100)

### CODE REVIEW

**Comment by jrobble** [comment]
Please cancel this pull request and create a new one. When you create the pull request please specify that you want the code to be merged into the "develop" branch not the "master" branch.

---

Review status: 0 of 65 files reviewed at latest revision, 3 unresolved discussions.

---

*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 231 at r8](https://reviewable.io:443/reviews/openmpf/openmpf/100#-Klyew4MC9CBlh-HlCHC:-Klyew4MC9CBlh-HlCHD:b-sh5r5k) ([raw file](https://github.com/openmpf/openmpf/blob/92e43c3b4868250b44f7b1728083e6c69e88bfa5/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L231)):*
> ```Java
> //
> //        String taskName = "TEST OCV FACE TASK";
> //        addTask(taskName, actionName);
> ```

I don't think you need the above commented out lines to generate the default output. "OCV FACE DETECTION PIPELINE" is part of OpenMPF by default. It's doesn't depend on "TEST X OCV FACE" and "TEST OCV FACE TASK".

---

*[trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java, line 239 at r8](https://reviewable.io:443/reviews/openmpf/openmpf/100#-KlyfrYGa8HkMq4oS_Ql:-KlyfrYGa8HkMq4oS_Qm:bav0o1j) ([raw file](https://github.com/openmpf/openmpf/blob/92e43c3b4868250b44f7b1728083e6c69e88bfa5/trunk/mpf-system-tests/src/test/java/org/mitre/mpf/mst/TestSystemNightly.java#L239)):*
> ```Java
>         List<JsonMediaInputObject> media = toMediaObjectList(ioUtils.findFile("/samples/person/video_02.mp4"));
>         long jobId = runPipelineOnMedia(pipelineName, media, Collections.emptyMap(),
> //        long jobId = runPipelineOnMedia("OCV FACE DETECTION PIPELINE", mediaPaths,  // to generate default output
> ```

Note that the comment about generating the default output is already here. Delete this comment or your new comment.

---

*[trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvCustomDetectVideo-defaultCompare.json, line 32 at r8](https://reviewable.io:443/reviews/openmpf/openmpf/100#-KlygA73wn9uZRYs9RIh:-KlygA73wn9uZRYs9RIi:b-q9pkkn) ([raw file](https://github.com/openmpf/openmpf/blob/44db2b5b01c0e897efd5109a92cc0391995bb65d/trunk/mpf-system-tests/src/test/resources/output/face/runFaceOcvCustomDetectVideo-defaultCompare.json#L32)):*
> ```JSON
>         {
>             "mediaId": 0,
>             "path": "file:///home/mpf/dev/mpf/trunk/mpf-system-tests/target/test-classes/samples/person/chokepoint_P2E_S5_C1.mp4",
> ```

It's odd how the old file has media in it that's not part of the runFaceOcvCustomDetectVideo test. I'm 100% on board with removing it if it's not necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/100#-:-KlygppwQrQrxYcY2S1A:b1hkb0c)*

**Comment by dpierce17** [comment]
canceling this pull request

**Comment by dpierce17** [comment]
I closed this merge request, and am making the comment changes you requested.  But, I don't see the media line you're referring to in runFaceOcvCustomDetectVideo-defaultCompare.json (i.e.           "path": "file:///home/mpf/dev/mpf/trunk/mpf-system-tests/target/test-classes/samples/person/chokepoint_P2E_S5_C1.mp) so I'm not sure how to make the change you are requesting.  When ready, I'll re-create the pull request using develop.

**Comment by jrobble** [comment]
chokepoint_P2E_S5_C1 is in the JSON file in the master branch. You may not see that code in the JSON file in the develop branch. You shouldn't have to do anything. The JSON file you're generating should only list the one piece of media used in the test.

**Pull request closed without merging**
