### PR TITLE
Changes for improved docker build

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/988)

### CODE REVIEW

**Comment by brosenberg42** [comment]
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITComponentRegistration.java, line 65 at r1](https://reviewable.io/reviews/openmpf/openmpf/988#-LyVdIfNCgEY69UQZtto:-Ly_MsyNEQmJPo1Ipzcu:bxrqyi9) ([raw file](https://github.com/openmpf/openmpf/blob/d73e737eaf3f9c30f267d5401e830f579150f8cf/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/ITComponentRegistration.java#L65)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How is my message not grammatically correct? Looking for `Assume.assumeTrue(` in the rest of the codebase shows some messages that start with "Skipping test". I was just trying to be consistent. Are those not grammatically correct?
</blockquote></details>

May be "grammatically correct" wasn't the right term to use. "Assume ansible is installed" makes more sense than "Assume skipping component registration tests because Ansible is not installed."

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/component_registration/layout.html, line 56 at r4](https://reviewable.io/reviews/openmpf/openmpf/988#-LzIwEHW66OtJDDPCEhR:-LzJ0DnJ6_a5W_CEMqy2:bktwirk) ([raw file](https://github.com/openmpf/openmpf/blob/b3b6ec19e7259293c99c7835f0b3d5937441c0eb/trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/component_registration/layout.html#L56)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This got me thinking. While it seems like we could use the `CORE_MPF_NODES` env. variable to determine if the WFM is part of a Docker deployment, I'm wondering if we want to be more direct and just set `ENV DOCKER=true` in the WFM Dockerfile. 

We can then use that to pass a field to the web UI so that we can:
1. Hide the "Nodes" page
2. Hide the "Package name" and "Date uploaded" fields in the "Component Registration" page
3. Hide the "Note that all actions performed on this page" messages.
</blockquote></details>

Also, the "Managed" column doesn't tell us much in a full Docker deployment. We could hide that as well.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/component_registration/layout.html, line 56 at r4](https://reviewable.io/reviews/openmpf/openmpf/988#-LzIwEHW66OtJDDPCEhR:-LzJ1bUhDHplG0xbCZfQ:b-5j0t8n) ([raw file](https://github.com/openmpf/openmpf/blob/b3b6ec19e7259293c99c7835f0b3d5937441c0eb/trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/component_registration/layout.html#L56)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Also, the "Managed" column doesn't tell us much in a full Docker deployment. We could hide that as well.
</blockquote></details>

Actually, the whole "Component Upload" feature doesn't make sense. I'm now leaning towards using a different "Component Registration" page for Docker deployments due to all of the differences. We can use one page for non-Docker deployments and a much simpler page for Docker deployments.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/webapp/WEB-INF/views/login_view.jsp, line 69 at r3](https://reviewable.io/reviews/openmpf/openmpf/988#-Lz8L3nH1IZEn2Kl76od:-LzJ1OQ-2t1qrPbUyGcC:bift60c) ([raw file](https://github.com/openmpf/openmpf/blob/8409121a1847c7f4703e0867a78c0fee17524d7e/trunk/workflow-manager/src/main/webapp/WEB-INF/views/login_view.jsp#L69)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note to self: Look for this in web UI.
</blockquote></details>

Related to this change, we're currently showing "unofficial build" in the top banner bar when the `gitBranch` is not set:

```
	MetadataService.getMetadata().then(function(data) {
		HomeUtilsFull.displayVersion = data.version;
		if ( data['gitBranch'] === "unknown" ) {
			HomeUtilsFull.displayVersion += " (unofficial build)";
		}
		else if ( data['gitBranch'] === "develop" ) {
			HomeUtilsFull.displayVersion += " ( " + data['gitBranch'] + "-" + data['buildNum'] + "-" + data['gitHash'] + " )";
		}
	});
```

Our official master releases should not show "unofficial build". 

Honestly, I would be in favor of removing use of `gitBranch`, `buildNum`, and `gitHash` entirely from the UI and our build process. It's not really useful now that we're tagging the final Docker images with the appropriate SHAs.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/component_registration/layout.html, line 56 at r4](https://reviewable.io/reviews/openmpf/openmpf/988#-LzIwEHW66OtJDDPCEhR:-Lzn-lvr9EyuTRddawYK:bw7gdyp) ([raw file](https://github.com/openmpf/openmpf/blob/b3b6ec19e7259293c99c7835f0b3d5937441c0eb/trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/component_registration/layout.html#L56)):*
The simplified Component Registration page looks better. Please also do the following when the "docker" profile is active:

1. Change the page heading from "Component Upload and Registration" to "Component Registration".

2. Change the "i" tooltip help to:

> "Unmanaged components, such as Docker services, self-register with the Workflow Manager. Removing one of these components through this page will not prevent it from self-registering in the future. If a component with the same name as an existing component attempts to register itself, the one with the higher version number will take precedence. If they have the same version number, the newest one will take precedence."

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 112 at r7](https://reviewable.io/reviews/openmpf/openmpf/988#-Lzra7EtACKZNN2qWNoo:-LzsDJM_Cw-U32gwrsqt:bb6ywmx) ([raw file](https://github.com/openmpf/openmpf/blob/9c2d326e5854cea3569d6dd6d818904fd06da478/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L112)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note to self: Check swagger page when docker profile is enabled.
</blockquote></details>

LGTM

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestServiceImpl.java, line 71 at r6](https://reviewable.io/reviews/openmpf/openmpf/988#-LznJeY44fwh9WdvwGm8:-LzwOwkL0k_A-ZZthd1k:bh7yqs5) ([raw file](https://github.com/openmpf/openmpf/blob/407dffdc75b4baefc9b3850238a18342ace2e81c/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestServiceImpl.java#L71)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note to self: Test streaming job locally.
</blockquote></details>

In ITWebStreamingHealthReports.java this first exception is not thrown:

```
    @BeforeClass
    public static void initialize() throws ComponentRegistrationException, IOException {
```

Tests pass locally.

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/directive_templates/navbar.html, line 55 at r10](https://reviewable.io/reviews/openmpf/openmpf/988#-M0-_kJ5-f45BgLsHAo1:-M0KG6R4-wDOIqndnj_a:b-xl8p5k) ([raw file](https://github.com/openmpf/openmpf/blob/c187cd9a7845206664946b554f721b5603df561d/trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/directive_templates/navbar.html#L55)):*
> Please correct this to say "Edit property settings".

Actually, that doesn't apply to the non-admin user. Please change to "View property settings".

Also "Edit OpenMPF Properties" doesn't apply to the non-admin user. Please change the title to "OpenMPF Properties".

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/directive_templates/navbar.html, line 55 at r10](https://reviewable.io/reviews/openmpf/openmpf/988#-M0-_kJ5-f45BgLsHAo1:-M0YX1-A6tPAcAI5X6sJ:b-u1s2sk) ([raw file](https://github.com/openmpf/openmpf/blob/c187cd9a7845206664946b554f721b5603df561d/trunk/workflow-manager/src/main/webapp/resources/mytheme/js/angular_app/directive_templates/navbar.html#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

> Please correct this to say "Edit property settings".

Actually, that doesn't apply to the non-admin user. Please change to "View property settings".

Also "Edit OpenMPF Properties" doesn't apply to the non-admin user. Please change the title to "OpenMPF Properties".
</blockquote></details>

Sorry if I wasn't clear. I didn't ask you to change the menu text from "Properties" to "OpenMPF Properties". That was fine the way it was. Rather, I was asking you to change the menu title (the h3 header that shows up at the top of the page when you're viewing it - right underneath the top banner), from "Edit OpenMPF Properties" to "OpenMPF Properties".

The code in question is in openmpf/trunk/workflow-manager/src/main/webapp/WEB-INF/html/admin/property_settings/layout.html, line 28.

**Pull request merged**
