### PR TITLE
Support HEIC and crushed PNGs

### PR DESCRIPTION
**Pull request by brosenberg42**
Resolves https://github.com/openmpf/openmpf/issues/1130
Resolves https://github.com/openmpf/openmpf/issues/1028

Associated PR: https://github.com/openmpf/openmpf-docker/pull/123

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1189)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
Let's land your PRs before my PRs.

> Reviewed 29 of 29 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1189#-:-MK8-ttH9iQv78vW0BZi:b-cpljbf)* status: all files reviewed, 5 unresolved discussions (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java, line 202 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1egO56QaOEO8vfDvP:-MK1egO56QaOEO8vfDvQ:b-fkgw12) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java#L202)):*
> ```Java
>             }
>             catch (IOException e) {
>                 if (!e.getMessage().contains("Connection reset by peer")) {
> ```

When do you encounter this exception?
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 160 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK7x4bD048OXktcCOPU:-MK7x4bE4_sBtmF3LJOW:b46b9ju) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L160)):*
> ```Java
>                             "Failed to delete the converted media file '%s' - " +
>                                     "it must be manually deleted.",
>                             media.getLocalPath()), e);
> ```

You want `media.getConvertedMediaPath()` here.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PngDefry.java, line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1hq8Y9CoTQl8mCgZP:-MK1hq8Y9CoTQl8mCgZQ:biwck3o) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PngDefry.java#L89)):*
> ```Java
>                         .waitFor();
> 
>             if (exitCode != 0) {
> ```

I also check the error stream in my code when I call `file`. If you trust pngdefry to always return a non-zero error code when there's a problem then this is fine. Also, if you know pngdefry will log to error when there isn't an error, then this is fine.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java, line 292 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1ikOO-Xp844ztMGWU:-MK1ikOO-Xp844ztMGWV:b-duc9im) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java#L292)):*
> ```Java
>     /** Tests that media inspection is properly skipped when given valid audio metadata. */
>     @Test(timeout = 5 * MINUTES)
>     public void testSkipAudioInspection() {
> ```

Seems like these skip tests should be in `TestMediaMetadataValidator.java`.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestPngDefry.java, line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1jUOR8-sBetwymYpF:-MK1jUOS1gBCF4JRt4ga:b-2jneuc) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestPngDefry.java#L46)):*
> ```Java
> 
>     private static final Path CRUSHED_IMG
>             = TestUtil.findFilePath("/samples/pngdefry/lenna-crushed.png");
> ```

Add new Lenna files and HEIC file to the NOTICE:

```
# IMG_5355.HEIC
Public Domain


# pngdefry/lenna-crushed.png, pngdefry/lenna-normal.png
Created by running the following command on a MacBook Pro:
"xcrun --sdk iphoneos pngcrush -iphone -force lenna-normal.png lenna-crushed.png"

Original lenna-normal.png image taken from https://en.wikipedia.org/wiki/File:Lenna_(test_image).png, which states:
"Use of this 512x512 scan is 'overlooked' and by implication permitted by Playboy."
```

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java, line 202 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1egO56QaOEO8vfDvP:-MK85WUCBdEs8QP0q21g:b-o6vyr5) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java#L202)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

When do you encounter this exception?
</blockquote></details>

Note that this does not resolve the "Caused by: java.io.IOException: Broken pipe" issue I've been seeing. Oddly, I cannot recreate the issue by deploying a stack on my local VM. It only shows up when I deploy the stack on the test cluster and when I deploy it on the Jenkins build VM.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1189)* status: 24 of 30 files reviewed, 4 unresolved discussions (waiting on @brosenberg42 and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java, line 202 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1egO56QaOEO8vfDvP:-MKFN3On8_9rPm8cVV9u:b-bjfbpl) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/mvc/controller/ServerMediaController.java#L202)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Note that this does not resolve the "Caused by: java.io.IOException: Broken pipe" issue I've been seeing. Oddly, I cannot recreate the issue by deploying a stack on my local VM. It only shows up when I deploy the stack on the test cluster and when I deploy it on the Jenkins build VM.
</blockquote></details>

When doing a non-Docker deployment or a docker stack deploy and using Chrome, this error shows up when the browser tries to get the preview image on the job creation page. When I do a docker-compose deployment and use Chrome, I see the "Caused by: java.io.IOException: Broken pipe" issue. When using Firefox, I never see any exception.

I decided to fix the issue in ControllerUncaughtExceptionHandler since I don't think we ever want to treat ClientAbortException as an error.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java, line 160 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK7x4bD048OXktcCOPU:-MKFL2k2ClT2TTZKrcuQ:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/InProgressBatchJobsService.java#L160)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You want `media.getConvertedMediaPath()` here.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PngDefry.java, line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1hq8Y9CoTQl8mCgZP:-MKFLVMHDdwgsEfs9pv1:b1sqt6x) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PngDefry.java#L89)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I also check the error stream in my code when I call `file`. If you trust pngdefry to always return a non-zero error code when there's a problem then this is fine. Also, if you know pngdefry will log to error when there isn't an error, then this is fine.
</blockquote></details>

I have a comment below that explains that pngdefry returns a success exit code no matter what. That is why I have to check if the output file was created.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java, line 292 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1ikOO-Xp844ztMGWU:-MKGN6yk7g5bANNMNi2o:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestMediaInspectionProcessor.java#L292)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Seems like these skip tests should be in `TestMediaMetadataValidator.java`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestPngDefry.java, line 46 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1jUOR8-sBetwymYpF:-MKFLLda-3O4bJjjA5Qh:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestPngDefry.java#L46)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add new Lenna files and HEIC file to the NOTICE:

```
# IMG_5355.HEIC
Public Domain


# pngdefry/lenna-crushed.png, pngdefry/lenna-normal.png
Created by running the following command on a MacBook Pro:
"xcrun --sdk iphoneos pngcrush -iphone -force lenna-normal.png lenna-crushed.png"

Original lenna-normal.png image taken from https://en.wikipedia.org/wiki/File:Lenna_(test_image).png, which states:
"Use of this 512x512 scan is 'overlooked' and by implication permitted by Playboy."
```
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1189)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PngDefry.java, line 89 at r1](https://reviewable.io/reviews/openmpf/openmpf/1189#-MK1hq8Y9CoTQl8mCgZP:-MKegYa5EmxoHo0dlahD:b-lsaxsh) ([raw file](https://github.com/openmpf/openmpf/blob/8cd0fab6036815eb19713f9917d8d80d7c00d7d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PngDefry.java#L89)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I have a comment below that explains that pngdefry returns a success exit code no matter what. That is why I have to check if the output file was created.
</blockquote></details>

Ok. Based on what you said, I'm assuming that nothing useful is returned on the error stream to help determine if the operation was successful or not.

**Pull request merged**
