### PR TITLE
Added optional feed-forward locations/tracks to detection protobufs

### PR DESCRIPTION
**Pull request by clnowacki**
Updated the detection protobuf definitions to allow optional feed-forward locations/tracks in a job request. Updated the C++ and Java Messenger and component executor code to handle the feed-forward locations/tracks.

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/197)

### CODE REVIEW

**Comment by jrobble** [comment]
Did a quick visual review and nit-picked some style issues. I still need to run this code.

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[trunk/detection/executor/cpp/main.cpp, line 280 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk5kIXF-iwmNroMpjH:-Kqk5kIXF-iwmNroMpjI:b-vfabm2) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/main.cpp#L280)):*
> ```cpp
>                                 // Invoke the detection component
>                                 // without a feed-forward track
>                                 MPFVideoJob video_job(job_name.str(), data_uri,
> ```

Please have `data_uri` on its own line to match the constructor use above.

---

*[trunk/detection/executor/cpp/main.cpp, line 342 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk61iwF-k6_B_3QrIx:-Kqk61iwF-k6_B_3QrIy:bhsobrn) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/main.cpp#L342)):*
> ```cpp
>                                 LOG4CXX_INFO(logger, "[" << job_name.str() << "] Processing feed-forward location on " << service_name << ".");
>                                 // Invoke the detection component with
>                                 // a feed-forward location
> ```

Please put this comment above the above log line to match the audio and video sections.

---

*[trunk/detection/executor/cpp/MPFDetectionBuffer.cpp, line 105 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk77pz2VcmwwLFcnLa:-Kqk77pz2VcmwwLFcnLb:bgrzlil) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/MPFDetectionBuffer.cpp#L105)):*
> ```cpp
>             video_request.feed_forward_track.detection_properties[prop.key()] = prop.value();
>         }
>         for ( auto loc : detection_request.video_request().feed_forward_track().frame_locations()) {
> ```

Remove space before `auto`.

---

*[trunk/detection/executor/cpp/MPFDetectionBuffer.cpp, line 144 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk712PIo52TIxmdKkl:-Kqk712QiLBj0W7cMTuq:bjpxidm) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/MPFDetectionBuffer.cpp#L144)):*
> ```cpp
> void MPFDetectionBuffer::GetImageRequest(MPFDetectionImageRequest &image_request) {
>     image_request.has_feed_forward_location = false;
>     if (detection_request.image_request().has_feed_forward_location()) {
> ```

Add a comment here about copying the feed forward location (like how you have a similar comment for audio and video).

---

*[trunk/detection/executor/cpp/MPFDetectionBuffer.cpp, line 157 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk6v7BVLmWsIK0Lvcv:-Kqk6v7BVLmWsIK0Lvcw:b-nb6cm6) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/MPFDetectionBuffer.cpp#L157)):*
> ```cpp
>                 detection_request.image_request().feed_forward_location().confidence();
>     }
>     for (auto prop : detection_request.image_request().feed_forward_location().detection_properties()) {
> ```

Add a comment here about copying the track properties like you have for audio and video.

---

*[trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java, line 63 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk7WFRAHtLovnN-myB:-Kqk7WFRAHtLovnN-myC:b-prmjii) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java#L63)):*
> ```Java
> 
>     public Map<String, String> copyProperties(List<DetectionProtobuf.PropertyMap> prop_map) {
> 	Map<String, String> props = new HashMap<String, String>();
> ```

Check left indentation here and on the other lines you added. 

---

*[trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java, line 69 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk7TWtou9FXYo41EQX:-Kqk7TWtou9FXYo41EQY:b8rk0gv) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java#L69)):*
> ```Java
> 	return props;
>     }
>     public MPFMessageMetadata getMessageMetadata(final byte[] requestContents) {
> ```

Add blank line above here.

---

*[trunk/protobuf/src/main/proto/detection.proto, line 149 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk4jM8V2oymAwEvySu:-Kqk4jM8V2oymAwEvySv:btsf4cg) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/protobuf/src/main/proto/detection.proto#L149)):*
> ```protobuf
> 
> 	// The track generated by a previous stage in a feed-forward pipeline.
> 	optional VideoTrack feed_forward_track = 3;
> ```

Please check left indentation for this line and the other lines you added.

---

*[trunk/protobuf/src/main/proto/detection.proto, line 159 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk4yVo3QiaudPzeeIK:-Kqk4yVo3QiaudPzeeIL:bl6sd92) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/protobuf/src/main/proto/detection.proto#L159)):*
> ```protobuf
>         // The stop time to process in the audio or video file.
>         optional int32 stop_time = 2 [default = -1];
> 	// The track generated by a previous stage in a feed-forward pipeline.
> ```

Please add a blank line above this one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/197#-:-Kqk8w40idDE63A7oR90:b-nfwzoe)*

**Comment by clnowacki** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[trunk/detection/executor/cpp/main.cpp, line 280 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk5kIXF-iwmNroMpjH:-Kr0sfUVnLn26DDBP-75:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/main.cpp#L280)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please have `data_uri` on its own line to match the constructor use above.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/main.cpp, line 342 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk61iwF-k6_B_3QrIx:-Kr0tAUoxT_tQxWewfLL:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/main.cpp#L342)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please put this comment above the above log line to match the audio and video sections.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/MPFDetectionBuffer.cpp, line 105 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk77pz2VcmwwLFcnLa:-Kr0u1FLUKGu62JrG5Ju:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/MPFDetectionBuffer.cpp#L105)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Remove space before `auto`.
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/MPFDetectionBuffer.cpp, line 144 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk712PIo52TIxmdKkl:-Kr0uIG1tDGOI5hWLQGx:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/MPFDetectionBuffer.cpp#L144)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a comment here about copying the feed forward location (like how you have a similar comment for audio and video).
</blockquote></details>

Done.

---

*[trunk/detection/executor/cpp/MPFDetectionBuffer.cpp, line 157 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk6v7BVLmWsIK0Lvcv:-Kr0uTXYP_aPFJiBmWVf:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/cpp/MPFDetectionBuffer.cpp#L157)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add a comment here about copying the track properties like you have for audio and video.
</blockquote></details>

Done.

---

*[trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java, line 63 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk7WFRAHtLovnN-myB:-Kr0zv6Al5hcS3qTi_iq:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java#L63)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Check left indentation here and on the other lines you added. 
</blockquote></details>

Done.

---

*[trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java, line 69 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk7TWtou9FXYo41EQX:-Kr0zuRvtz98vMYjSZeh:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java#L69)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Add blank line above here.
</blockquote></details>

Done.

---

*[trunk/protobuf/src/main/proto/detection.proto, line 149 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk4jM8V2oymAwEvySu:-Kr1-NT0iWTNoZesb3cx:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/protobuf/src/main/proto/detection.proto#L149)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please check left indentation for this line and the other lines you added.
</blockquote></details>

Done.

---

*[trunk/protobuf/src/main/proto/detection.proto, line 159 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/197#-Kqk4yVo3QiaudPzeeIK:-Kr1-VjStMWzyQMRaq9_:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/236761b40092d75daf0b9e72e1f3e07b9d093156/trunk/protobuf/src/main/proto/detection.proto#L159)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add a blank line above this one.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/197)*

**Comment by jrobble** [comment]
Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/197)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/197)*

**Pull request merged**
