### PR TITLE
Added routes for handling dead letters.

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/186)

### CODE REVIEW

**Comment by jrobble** [comment]
To test this I modified openmpf-cpp-component-sdk/detection/examples/HelloWorldComponent/HelloWorld.cpp:

```
diff --git a/detection/examples/HelloWorldComponent/HelloWorld.cpp b/detection/examples/HelloWorldComponent/HelloWorld.cpp
index 68bb556..9fae095 100644
--- a/detection/examples/HelloWorldComponent/HelloWorld.cpp
+++ b/detection/examples/HelloWorldComponent/HelloWorld.cpp
@@ -28,6 +28,8 @@
 #include <iostream>
 #include "HelloWorld.h"
 
+#include <signal.h>
+
 //-----------------------------------------------------------------------------
 /* virtual */ bool HelloWorld::Init() {
 
@@ -59,6 +61,11 @@ MPFDetectionError HelloWorld::GetDetections(const MPFVideoJob &job,
               << "\" from frame " << job.start_frame
               << " to frame " << job.stop_frame << "." << std::endl;
 
+
+    if (job.start_frame > 150 && job.start_frame < 250) {
+        raise(SIGSEGV); // DEBUG
+    }
+
     // The MPFVideoJob structure contains two Properties entries, one
     // that contains job-specific properties, and one that contains
     // media-specific properties.  The frame processing interval is one
@@ -131,6 +138,8 @@ MPFDetectionError HelloWorld::GetDetections(const MPFImageJob &job,
     // process an image file.
     std::cout << "[" << job.job_name << "] Processing \"" << job.data_uri << "\"." << std::endl;
 
+    raise(SIGSEGV); // DEBUG
+
     // Detection logic goes here
 
     MPFImageLocation image_location(0, 0, 100, 100);
```

Running an image through "HELLOWORLD DETECTION PIPELINE" will cause the HelloWorldComponent component service to terminate. You should then go to the Nodes page in the UI and start the service again. After 6 failed redelivery attempts the message will be placed on the "ActiveMQ.DLQ" and then immediately consumed due to the code in DlqRouteBuilder. The job status in the UI will change to "COMPLETE_WITH_ERRORS" (as opposed to being left "IN_PROGRESS", the current behavior). The JSON output will show:

```
"detectionProcessingErrors": { "+#HELLOWORLD DETECTION ACTION": [ { "startOffset": 0, "stopOffset": 0, "message": "DEAD_LETTER" } ] }
```

Running a video through "HELLOWORLD DETECTION PIPELINE" will cause the HelloWorldComponent component service to terminate when processing a segment that starts in the range (150, 250). You should then go to the Nodes page in the UI and start the service again. After 6 failed redelivery attempts the message will be placed on the "ActiveMQ.DLQ". I recommend testing a video that generates at least two segments. The first one will be processed just fine while the second will have this issue.

If you go to the ActiveMQ management page you will see that "ActiveMQ.DLQ" has 1 consumer. You will also see unconsumed messages in "MPF.PROCESSED_DLQ_MESSAGES". These are left for auditing purposes. The "Message Detail" for these shows the string representation of the original job request protobuf message.

**Comment by brosenberg42** [comment]
Review status: 0 of 16 files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java, line 72 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/186#-Kq8AGiO9Rq9UfEfufAJ:-Kq8AGiO9Rq9UfEfufAK:b-5ou62h) ([raw file](https://github.com/openmpf/openmpf/blob/14a43e58b0fe2803615d1e4f41d778467713a32b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java#L72)):*
> ```Java
> 			.setExchangePattern(ExchangePattern.InOnly)
> 			.choice()
> 				.when(header(MpfHeaders.JMS_REPLY_TO).isEqualTo(MpfEndpoints.COMPLETED_DETECTIONS_REPLY_TO)) // otherwise leave message on the default DLQ (for auditing)
> ```

To test this I added messages to the DLQ that don't match this predicate. The messages were silently consumed. There was no log message, and the messages were not in the  jms:MPF.PROCESSED_DLQ_MESSAGES queue.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java, line 72 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/186#-Kq8AGiO9Rq9UfEfufAJ:-Kq8P3cDtKAlNoTu7xqo:b-8c7mlc) ([raw file](https://github.com/openmpf/openmpf/blob/14a43e58b0fe2803615d1e4f41d778467713a32b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java#L72)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

To test this I added messages to the DLQ that don't match this predicate. The messages were silently consumed. There was no log message, and the messages were not in the  jms:MPF.PROCESSED_DLQ_MESSAGES queue.
</blockquote></details>

How did you add these messages?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186)*

**Comment by brosenberg42** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java, line 72 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/186#-Kq8AGiO9Rq9UfEfufAJ:-Kq8Tph-o7TajGCltsil:bx30ql9) ([raw file](https://github.com/openmpf/openmpf/blob/14a43e58b0fe2803615d1e4f41d778467713a32b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java#L72)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How did you add these messages?
</blockquote></details>

Through the ActiveMQ management web page.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186)*

**Comment by jrobble** [comment]
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java, line 72 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/186#-Kq8AGiO9Rq9UfEfufAJ:-Kq8Psff4SplRXsIRLnO:b2av1mj) ([raw file](https://github.com/openmpf/openmpf/blob/14a43e58b0fe2803615d1e4f41d778467713a32b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java#L72)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Through the ActiveMQ management web page.
</blockquote></details>

Good find! I'm now using a selector. The warning at the bottom of [this page](https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.0/html/Implementing_Enterprise_Integration_Patterns/files/MsgEnd-Selective.html) made it clear what the issue was.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186)*

**Comment by brosenberg42** [comment]
I think we want to preserve the content of MPF.PROCESSED_DLQ_MESSAGES when the workflow manager restarts.
To do this you can add the queue to the whitelist property in mpf.properties:
```
# A comma-separated list of queues not to purge.
jmx.amq.broker.whiteList=MPF.PROCESSED_DLQ_MESSAGES
```

---

Reviewed 15 of 16 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java, line 72 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/186#-Kq8AGiO9Rq9UfEfufAJ:-Kq8ju1TY5hTPTSWTHs-:bdmdr0n) ([raw file](https://github.com/openmpf/openmpf/blob/14a43e58b0fe2803615d1e4f41d778467713a32b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java#L72)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Good find! I'm now using a selector. The warning at the bottom of [this page](https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.0/html/Implementing_Enterprise_Integration_Patterns/files/MsgEnd-Selective.html) made it clear what the issue was.
</blockquote></details>

This is a minor thing, but I think this looks nicer as a single route:
```
fromF("%s?selector=%s", entryPoint, encodedSelector)
        .routeId(routeId)
        .setExchangePattern(ExchangePattern.InOnly)
        .multicast()
            .pipeline()
                .unmarshal().protobuf(DetectionProtobuf.DetectionRequest.getDefaultInstance()).convertBodyTo(String.class)
                .to(exitPoint)
            .end()
            .pipeline()
                .process(DetectionDeadLetterProcessor.REF)
                .to(MpfEndpoints.COMPLETED_DETECTIONS)
            .end()
        .end();
```
This is just personal preference so do what you prefer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186#-:-Kq8jE_WF7vXGe2mjk95:b7hv8jo)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java, line 72 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/186#-Kq8AGiO9Rq9UfEfufAJ:-Kq8mY_d5fpHJ1sHfb3g:b-qt2a7q) ([raw file](https://github.com/openmpf/openmpf/blob/14a43e58b0fe2803615d1e4f41d778467713a32b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java#L72)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

This is a minor thing, but I think this looks nicer as a single route:
```
fromF("%s?selector=%s", entryPoint, encodedSelector)
        .routeId(routeId)
        .setExchangePattern(ExchangePattern.InOnly)
        .multicast()
            .pipeline()
                .unmarshal().protobuf(DetectionProtobuf.DetectionRequest.getDefaultInstance()).convertBodyTo(String.class)
                .to(exitPoint)
            .end()
            .pipeline()
                .process(DetectionDeadLetterProcessor.REF)
                .to(MpfEndpoints.COMPLETED_DETECTIONS)
            .end()
        .end();
```
This is just personal preference so do what you prefer.
</blockquote></details>

Oops, the `from` in that route won't work with how you set up the URI, it should be:
```
from(entryPoint + selector)
        .routeId(routeId)
        .setExchangePattern(ExchangePattern.InOnly)
        .multicast()
            .pipeline()
                .unmarshal().protobuf(DetectionProtobuf.DetectionRequest.getDefaultInstance()).convertBodyTo(String.class)
                .to(exitPoint)
            .end()
            .pipeline()
                .process(DetectionDeadLetterProcessor.REF)
                .to(MpfEndpoints.COMPLETED_DETECTIONS)
            .end()
        .end();
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186)*

**Comment by jrobble** [comment]
> I think we want to preserve the content of MPF.PROCESSED_DLQ_MESSAGES

Done.

---

Review status: 15 of 17 files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java, line 72 at r1](https://reviewable.io:443/reviews/openmpf/openmpf/186#-Kq8AGiO9Rq9UfEfufAJ:-Kq9gjiAnWUk1pJ3zMh6:b-7rvduy) ([raw file](https://github.com/openmpf/openmpf/blob/14a43e58b0fe2803615d1e4f41d778467713a32b/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/routes/DlqRouteBuilder.java#L72)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Oops, the `from` in that route won't work with how you set up the URI, it should be:
```
from(entryPoint + selector)
        .routeId(routeId)
        .setExchangePattern(ExchangePattern.InOnly)
        .multicast()
            .pipeline()
                .unmarshal().protobuf(DetectionProtobuf.DetectionRequest.getDefaultInstance()).convertBodyTo(String.class)
                .to(exitPoint)
            .end()
            .pipeline()
                .process(DetectionDeadLetterProcessor.REF)
                .to(MpfEndpoints.COMPLETED_DETECTIONS)
            .end()
        .end();
```
</blockquote></details>

I agree, your approach is nicer. I updated the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186#-:-Kq9gt1QhIt4Bhk1O65K:b-5myxf0)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/186#-:-Kq9xOlgCi9XnvqvoTov:bnfp4nl)*

**Pull request merged**
