### PR TITLE
Add support for setuptools Python components and automatically create virtualenv during component registration.

### PR DESCRIPTION
**Pull request by brosenberg42**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)

### CODE REVIEW

**Comment by jrobble** [comment]
As discussed, four things: 
1. Remove Ansible task that installs virtual env.
2. Update Build Guide so that user pip installs virtualenv and wheel.
3. Update Build Guide so that user downloads virtualenv module.
4. Add an Ansible task to the full deployment process to pip install virtualenv from the local Ansible repo.

Refer to https://github.com/openmpf/openmpf/issues/567 for # 2 and # 3.

---

Reviewed 9 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---

*[trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml, line 173 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCoQQ_nEHp8ettIqbEz:-LCoQQ_o4FogVf01oiAy:b-xuo21w) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml#L173)):*
> ```YAML
> 
> 
>     - name: Check if component is a Python component
> ```

As discussed, this file only seems to be used when registering components through the web UI. Please ensure that Python components can be installed through the full deployment process as well.

Please refer to compregistration.yml, which is used at deployment time.

---

*[trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml, line 192 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCniRRK51qXZtdYpe7_:-LCniRRK51qXZtdYpe7a:b9zhdw) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml#L192)):*
> ```YAML
>     - name: Setup virtualenv for Python setuptools-based component
>       pip:
>         name: "{{ext_component_descriptor.batchLibrary}}"
> ```

What about streaming-only Python components?

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnjNzQC0S_QQQWXJpY:-LCnj-nw0bbdS1sw40sq:b1np2jm) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/main.cpp#L68)):*
> ```cpp
> }
> 
> bool is_python(log4cxx::LoggerPtr &logger, int argc, char* argv[]);
> ```

Is this forward declaration necessary?

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 153 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnk9ShEy7IumwAu3Ra:-LCnk9ShEy7IumwAu3Rb:bs5jkpd) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/main.cpp#L153)):*
> ```cpp
>                        static_cast<int(*)(int)>(std::tolower));
> 
>         if (std::string("python") == argv[4]) {
> ```

Do you want to use `provided_language` here instead of `argv[4]`?

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 156 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnkGxx2dBaoclw3Z3f:-LCnkGxx2dBaoclw3Z3g:bs5jkpd) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/main.cpp#L156)):*
> ```cpp
>             return true;
>         }
>         if (std::string("c++") == argv[4]) {
> ```

Do you want to use `provided_language` here instead of `argv[4]`?

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/test_env_activate.py, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnnNHX5_sHT-GWlfFe:-LCnnNHX5_sHT-GWlfFf:bzf1z1z) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/test/test_python_components/test_env_activate.py#L1)):*
> ```Python
> import sys
> ```

Please add header comments.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java, line 473 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnnlta1P_XTV0M3yEC:-LCnnlta1P_XTV0M3yED:b-tf70d3) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/service/component/AddComponentServiceImpl.java#L473)):*
> ```Java
>                 algorithmService.addArg(descriptor.batchLibrary);
>                 algorithmService.addArg(queueName);
>                 algorithmService.addArg(descriptor.sourceLanguage.getValue());
> ```

Note to self: Test Sphinx component.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565#-:-LCoinrkByCOj1Uzc6ms:bfwx62b)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by brosenberg42** [comment]
Review status: 6 of 10 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml, line 173 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCoQQ_nEHp8ettIqbEz:-LCp8yPm1FNRkh358HNM:b-723cqf) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml#L173)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

As discussed, this file only seems to be used when registering components through the web UI. Please ensure that Python components can be installed through the full deployment process as well.

Please refer to compregistration.yml, which is used at deployment time.
</blockquote></details>

I put the venv stuff in a separate file. I only call it here. If this passes on Jenkins I will add the call to compregistration.yml

---

*[trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml, line 192 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCniRRK51qXZtdYpe7_:-LCp9HTDBxGlPF-o36ri:b-xjpvfm) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml#L192)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What about streaming-only Python components?
</blockquote></details>

That is taken care of in setup_python_component_venv.yml

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnjNzQC0S_QQQWXJpY:-LCp9NQKChD0tMzbBK5W:b-fth7bv) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/main.cpp#L68)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is this forward declaration necessary?
</blockquote></details>

If I moved the function up there I could get rid of the forward declaration, but I like having main very close to the top. Before, is_python was very short.

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 153 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnk9ShEy7IumwAu3Ra:-LCp9kLg2qBSnzAdCGpA:bb77ufg) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/main.cpp#L153)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you want to use `provided_language` here instead of `argv[4]`?
</blockquote></details>

Yes.

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 156 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnkGxx2dBaoclw3Z3f:-LCp9lVS1fk3mneF55AP:bb77ufg) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/main.cpp#L156)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you want to use `provided_language` here instead of `argv[4]`?
</blockquote></details>

Yes.

---

*[trunk/detection/executor/cpp/batch/test/test_python_components/test_env_activate.py, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnnNHX5_sHT-GWlfFe:-LCp9nod8C4SjBVGlpuf:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/test/test_python_components/test_env_activate.py#L1)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Please add header comments.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by jrobble** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml, line 174 at r3](https://reviewable.io/reviews/openmpf/openmpf/565#-LCpF4ZcBufIkF73RBgn:-LCpF4ZcBufIkF73RBgo:bfbf0iy) ([raw file](https://github.com/openmpf/openmpf/blob/4b65aaece9d5923abdd471163e293844285cfad2/trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml#L174)):*
> ```YAML
>     - include: setup_python_component_venv.yml
>       vars:
>         component_path: "{{ plugins_dir }}/{{ component_tld }}"
> ```

Note to self: Test component registration on startup and through web UI.

---

*[trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml, line 36 at r3](https://reviewable.io/reviews/openmpf/openmpf/565#-LCpEZGv6CjFoW2L60wg:-LCpEZGv6CjFoW2L60wh:b-40p8cm) ([raw file](https://github.com/openmpf/openmpf/blob/4b65aaece9d5923abdd471163e293844285cfad2/trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml#L36)):*
> ```YAML
> - name: Setup virtualenv for Python setuptools-based component
>   pip:
>     name: "{{ descriptor.batchLibrary | default('') }} {{ descriptor.streamLibrary | default('') }}"
> ```

What if the batch and stream libs have different names?

---

*[trunk/detection/executor/cpp/batch/main.cpp, line 68 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCnjNzQC0S_QQQWXJpY:-LCpElA9CSXxJydlurA7:bfjftfp) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/detection/executor/cpp/batch/main.cpp#L68)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

If I moved the function up there I could get rid of the forward declaration, but I like having main very close to the top. Before, is_python was very short.
</blockquote></details>

Ok. I thought as much. Works for me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml, line 36 at r3](https://reviewable.io/reviews/openmpf/openmpf/565#-LCpEZGv6CjFoW2L60wg:-LCpH-ye5hYqYGTG9k1m:b-jst9hn) ([raw file](https://github.com/openmpf/openmpf/blob/4b65aaece9d5923abdd471163e293844285cfad2/trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml#L36)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What if the batch and stream libs have different names?
</blockquote></details>

That will normally be the case. I think the edge case would be when they have the same name. 
I tested this locally by changing it to
`name: "{{ descriptor.batchLibrary | default('') }} {{ descriptor.streamLibrary | default('') }} Flask {{ descriptor.batchLibrary | default('') }}"`
That way it tested different library names and duplicated library names. 

There is nothing special about flask, it's just a random package.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml, line 173 at r1](https://reviewable.io/reviews/openmpf/openmpf/565#-LCoQQ_nEHp8ettIqbEz:-LD2LCgU-zWeo5Vd5HzL:b-ke5f9u) ([raw file](https://github.com/openmpf/openmpf/blob/98a6656a91a977aaa8271d369bb809f4fdb9d1cf/trunk/ansible/install/ansible/roles/child/tasks/compdeploy.yml#L173)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I put the venv stuff in a separate file. I only call it here. If this passes on Jenkins I will add the call to compregistration.yml
</blockquote></details>

I tested local deployment. That worked as expected. I will test deployment on a separate VM once you push those changes.

---

*[trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml, line 36 at r3](https://reviewable.io/reviews/openmpf/openmpf/565#-LCpEZGv6CjFoW2L60wg:-LD2Q4x28gxH_wMlxmW3:b-dzb10g) ([raw file](https://github.com/openmpf/openmpf/blob/4b65aaece9d5923abdd471163e293844285cfad2/trunk/ansible/install/ansible/roles/child/tasks/setup_python_component_venv.yml#L36)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

That will normally be the case. I think the edge case would be when they have the same name. 
I tested this locally by changing it to
`name: "{{ descriptor.batchLibrary | default('') }} {{ descriptor.streamLibrary | default('') }} Flask {{ descriptor.batchLibrary | default('') }}"`
That way it tested different library names and duplicated library names. 

There is nothing special about flask, it's just a random package.
</blockquote></details>

Based on our discussion, this seems fine.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[trunk/ansible/install/ansible/roles/child/tasks/compregistration.yml, line 82 at r4](https://reviewable.io/reviews/openmpf/openmpf/565#-LD3RlRg5FJJHpjMJdsi:-LD3RlRg5FJJHpjMJdsj:bc7zoe5) ([raw file](https://github.com/openmpf/openmpf/blob/1d640de6b99db6b8bf4d91f37efbbf1aec85aea4/trunk/ansible/install/ansible/roles/child/tasks/compregistration.yml#L82)):*
> ```YAML
> 
> 
> - name: Load external component descriptor
> ```

I’m going to hold off on testing deployment until you have a chance to:

1. Add an Ansible task to install pip on child nodes
2. Add an Ansible task to install virtualenv on all nodes (note that master is also a child)

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by jrobble** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by jrobble** [comment]
Reviewed 5 of 5 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[trunk/mpf-install/base-pom.xml, line 100 at r6](https://reviewable.io/reviews/openmpf/openmpf/565#-LDDTLAc-uaid-V3doZT:-LDDTLAc-uaid-V3doZU:b4m0cny) ([raw file](https://github.com/openmpf/openmpf/blob/ab0f6110b8ecf386ed0a48ff98977ef5baa9d70f/trunk/mpf-install/base-pom.xml#L100)):*
> ```XML
>                                 See https://ant.apache.org/manual/Tasks/chmod.html -->
>                                 <chmod perm="755" verbose="true" maxparallel="100">
>                                     <fileset dir="${basedir}/../install" excludes="plugins/**"/>
> ```

What happened that motivated you to add this?

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java, line 525 at r6](https://reviewable.io/reviews/openmpf/openmpf/565#-LDDTFvUCqBYebZQ-HdU:-LDDTFvUCqBYebZQ-HdV:b4m0cny) ([raw file](https://github.com/openmpf/openmpf/blob/ab0f6110b8ecf386ed0a48ff98977ef5baa9d70f/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java#L525)):*
> ```Java
>         String key = "startup.num.services.per.component";
>         try {
>             return mpfPropertiesConfig.getInt(key, 0);
> ```

What happened that motivated you to add this?

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by brosenberg42** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[trunk/mpf-install/base-pom.xml, line 100 at r6](https://reviewable.io/reviews/openmpf/openmpf/565#-LDDTLAc-uaid-V3doZT:-LDDUTMXBRhBm1469x42:b-5xmgg5) ([raw file](https://github.com/openmpf/openmpf/blob/ab0f6110b8ecf386ed0a48ff98977ef5baa9d70f/trunk/mpf-install/base-pom.xml#L100)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What happened that motivated you to add this?
</blockquote></details>

It was following a symlink into /usr/include/python2.7 and trying to change permissions there.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java, line 525 at r6](https://reviewable.io/reviews/openmpf/openmpf/565#-LDDTFvUCqBYebZQ-HdU:-LDDUlVQ6MBIJEjrpQR8:bwkg2jv) ([raw file](https://github.com/openmpf/openmpf/blob/ab0f6110b8ecf386ed0a48ff98977ef5baa9d70f/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/PropertiesUtil.java#L525)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

What happened that motivated you to add this?
</blockquote></details>

Deployment failed because `startup.num.services.per.component` was missing.
It was originally declared as:
```
// Defaults to zero if property not set.
@Value("${startup.num.services.per.component:0}")
private int numStartUpServices;
public int getNumStartUpServices() {
    return numStartUpServices;
}
```
The `:0` made it optional.

---


*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by jrobble** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565)*

**Comment by jrobble** [comment]
Tested this via deployment upgrade. Works as expected.

---

Review status: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/565#-:-LDo6ba98zroaBdNzSmw:bda89s3)*

**Pull request merged**
