### PR TITLE
Feat/protobuf refactor

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1769

**Related PRs:**
- https://github.com/openmpf/openmpf-docker/pull/210

- - -
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1773)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 49 of 62 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1773)* status: all files reviewed, 14 unresolved discussions (waiting on @brosenberg42)

___
*[`trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java` line 59 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSgIBY7LAsGAsmKdaA:-NtSgIBaBME2qlre6F7I:b-8b9x58) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java#L59)):*
> ```Java
>     }
> 
>     public Map<String, String> copyProperties(List<DetectionProtobuf.PropertyMap> prop_map) {
> ```

Why are copies no longer necessary? Were they ever?
___
*[`trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java` line 233 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSgWHP7Qz7hfKItKlY:-NtSgWHP7Qz7hfKItKlZ:birlaaz) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java#L233)):*
> ```Java
> 
> 			// Record the success.
> 			LOG.debug("Request built and sent response. Error: {}.", detectionResponse.getError());
> ```

Is the request id not useful for these logs? I can't say I've ever used it.
___
*[`trunk/interop/src/main/java/org/mitre/mpf/interop/JsonStreamingDetectionOutputObject.java` line 84 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSguUK5JkU7iH33c_o:-NtSguUK5JkU7iH33c_p:b-1v9xjn) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonStreamingDetectionOutputObject.java#L84)):*
> ```Java
> 			@JsonProperty("height") int height,
> 			@JsonProperty("confidence") float confidence,
> 			@JsonProperty("detectionProperties") Map<String, String> detectionProperties,
> ```

Do we not care about sorting anymore?
___
*[`trunk/protobuf/CMakeLists.txt` line 55 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTOcCPCMxpIDX5ckz4:-NtTOcCV73UO7d66SMc2:bkslxuy) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/protobuf/CMakeLists.txt#L55)):*
> ```CMake
> target_include_directories(mpfProtobufs PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
> 
> # Video overlay is a shared library, so it needs to link with the shared version of libprotobuf.
> ```

How did this work before we started using the shared lib? Why is it required now?
___
*[`trunk/protobuf/src/main/proto/detection.proto` line 154 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtNNgRx4VW8W1mj-Shb:-NtNNgS-7UBDceL6DlgZ:byl0sy8) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/protobuf/src/main/proto/detection.proto#L154)):*
> ```proto
>     int32 action_index = 5;
> 
>     oneof response_type {
> ```

`oneof` ... nice!
___
*[`trunk/protobuf/src/main/proto/markup.proto` line 58 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtWl_ioECnmaKHGuXcI:-NtWl_ip3jfxhrHWYyVL:bcdxlcj) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/protobuf/src/main/proto/markup.proto#L58)):*
> ```proto
>     repeated MarkupRequestPropertyMap markup_properties  = 9; // The collection of arbitrary key-value pairs.
> 
>     required int32 task_index         = 501; // The index of the task which produced this request.
> ```

Why remove these indexes? I see that you left them in `detection.proto`. Were they simply unnecessary since there can only be one markup action/task per job?
___
*[`trunk/video-overlay/src/test/java/org/mitre/mpf/videooverlay/TestBoundingBoxWriter.java` line 139 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTTgD12rndcTP9PwVp:-NtTTgD12rndcTP9PwVq:bu0aprd) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/video-overlay/src/test/java/org/mitre/mpf/videooverlay/TestBoundingBoxWriter.java#L139)):*
> ```Java
>                 .setRotationDegrees(270)
>                 .setFlip(false)
>                 .setRed(2500)
> ```

This should be 255.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionContext.java` line 59 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtWdXUuErk8zi_n6hQ7:-NtWdXUv-tq5yNnGeG-R:b-j509up) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionContext.java#L59)):*
> ```Java
> 
>     private final List<AlgorithmPropertyProtocolBuffer.AlgorithmProperty> algorithmProperties;
>     public List<AlgorithmPropertyProtocolBuffer.AlgorithmProperty> getAlgorithmProperties() {
> ```

It was ugly to have the protobuf data member in here. Glad to see it go.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 201 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTWQUBEhI4M-hqLFET:-NtTWQUC35rTdU1IY-zF:b-7g0b4r) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L201)):*
> ```Java
>         boolean isMediaType = trackType.equals("MEDIA");
>         for (DetectionProtobuf.VideoTrack objectTrack : videoResponse.getVideoTracksList()) {
>             SortedMap<String, String> trackProperties = toImmutableMap(objectTrack.getDetectionPropertiesList());
> ```

Do we not care about immutable any more?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java` line 133 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTYu5dBaNP-sb96orY:-NtTYu5dBaNP-sb96orZ:bssvbxr) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java#L133)):*
> ```Java
>     }
> 
>     private static int getMediaIndex(BatchJob job, Media media) {
> ```

This seems a little odd because we used to pass the media index in the protobuf. Although, in the grand scheme of things this code will not be executed often or take very long. What was your motivation for removing media index?
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/MediaSegmenter.java` line 79 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtWbDwd8yMb-NNFCqJ1:-NtWbDwd8yMb-NNFCqJ2:b-l62mq9) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/MediaSegmenter.java#L79)):*
> ```Java
>                     || algoProps.containsKey(FEED_FORWARD_TOP_QUALITY_COUNT)) {
>             return algoProps.entrySet().stream()
>                 .filter(e -> !e.getKey().equals(FEED_FORWARD_TYPE))
> ```

Why are we filtering out these properties? A code comment would help.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionResponseProcessor.java` line 203 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtWdvWj8DsxmKLzqSpD:-NtWdvWj8DsxmKLzqSpE:bcnasso) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionResponseProcessor.java#L203)):*
> ```Java
>                                 .setConfidence(0.5f)
>                                 .putDetectionProperties(
>                                         "TRACK_TEST_PROP_KEY", "TRACK_TEST_PROP_KEY")
> ```

You want "TRACK_TEST_PROP_VALUE" as the second parameter.
___
*[`trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/JniLoader.java` line 47 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSo-7G5xWHfqzxx7Qa:-NtSo-7G5xWHfqzxx7Qb:b3qb91y) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/JniLoader.java#L47)):*
> ```Java
>         catch (UnsatisfiedLinkError ex) {
>             log.warn("System.loadLibrary() failed due to: {}", ex.getMessage());
>             String libDir = System.getenv("MPF_HOME") + "/lib";
> ```

Why not use `EnvVar`?
___
*[`trunk/video-overlay/src/test/java/org/mitre/mpf/OverlayTestUtils.java` line 34 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTQ3uy-f8lrMQa8qZf:-NtTQ3uzDeGYMPup6Bwe:b-9l06ld) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/video-overlay/src/test/java/org/mitre/mpf/OverlayTestUtils.java#L34)):*
> ```Java
> import org.slf4j.LoggerFactory;
> 
> public class DefaultCallbackSkeleton extends CallbackSkeleton {
> ```

Was `DefaultCallbackSkeleton` never used?

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1773)* status: all files reviewed, 12 unresolved discussions (waiting on @jrobble)

___
*[`trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java` line 59 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSgIBY7LAsGAsmKdaA:-NtWwYnbDbmDGqKMy0bG:b-6ji2ur) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionBuffer.java#L59)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why are copies no longer necessary? Were they ever?
</blockquote></details>

It is no longer necessary because the protobuf now uses `map<string, string> detection_properties` instead of `repeated PropertyMap detection_properties`.
___
*[`trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java` line 233 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSgWHP7Qz7hfKItKlY:-NtWnu_O67LWxazuFCdg:beg4hhr) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java#L233)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Is the request id not useful for these logs? I can't say I've ever used it.
</blockquote></details>

I've never used either, so it is hard to justify its existence.
___
*[`trunk/interop/src/main/java/org/mitre/mpf/interop/JsonStreamingDetectionOutputObject.java` line 84 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSguUK5JkU7iH33c_o:-NtWoWaX4dfGQyZ9pnh2:bm72d3g) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/interop/src/main/java/org/mitre/mpf/interop/JsonStreamingDetectionOutputObject.java#L84)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we not care about sorting anymore?
</blockquote></details>

`this.detectionProperties.putAll(detectionProperties);` is called in the constructor below. That ensures it is sorted. I wanted to pass in a regular Map because that is what other code returned. The constructor already copies the Map once. I would have to copy my regular Map in to a TreeMap only for the constructor to copy it again.
___
*[`trunk/protobuf/CMakeLists.txt` line 55 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTOcCPCMxpIDX5ckz4:-NtWqFAo9zog3BcTn-8p:b-gmu9an) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/protobuf/CMakeLists.txt#L55)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

How did this work before we started using the shared lib? Why is it required now?
</blockquote></details>

It's required now because the C++ code accesses the markup request through the protobuf rather than JNI.
___
*[`trunk/protobuf/src/main/proto/markup.proto` line 58 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtWl_ioECnmaKHGuXcI:-NtWqnov3bYA4Cna010e:bnq5ou5) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/protobuf/src/main/proto/markup.proto#L58)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why remove these indexes? I see that you left them in `detection.proto`. Were they simply unnecessary since there can only be one markup action/task per job?
</blockquote></details>

They are unnecessary because there can only be one markup task. 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 201 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTWQUBEhI4M-hqLFET:-NtWsdrx-qVwuAs1zMLI:b-vy1f76) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L201)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do we not care about immutable any more?
</blockquote></details>

We never really cared about immutability. That method was for converting the `Collection<DetectionProtobuf.PropertyMap>` to a `Map<String, String>`. The `Track` constructor will end up copying that in to an `ImmutableSortedMap` anyway. Passing in an `ImmutableSortedMap` prevented a copy because `ImmutableSortedMap.copyOf` does not actually create a copy when the parameter is already a `ImmutableSortedMap`. We can't prevent that copy because the protobuf returns a regular Map. 
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java` line 133 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTYu5dBaNP-sb96orY:-NtWvxQwBv0M5DLS6vD4:bg1rthu) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/markup/MarkupResponseProcessor.java#L133)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This seems a little odd because we used to pass the media index in the protobuf. Although, in the grand scheme of things this code will not be executed often or take very long. What was your motivation for removing media index?
</blockquote></details>

It's a change in direction from including everything that seems like it could be useful, to including only the fields that are absolutely necessary. Including things "just in case" makes the code more confusing. Regarding the performance, I think my change would improve performance, but it does not matter because we are talking about nanoseconds here. Also, having both a media index and media id is confusing throughout the WFM code.
___
*[`trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/JniLoader.java` line 47 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtSo-7G5xWHfqzxx7Qa:-NtWrMsz00jg8RCCBBPB:b-65ndna) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/video-overlay/src/main/java/org/mitre/mpf/videooverlay/JniLoader.java#L47)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why not use `EnvVar`?
</blockquote></details>

`EnvVar` is part of Workflow Manager. I moved the JniLoader from Workflow Manager to VideoOverlay. The VideoOverlay code shouldn't depend on the calling library to find the JNI libraries it needs. I think there were 3 separate places where we were looking for those libraries all slightly differently. Now it is impossible to load the VideoOverlay classes without finding the Jni libraries that they need for their native methods.
___
*[`trunk/video-overlay/src/test/java/org/mitre/mpf/OverlayTestUtils.java` line 34 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTQ3uy-f8lrMQa8qZf:-NtWsFc35X7Y2vD60p4A:b-w1pbq8) ([raw file](https://github.com/openmpf/openmpf/blob/3fe48e15c7341defdba07facb661913f2cd787d7/trunk/video-overlay/src/test/java/org/mitre/mpf/OverlayTestUtils.java#L34)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Was `DefaultCallbackSkeleton` never used?
</blockquote></details>

Not recently. At some point it might have been used, but it would have been a long time ago.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1773)* status: 58 of 62 files reviewed, 5 unresolved discussions (waiting on @jrobble)

___
*[`trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java` line 94 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtX_mgM7LhrBOL6yJJj:-Nt_prng0hSOW_kqDS-A:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/detection/executor/java/src/main/java/org/mitre/mpf/component/executor/detection/MPFDetectionMessenger.java#L94)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I think this comment can be removed.
</blockquote></details>

Done.
___
*[`trunk/video-overlay/src/test/java/org/mitre/mpf/videooverlay/TestBoundingBoxWriter.java` line 139 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTTgD12rndcTP9PwVp:-Nt_pg0g05ryUICf36K9:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/video-overlay/src/test/java/org/mitre/mpf/videooverlay/TestBoundingBoxWriter.java#L139)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

This should be 255.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java` line 150 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtTUeHbCYsm7shrtGkv:-Nt_jbtHD1q65UfrR-r9:b-an73r4) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionResponseProcessor.java#L150)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Do you know of a scenario where this code will be executed? Unless there is a coding bug, it seems that the executors should generate a response protobuf with one of the Response types.
</blockquote></details>

It would have to be a bug in one of the executors. Previously, we checked the number of responses to make sure it was 1 even though it could only be caused by a bug in the executor. I was trying to keep the same behavior.
___
*[`trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/MediaSegmenter.java` line 79 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtWbDwd8yMb-NNFCqJ1:-Nt_pQx-6OE7wtod-C_Y:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/segmenting/MediaSegmenter.java#L79)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Why are we filtering out these properties? A code comment would help.
</blockquote></details>

Done.
___
*[`trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionResponseProcessor.java` line 203 at r2](https://reviewable.io/reviews/openmpf/openmpf/1773#-NtWdvWj8DsxmKLzqSpD:-Nt_m-W4EE3zrVAyyRmu:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/b075e90ba64a563dfe68125927e2d9caca0c7c4f/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/camelOps/TestDetectionResponseProcessor.java#L203)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

You want "TRACK_TEST_PROP_VALUE" as the second parameter.
</blockquote></details>

Done.

**Review by jrobble — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1773)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
