### PR TITLE
Handle VFR videos

### PR DESCRIPTION
**Pull request by brosenberg42**
Resolves: openmpf/openmpf#1307

Associated PRs:
- https://github.com/openmpf/openmpf/pull/1310
- https://github.com/openmpf/openmpf-cpp-component-sdk/pull/102
- https://github.com/openmpf/openmpf-python-component-sdk/pull/45
- https://github.com/openmpf/openmpf-docker/pull/141

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1310)

### CODE REVIEW

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1310)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameRateTypeDetector.java, line 1 at r1](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZmhWtD1ousN1b7RLT7:-MZmhWtD1ousN1b7RLT8:b5p5zdl) ([raw file](https://github.com/openmpf/openmpf/blob/9eaec80ef5a6886eaf610f1c4c81f968f25ba389/trunk/workflow-manager/src/test/java/org/mitre/mpf/wfm/util/TestFrameRateTypeDetector.java#L1)):*
> ```Java
> package org.mitre.mpf.wfm.util;
> ```

Package should come after the header blocks, for consistency.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1310)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java, line 242 at r2](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZsCzpuBFw1gziLL26h:-MZsCzpuBFw1gziLL26i:bnorq3v) ([raw file](https://github.com/openmpf/openmpf/blob/10b999abc4ae6883130b1ddbe0cb47e04c2273a2/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L242)):*
> ```Java
>             SystemPropertiesSnapshot systemPropertiesSnapshot, Map<String, String> properties,
>             Media media) {
>         int targetSegmentLength = systemPropertiesSnapshot.getTargetSegmentLength();
> ```


Need `detection.vfr.segment.minimum.length`.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java, line 267 at r2](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZsBvo23zruvZmzWoFT:-MZsBvo46IjF6lIs6equ:b4czesx) ([raw file](https://github.com/openmpf/openmpf/blob/10b999abc4ae6883130b1ddbe0cb47e04c2273a2/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L267)):*
> ```Java
>                     }
>                 }
>                 if (!hasConstantFrameRate &&
> ```

Could make this an `else if`.

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1310)* status: 16 of 20 files reviewed, 1 unresolved discussion (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java, line 242 at r2](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZsCzpuBFw1gziLL26h:-MZseExo9qTZdGKpOh4s:b-896fix) ([raw file](https://github.com/openmpf/openmpf/blob/10b999abc4ae6883130b1ddbe0cb47e04c2273a2/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L242)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Need `detection.vfr.segment.minimum.length`.
</blockquote></details>

Done.
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java, line 267 at r2](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZsBvo23zruvZmzWoFT:-MZse2wpEJSc_5X9uQt4:b-v73ho1) ([raw file](https://github.com/openmpf/openmpf/blob/10b999abc4ae6883130b1ddbe0cb47e04c2273a2/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L267)):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Could make this an `else if`.
</blockquote></details>

The whole function is a mess. I was trying to make the minimal number of changes.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1310)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

___
*[trunk/workflow-manager/src/main/resources/workflow-properties.json, line 146 at r3](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZtHKTJ62bU6I3Uaa2_:-MZtHKTJ62bU6I3Uaa2a:b-btgd61) ([raw file](https://github.com/openmpf/openmpf/blob/d85a5e04c63e250fbed00c131a267f5e798177e0/trunk/workflow-manager/src/main/resources/workflow-properties.json#L146)):*
> ```JSON
>         "description": "In the context of variable segment length videos, the minimum length of a segment which will be processed by this algorithm. Value must be greater than 0.",
>         "type": "INT",
>         "propertiesKey": "detection.segment.minimum.length",
> ```

This should be `detection.vfr.segment.minimum.length`.
___
*[trunk/workflow-manager/src/main/resources/properties/mpf.properties, line 182 at r3](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZtHV8t48QfHAx-NFKx:-MZtHV8u4ivzYZuk07a5:b553aer) ([raw file](https://github.com/openmpf/openmpf/blob/d85a5e04c63e250fbed00c131a267f5e798177e0/trunk/workflow-manager/src/main/resources/properties/mpf.properties#L182)):*
This should be:

> "overridden in a detection action by providing the VFR_MIN_SEGMENT_LENGTH property".

**Comment by jrobble** [comment]
___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java, line 272 at r3](https://reviewable.io/reviews/openmpf/openmpf/1310#-MZtOfU1EcXhNu2GFewu:-MZtOfU5A1zkpIZ4hVXH:b-ea8mp9) ([raw file](https://github.com/openmpf/openmpf/blob/d85a5e04c63e250fbed00c131a267f5e798177e0/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/camel/operations/detection/DetectionTaskSplitter.java#L272)):*
> ```Java
>         int targetSegmentLength = tryParseIntProperty(
>                 targetSegmentLengthPropName, properties,
>                 systemPropertiesSnapshot.getTargetSegmentLength());
> ```

If a user provides an non-numerical value for `VFR_TARGET_SEGMENT_LENGTH`, the default value will be the target segment length system property for CFR, not VFR.

There is a similar issue for the `VFR_MIN_SEGMENT_LENGTH` in the code below.

**Review by jrobble — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1310)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

**Pull request merged**
