### PR TITLE
Feature/persist callback status

### PR DESCRIPTION
**Pull request by brosenberg42**
**Issues:**
- https://github.com/openmpf/openmpf/issues/1396

---
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)

### CODE REVIEW

**Review by clnowacki — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42 and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java, line 51 at r2](https://reviewable.io/reviews/openmpf/openmpf/1471#-MurDTTC0pmG1LiKQhge:-MurDTTD-p1dYmwxvKSi:b-4a7sqq) ([raw file](https://github.com/openmpf/openmpf/blob/38ce1222155b1d64c981493017ce29130883b1f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java#L51)):*
> ```Java
> 
>     public AllJobsStatisticsModel getJobStats();
> ```

I'm curious why you decided to have two sets of 3 functions, instead of just having the two: setTiesDbStatus(jobid,status) and setCallbackStatus(jobid,status). What is your motivation for doing it this way?

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: all files reviewed, 1 unresolved discussion (waiting on @clnowacki and @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java, line 51 at r2](https://reviewable.io/reviews/openmpf/openmpf/1471#-MurDTTC0pmG1LiKQhge:-MuueZDF52h4-WB7znTl:b-hck1k1) ([raw file](https://github.com/openmpf/openmpf/blob/38ce1222155b1d64c981493017ce29130883b1f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java#L51)):*
<details><summary><i>Previously, clnowacki wrote…</i></summary><blockquote>

I'm curious why you decided to have two sets of 3 functions, instead of just having the two: setTiesDbStatus(jobid,status) and setCallbackStatus(jobid,status). What is your motivation for doing it this way?
</blockquote></details>

I felt that the other parts of the code shouldn't need to know the exact way in which this information is persisted. Also, if I just had the two functions, I would have to declare something like:
```java
public class CallbackStatuses {
    public static final String NOT_REQUESTED = "NOT REQUESTED";
    public static final String SUCCESS = "SUCCESS";
    public static String error(String reason) {
        return "ERROR: " + reason;
    }
}
```
and then call it like `jobRequestDao.setTiesDbStatus(jobId, CallbackStatuses.SUCCESS)`. 

By doing it the way I did it in the PR, those strings all appear in the same class in about the same location. Since they are close together and the strings are only used twice, I felt that adding `public static final String` variables was unnecessary.

**Review by clnowacki — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jrobble)

___
*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java, line 51 at r2](https://reviewable.io/reviews/openmpf/openmpf/1471#-MurDTTC0pmG1LiKQhge:-Muzo_K-A2e4sbsqk3lP:bwsnv7m) ([raw file](https://github.com/openmpf/openmpf/blob/38ce1222155b1d64c981493017ce29130883b1f8/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/access/JobRequestDao.java#L51)):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

I felt that the other parts of the code shouldn't need to know the exact way in which this information is persisted. Also, if I just had the two functions, I would have to declare something like:
```java
public class CallbackStatuses {
    public static final String NOT_REQUESTED = "NOT REQUESTED";
    public static final String SUCCESS = "SUCCESS";
    public static String error(String reason) {
        return "ERROR: " + reason;
    }
}
```
and then call it like `jobRequestDao.setTiesDbStatus(jobId, CallbackStatuses.SUCCESS)`. 

By doing it the way I did it in the PR, those strings all appear in the same class in about the same location. Since they are close together and the strings are only used twice, I felt that adding `public static final String` variables was unnecessary.

</blockquote></details>

Ok, thanks for the explanation. Looks good.

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 7 of 13 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: all files reviewed, 2 unresolved discussions (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1471#-Mv5jGFICk5s46SQ5gMg:-Mv5jGFICk5s46SQ5gMh:bf20s9d) (no related file):*
I noticed that the UI will show `JOB RUNNING` until you either you refresh the page, or the job completes. Then the `TiesDb` and `Callback` status will change. Is it intentional that the status doesn't transition to `IN PROGRESS` automatically?

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1471#-Mv5ks5d6ZQeE8JxmWNt:-Mv5ks5d6ZQeE8JxmWNu:bvrg8mi) (no related file):*
I saw an error message like this when I clicked on the `ERROR` button:

```
ERROR: Sending HTTP POST to TiesDb (http://localhost:8083/api/db/supplementals?sha256Hash=7e497501a28bcf9a353ccadf6eb9216bf098ac32888fb542fb9bfe71d486761f) for OCV GENERIC MARKUP ACTION failed due to: java.net.ConnectException: Connection refused 
```

The pipeline I ran was `OCV FACE DETECTION (WITH MARKUP) PIPELINE`. This message by itself makes me assume that the `OCV FACE DETECTION ACTION` succeeded since it's not mentioned. I know it didn't because I was using a dummy endpoint.

It boils down to this code, which results in only recording one TiesDb error:

```java
        var errorMessage = String.format(
                "Sending HTTP POST to TiesDb (%s) for %s failed due to: %s",
                url, action, error);
        LOG.error(errorMessage, error);
        _jobRequestDao.setTiesDbError(jobId, errorMessage);
```

It may be worth asking the users if they care to know which action failed in the dialog, or if they just want to know that one of the actions failed since they would probably re-run the whole job anyway. In any case, we should log the exact actions that failed.

---

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @clnowacki and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1471#-Mv5jGFICk5s46SQ5gMg:-MvJsNAE54C47PpHPbEl:b-lpm3vm) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I noticed that the UI will show `JOB RUNNING` until you either you refresh the page, or the job completes. Then the `TiesDb` and `Callback` status will change. Is it intentional that the status doesn't transition to `IN PROGRESS` automatically?
</blockquote></details>

That is how it worked before. 

---
*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1471#-Mv5ks5d6ZQeE8JxmWNt:-MvJsRnZ3UJaynqctDZZ:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

I saw an error message like this when I clicked on the `ERROR` button:

```
ERROR: Sending HTTP POST to TiesDb (http://localhost:8083/api/db/supplementals?sha256Hash=7e497501a28bcf9a353ccadf6eb9216bf098ac32888fb542fb9bfe71d486761f) for OCV GENERIC MARKUP ACTION failed due to: java.net.ConnectException: Connection refused 
```

The pipeline I ran was `OCV FACE DETECTION (WITH MARKUP) PIPELINE`. This message by itself makes me assume that the `OCV FACE DETECTION ACTION` succeeded since it's not mentioned. I know it didn't because I was using a dummy endpoint.

It boils down to this code, which results in only recording one TiesDb error:

```java
        var errorMessage = String.format(
                "Sending HTTP POST to TiesDb (%s) for %s failed due to: %s",
                url, action, error);
        LOG.error(errorMessage, error);
        _jobRequestDao.setTiesDbError(jobId, errorMessage);
```

It may be worth asking the users if they care to know which action failed in the dialog, or if they just want to know that one of the actions failed since they would probably re-run the whole job anyway. In any case, we should log the exact actions that failed.
</blockquote></details>

Done.

---

**Review by jrobble — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: all files reviewed, 1 unresolved discussion (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1471#-Mv5jGFICk5s46SQ5gMg:-MvK8_Cg6eKe_RaRMBAR:b7nclfl) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

That is how it worked before. 
</blockquote></details>

Yeah, but I think it's something we should fix. Currently, the UI (if broadcasts are enabled) and job status endpoint are not in sync. The UI says `IN_PROGRESS` at 99% and `JOB RUNNING` for the callbacks which the endpoint returns `COMPLETE`at 100% and `IN_PROGRESS`, respectively.

---

**Review by brosenberg42 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: 6 of 17 files reviewed, 1 unresolved discussion (waiting on @brosenberg42, @clnowacki, and @jrobble)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1471#-Mv5jGFICk5s46SQ5gMg:-MvQ24Wk3a8i5mZZqoD1:b-896fix) (no related file):*
<details><summary><i>Previously, jrobble (Jeff Robble) wrote…</i></summary><blockquote>

Yeah, but I think it's something we should fix. Currently, the UI (if broadcasts are enabled) and job status endpoint are not in sync. The UI says `IN_PROGRESS` at 99% and `JOB RUNNING` for the callbacks which the endpoint returns `COMPLETE`at 100% and `IN_PROGRESS`, respectively.
</blockquote></details>

Done.

---

**Review by jrobble — APPROVED** [review]
> Reviewed 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/openmpf/openmpf/1471)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @brosenberg42)

*[a discussion](https://reviewable.io/reviews/openmpf/openmpf/1471#-Mv5jGFICk5s46SQ5gMg:-MvePLtBBeFiAFD6fbMY:bex5br4) (no related file):*
<details><summary><i>Previously, brosenberg42 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Looks great. I like the dummy spinner.

---

**Pull request merged**
