### PR TITLE
Handle streaming messages

### PR DESCRIPTION
**Pull request by jrobble**
This change is [Reviewable](https://reviewable.io/reviews/openmpf/openmpf/435)

### CODE REVIEW

**Comment by brosenberg42** [comment]
Reviewed 16 of 25 files at r1, 3 of 6 files at r2, 11 of 11 files at r3.
Review status: all files reviewed at latest revision, 13 unresolved discussions.

---

*[trunk/node-manager/src/main/java/org/mitre/mpf/nms/MasterNodeStateManager.java, line 225 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4aVF_cXmNkL97H2EJD:-L4aVF_dCxEaHhpX1kFC:b-wmmqv9) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/node-manager/src/main/java/org/mitre/mpf/nms/MasterNodeStateManager.java#L225)):*
> ```Java
>             LOG.info("Shutting down all the services currently running: {}", getServiceTable().size());
>             getServiceTable().values().forEach(this::shutdownService);
>             streamingJobManager.stopAllJobs();
> ```

I think this should be outside the synchronized block.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java, line 299 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4b3s7FRcFGRpdbUqKy:-L4b3s7FRcFGRpdbUqKz:b-szju0k) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L299)):*
> ```Java
>         if (streamingJobRequest == null) {
>             throw new JobCancellationInvalidJobIdWfmProcessingException("A streaming job with the id " + jobId + " is not known to the system.");
>         } else {
> ```

This method is pretty deeply nested, but it doesn't need to be. Here, you don't need an else after a throw.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java, line 301 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4b46zb2DuPevszdoAK:-L4b46zb2DuPevszdoAL:bsm7wni) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L301)):*
> ```Java
>         } else {
> 
>             assert streamingJobRequest.getStatus()
> ```

`assert`s don't do anything at runtime unless you pass certain command line arguments to the JVM.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java, line 315 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4b4pSIB6nD8mbLrTdi:-L4b4pSIB6nD8mbLrTdj:b39p8dl) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L315)):*
> ```Java
>                 }
>                 throw new JobAlreadyCancellingWfmProcessingException(errorMessage);
>             } else {
> ```

Again, you don't need an else after a throw.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java, line 319 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4b4w-ny1Vx6X8FxWJx:-L4b4w-ny1Vx6X8FxWJy:b4etv82) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L319)):*
> ```Java
> 
>                 // Mark the streaming job as cancelled in Redis
>                 if (redis.cancel(jobId)) {
> ```

I would either invert this if to reduce nesting or add a return at the end of the if so you don't need the else

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java, line 353 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4b6AQ7Z7jDElvpTunZ:-L4b6AQ7Z7jDElvpTun_:b26d54x) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L353)):*
> ```Java
>      * was detected in specification of the jobs output object directory.
>      */
>     public synchronized void cleanup(long jobId, String outputObjectDirPath) throws WfmProcessingException {
> ```

`@Override` is missing

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java, line 656 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4bA_jhLFdw_JsucU8b:-L4bA_jhLFdw_JsucU8c:b-unr1lk) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L656)):*
> ```Java
> 
>         LocalDateTime time = LocalDateTime.now();
>         summaryReport.setReportDate(time);
> ```

This seems like something that should be a constructor parameter.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java, line 717 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4bBeZhEvLgiSjQfkVA:-L4bBeZhEvLgiSjQfkVB:b-vo2s7z) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/businessrules/impl/StreamingJobRequestBoImpl.java#L717)):*
> ```Java
>                 healthReportCallbackUriToActiveJobIdListMap.keySet().stream().forEach(
>                     healthReportCallbackUri -> callbackUtils.doHealthReportCallback(
>                             healthReportCallbackUriToActiveJobIdListMap.get(healthReportCallbackUri), healthReportCallbackUri));
> ```

This should either be:
```
healthReportCallbackUriToActiveJobIdListMap
      .forEach((uri, ids) -> callbackUtils.doHealthReportCallback(ids, uri));
```

or if you switch the order of the parameters to doHealthReportCallback it could be:
```
healthReportCallbackUriToActiveJobIdListMap
    .forEach(callbackUtils::doHealthReportCallback);
```

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java, line 389 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4azUkLVgLVsyH4aJxC:-L4azUkLVgLVsyH4aJxD:byobhz8) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java#L389)):*
> ```Java
>      * @throws WfmProcessingException is thrown if this method is attempted to be used for a batch job.
>      */
>     @SuppressWarnings("unchecked")
> ```

This is missing `@Override`.
Also `@SuppressWarnings("unchecked")` doesn't do anything here.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java, line 522 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4b--eJW_SXZPrlP7M9:-L4b--eJW_SXZPrlP7MA:ba6u7il) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java#L522)):*
> ```Java
>      */
>     @Override
>     @SuppressWarnings("unchecked")
> ```

`@SuppressWarnings("unchecked")` doesn't do anything here.

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java, line 526 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4b-1hdiJzZzMAj0ydg:-L4b-1hdiJzZzMAj0ydh:b-xu9it9) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/RedisImpl.java#L526)):*
> ```Java
>         return getStreamingJobStatuses(jobIds).stream().map(streamingJobStatus -> {
>             return streamingJobStatus.toString();
>         }).collect(Collectors.toList());
> ```

This should be:
```
return getStreamingJobStatuses(jobIds).stream()
    .map(StreamingJobStatus::toString)
    .collect(Collectors.toList());
```

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/StreamingJobStatus.java, line 103 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4actEqQOQP65iiVaue:-L4actEqQOQP65iiVauf:b-jtngas) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/data/entities/persistent/StreamingJobStatus.java#L103)):*
> ```Java
>     @Override
>     public int hashCode() {
>         return System.identityHashCode(this.type);
> ```

Non-final fields should not be used in equals and hashCode. Can we get rid of the setters or get rid of the equals and hashCode overrides? If we keep equals and hashCode then this should be changed to `return type.hashCode();`

---

*[trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java, line 107 at r3](https://reviewable.io:443/reviews/openmpf/openmpf/435#-L4bCHcQURFswrvUbZzQ:-L4bCHcQURFswrvUbZzR:b-smj5j1) ([raw file](https://github.com/openmpf/openmpf/blob/4fc6a94946362b5b71fed3a7ec3b4fe4c109bf6e/trunk/workflow-manager/src/main/java/org/mitre/mpf/wfm/util/CallbackUtils.java#L107)):*
> ```Java
> 
>     // Send the health report to the URI identified by callbackUri, using the HTTP POST method.
>     public void doHealthReportCallback(List<Long> jobIds, String callbackUri) {
> ```

I think "send" or "post" is more descriptive than "do".  I generally only use the do prefix when I need to disambiguate a private method. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/435)*

**Comment by jrobble** [comment]
As we discussed, please update this PR to send IN_PROGRESS after StreamingVideoCapture is created.

---

Review status: all files reviewed at latest revision, 13 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/435#-:-L4c0DyAHnpMKKdz7gy9:b-b1lk32)*

**Comment by brosenberg42** [comment]
When testing the callbacks the job stays in the INITIALIZING and never moves in to the IN_PROGRESS state. I know that transitioning from INITIALIZING to IN_PROGRESS is related to my PR, but I just want to make sure the current behavior is the behavior that you are expecting.

---

Reviewed 11 of 11 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/435#-:-L4fgjrh3NepLOAN7Hut:b-w9cozu)*

**Comment by jrobble** [comment]
Yes, that behavior is what I expect. The job won't transition to IN_PROGRESS until it gets a status update from the C++ Streaming Component Executor.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/435#-:-L4gS1KRpSgoVrwu6c1u:bvhe86d)*

**Comment by brosenberg42** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openmpf/openmpf/435#-:-L4gU8kW3K6_512H5Oj8:bnfp4nl)*

**Pull request merged**
